### ISSUE TITLE
Adding parameters when generating component in service.

### ISSUE THREAD

**Issue by sencagri** [Blazored/Modal#100]
Hello,

When we want to pass parameter to the component. We have to add [CascadingParameter] attribute inside relevant component. Instead of doing this I thougt we can add attributes in service when generating component. But I can't see the disadvantages of this method for future use.

I just changed the service code like below :

``` c#
       public void Show(Type contentComponent, string title, ModalParameters parameters, ModalOptions options)
        {
            if (!typeof(ComponentBase).IsAssignableFrom(contentComponent))
            {
                throw new ArgumentException($"{contentComponent.FullName} must be a Blazor Component");
            }

            var content = new RenderFragment(x =>
            {
                x.OpenComponent(1, contentComponent);

                int parameterCount = 1;
                foreach (var parameter in contentComponent.GetProperties())
                {
                    var parameterVal = parameters.Get<object>(parameter.Name);
                    if (parameterVal != null)
                    {
                        x.AddAttribute(parameterCount, parameter.Name, parameterVal);
                        parameterCount++;
                    }
                }

                x.CloseComponent();
            });

            _modalType = contentComponent;

            OnShow?.Invoke(title, content, parameters, options);
        }
```

**Comment by chrissainty** [comment]
Thanks for your feedback, @sencagri.

Are you suggesting we try and dynamically add attributes onto the child component being rendered?

**Comment by sencagri** [comment]
Yes. The downside part I found this kind of approach is you have to write the parameter names yourself. In case of refactoring this might be boring work.

**Comment by chrissainty** [comment]
Yeah, that definitely an issue. The other concern I have is the use of auto-incrementing sequence numbers. This isn't a good practice and makes Blazors diffing algorithm less efficient.

Based on these issues I don't think this is something I'd want to implement, but thank you for the suggestion.
