### ISSUE TITLE
Close Modal Async

### ISSUE THREAD

**Issue by marciusnery** [Blazored/Modal#101]
Hello, I need to close a modal while an asynchronous method is executed, but it is only closing when the execution is over. See the code below:

`<button type="button" @onclick=ConfirmarLeitura>Open</button>`

```
protected void ConfirmarLeitura()
    {        
        Modal.OnClose += ModalClosedLeitura;
        StateHasChanged();
        Modal.Show<ModalMessage>("", ModalConfig.GetParameters("Confirm reading the file?", "", "Fechar", true, "Question"));        
    }
```

```
private async void ModalClosedLeitura(ModalResult modalResult)
    {
        if (!modalResult.Cancelled)
        {
            await ReadFile();            
        }
        Modal.OnClose -= ModalClosedLeitura;
    }
```

In the ReadFile method I would like to close the confirmation modal and open a new one to display an image loading while reading the file.

```
public async Task ReadFile()
    {
        Modal.Show<ModalMessage>("", ModalConfig.GetParameters("Aguarde, estou carregando o documento.", "", "", false, "Loading"));
        Message = string.Empty;
        this.StateHasChanged();

        file = (await Reader.EnumerateFilesAsync()).FirstOrDefault();
        if (file != null)
        {
            try
            {
                Message = "Reading file...";
                this.StateHasChanged();
                var fileInRam = await file.CreateMemoryStreamAsync(4096);
                Message = "Parsing file...";
                this.StateHasChanged();
                using (var package = new OfficeOpenXml.ExcelPackage(fileInRam))
                {
                    Tables = EPPlusBuilder.ParseByWorksheetIndex(package, FirstRowIsHeader, 1);
                }

                this.StateHasChanged();
                Message = "Done.";                
                this.StateHasChanged();
                Modal.Close();
            }
            catch (Exception e)
            {
                Message = e.ToString();
            }
        }
    }
```

**Comment by chrissainty** [comment]
Hi @marciusnery, I don't think this is possible with the current way we do things with the modal. I'll need to do some investigation and get back to you.

**Comment by marciusnery** [comment]
It would be very useful if you had that possibility. In cases where processing is slow, we need to display something so that the user knows what's going on.

Thanks for your attention.

**Comment by Liero** [comment]
#103 would enable this. We could add Close() method to ModalReference, but Im not convinced it is a good practice.

**Comment by chrissainty** [comment]
@marciusnery I've just pushed a new major version to NuGet with a new programming model using async/await. Hopefully this should improve your situation. I'm going to close this issue for now but please feel free to reopen if you have further questions/issues.
