### ISSUE TITLE
Implement ModalReference

### ISSUE THREAD

**Issue by Liero** [Blazored/Modal#103]
# Motivation

current API design forces to subscribe to long living object (ModalService) and to unsubscribe from it.
It makes the application prone to memory leaks and code can be harder to read.

# Proposal

 - [ ] IModalService.Show(..) should return ModalReference - representation of the Modal instance
 - [ ] Closed event should be moved to ModalReference
 - [ ] [Optional] ModalReference can be used to access instance of the component

# Usage example

awaiting result: 

```csharp
var modal = Modal.Show<SignUpForm>("Sign Up Form");
var result = await modal.Result;
if (!result.Cancelled) ...
```

accessing component instance:

```csharp
var modal = Modal.Show<SignUpForm>("Sign Up Form");
modal.Showed += (instance) =>
{
    var signUpForm = (SignUpForm)instance;
    signUpForm.FirstName = "John";
    signUpForm.LastName = "Smith";
    signUpForm.FormSubmitted += () =>
    {
        Console.WriteLine($"Form has been submitted");
    };
};
```

Fixes also #94 
Makes possible also: #41

**Comment by chrissainty** [comment]
Hi @Liero, thank you for making this suggestion. It's an interesting design and certainly opens up some options for us with the control.

I've been quite busy the last few weeks with talks but I should be able to devote a decent amount of time to this over the next few weeks.

**Comment by Liero** [comment]
Well, PR is done, including examoles, only waiting for review

**Comment by chrissainty** [comment]
Hi @Liero, I've spent some time reviewing your proposal this morning but I have a few concerns. 

> IModalService.Show(..) should return ModalReference - representation of the Modal instance

Your code doesn't appear to do this, it returns an instance of the component being rendered inside the modal. There is still only one modal instance, so I don't think this opens any options regarding #41.

> var signUpForm = (SignUpForm)instance;
    signUpForm.FirstName = "John";
    signUpForm.LastName = "Smith";
    signUpForm.FormSubmitted += () =>
    {
        Console.WriteLine($"Form has been submitted");
    };

This code concerns me a lot. The internal workings of a component should stay internal. This will bypass some of Blazors events and potentially cause weird issues. Components should only have their state modified via their parameters (marked with `[Parameter]` attribute) or user interaction.

**Comment by chrissainty** [comment]
Based on my comments above, I'm going to close this in favour of #106. Thank you for your effort on this, it was a great help in getting to the latest changes.

**Comment by Liero** [comment]
@chrissainty: OK, thanks for your time.

Just out of curiosity, is there a documentation elaborating on this: 
> Generally speaking, components should only have their state modified via their parameters (marked with [Parameter] attribute) or user interaction.

**Comment by chrissainty** [comment]
@Liero I don't think there is anything "official" I can point you at for this, but the whole point of component parameters is to define the public API for the component. Blazor understands this and will correctly trigger rerenders when state changes, automatically, without manual intervention. 

Just to be clear, I'm not saying you _can't_ modify component state by capturing a reference and accessing any public properties or methods, it's just that often, it's not the best way. When you go this route you will have to manually tell Blazor that you have changed something and tell Blazor it needs to perform a rerender by calling `StateHasChanged`.

**Comment by Liero** [comment]
I see what you mean. Exactly the same situation is in Angular (Blazor is heavily inspired by Angular :) ).
However, the showed `Showed` event is supposed to be triggered in such event loop, where Blazor triggers change detection automatically (just like @onclick event, etc), so it should be safe. I just think typesafety is quite important and existing solution is not typesafe. I wish I could capture instance of the component before it is rendered to VDOM.

Anyway, you are the owner, this was just a suggestion.

Regarding:
> There is still only one modal instance
Yes, but the API design open the possibility. You don't need to change the API design in order to implement multiple modals

**Comment by chrissainty** [comment]
I think you miss understood my comment, I was referring to accessing the component being displayed in the modal, this code:

> var signUpForm = (SignUpForm)instance;
signUpForm.FirstName = "John";
signUpForm.LastName = "Smith";
signUpForm.FormSubmitted += () =>
{
Console.WriteLine($"Form has been submitted");
};

I'm not sure what you mean by typesafety though?

**Comment by Liero** [comment]
No, no, I think I understood you well.
When the component is accessed and it's properties are changed directly in Showed event, it should be fine in terms of change detection - StateHasChanged is called automatically, or even better, it is called before it is rendered, so StateHasChanged doesn't have to be called.

By typesafety I war referring to ModalParameters. I don't like I have to do this:

    var parameters = new ModalParameters();
    parameters.Add("MovieId", movieId);
    ....
    MovieId = Parameters.Get<int>("MovieId");

It's kind of violation of DRY principle, because the parameter name and the parameter type are implemented at two places without any compile time checking. If I change int to guid in the component, I only get runtime errors. With my design, I would get compiler error.
