### ISSUE TITLE
Blazored modal simply does not work

### ISSUE THREAD

**Issue by myket** [Blazored/Modal#107]
Perhaps I am the only one who cannot put this feature into operation... But I am sure that Blazored modal does not work based on the install guide you have written as a help. I have tried with a newly created blazor server side app. Unfortunately nothing happens if I click on the button..

**Comment by chrissainty** [comment]
Hi @myket, I agree this is probably a local issue as there are a lot of people using the control. Could you provide some information about what you have tried, what errors you're getting (if any). Something that we can use to try and help you.

**Comment by myket** [comment]
Hi, thank you for the quick answer. Unfortunately there are no errors that could lead to a solution. It simple does nothing. I have asked one of my friends, who works by a different company, to try it out and apply the setting covered by the description  and he told me same result.

**Comment by chrissainty** [comment]
Can you create a repo with your code in it so I can take a look please?

**Comment by myket** [comment]
Sorry for raising this issue. It was definitely my issue. Unfortunately I have skipped one step putting <BlazoredModal /> into MainLayout... Sorry for that and thank you for your promt support.

**Comment by myket** [comment]
Putting "component name" into... (html tags will be skipped here)
