### ISSUE TITLE
Can't reuse a component in Modal and Page

### ISSUE THREAD

**Issue by prabhakarreddy1234** [Blazored/Modal#109]
I've a child component which is supposed to be reused in a page and modal. This child component takes a DTO object as parameter and binds DTO properties to controls. It works fine when rendered inside Page.

But the same child component when rendered inside a Modal does't work as is. Since the way Modal passes an Object  or DTO or Parameters is different. ModelProperties needs to be accessed as `Parameters.Get<int>("MovieId");` which doesn't work when invoked from a Page. 

**Expected behavior**
It would be very useful if `Modal` passes the Model into the component the same way a Page passes the Model.

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Comment by larsk2009** [comment]
Hi @prabhakarreddy1234. This should be fixed in #106, so once a new version of Blazored.Modal is released, you can use the same components in pages and modals.

**Comment by chrissainty** [comment]
I'm going to close this issue @prabhakarreddy1234 as this should resolve later today when I publish the new version.
