### ISSUE TITLE
[Bug] Error after update to Blazor WebAssembly 3.2.0 Preview 2

### ISSUE THREAD

**Issue by marciusnery** [Blazored/Modal#110]
**Describe the bug**
Update the application to Blazor WebAssembly version 3.2.0 Preview 2 and when publishing I am having the following problem when trying to access.

> Unable to locate application dependencies. Ensure that the versions of  Microsoft.NetCore.App and Microsoft.AspNetCore.App targeted by the application  are installed.

In the event viewer I found a description of the error when starting the application in IIS. 

> Could not find  'aspnetcorev2_inprocess.dll'. Exception message: Error: An assembly specified in  the application dependencies manifest (DVCE.Server.deps.json) was not found:  package: 'Blazored.Modal', version: '3.1.2' path:  'lib/netstandard2.0/Blazored.Modal.dll'

**To Reproduce**
Update the app to Blazor WebAssembly version 3.2.0 Preview 2, publish and try to access the website.

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly wiht host server

**Comment by chrissainty** [comment]
Hi, @marciusnery. This could be down to the fact the current release isn't using the latest package versions. We have a new version which should hopefully be out later today that is fully up to date.

**Comment by marciusnery** [comment]
Thanks! I'm waiting for this update.

**Comment by marciusnery** [comment]
The problem continues. My client project is in the standard .net version 2.1. From the message it looks like it's depending on version 2.0.

Could not find  'aspnetcorev2_inprocess.dll'. Exception message: Error: An assembly specified in  the application dependencies manifest (DVCE.Server.deps.json) was not found:  package: 'Blazored.Modal', version: '4.0.0' path:  'lib/netstandard2.0/Blazored.Modal.dll'
--

**Comment by chrissainty** [comment]
@marciusnery I can't replicate this issue. I've tried on separate machines and both old and new apps and every time, the current version works fine.

Could you try creating a new app and installing the package and seeing if it works?

**Comment by marciusnery** [comment]
@chrissainty Did you publish the application on IIS server?

**Comment by chrissainty** [comment]
No I haven't. Is that where you're seeing the issue? Do you still get the same issue with a new app?

**Comment by marciusnery** [comment]
This problem only occurs when publishing the application on the IIS server. Running in visual studio does not occur.

I haven't tested it with a new application. I will update the .net core run time that came out yesterday, to see if it corrects this problem.

**Comment by marciusnery** [comment]
@chrissainty I found out what causes the problem. If you publish the application in debug mode, the error occurs.

I published in release mode and it worked. Thanks for listening.

**Comment by chrissainty** [comment]
Glad we got to the bottom of it @marciusnery 🙂
