### ISSUE TITLE
[Bug] the type of namespace name 'BlazoredModalInstance' could not be found

### ISSUE THREAD

**Issue by webebox** [Blazored/Modal#111]
**Describe the bug**
I just installed Blazord Modal. everything works but when I want to use BlazoredModalInstance in the modal component it says  : the type of namespace name 'BlazoredModalInstance' could not be found.
I tryed to use Blazored.Modal.BlazoredModalInstance
but this component is not exists.
My version is 3.1.2.

**Comment by larsk2009** [comment]
Hi @webebox . If you are using v3.1.2 of blazored.modal, please see this version of the readme instructions: https://github.com/Blazored/Modal/tree/v3.1.0. THe BlazoredModalInstance is introduced in v4.0.0 of blazored.modal, which has not been released yet.

**Comment by webebox** [comment]
Hi @larsk2009 , thank you for your reply. I just tryed the BlazorServer example, it includes 'Blazored.Modal' class library contains 'BlazoredModalInstance.razor' 
So how I can close the modal inside it when I can not make use of BlazoredModalInstance.Close method ?

**Comment by chrissainty** [comment]
@webebox If you [browse the repo at this point in time](https://github.com/Blazored/Modal/tree/3f8a54eaf3e4cdcc985ebe67249bb6c2f4ad3540) you can see the correct configuration you need.

Apologies for this, I'm hoping to push the new version today so everything will be in sync again.

**Comment by webebox** [comment]
@chrissainty  We are waiting impatiently! I asked the team to stop the project until your release.
Thanks

**Comment by chrissainty** [comment]
@webebox This is something I do in my spare time, on top of a full-time job and other community activitiesd, FOR FREE. Please keep this in mind.
