### ISSUE TITLE
Create a proper docs site

### ISSUE THREAD

**Issue by chrissainty** [Blazored/Modal#114]
I was trying to get this done for the v4 release but I just couldn't get it done in time. This is a tracking issue to make sure it actually gets done and doesn't get forgotten again.

Here's what I *think* needs doing:

- [x] Decide on either writing a custom site using Blazor or a static content generator such as Hugo
  - **Decided on DocFX**
- [x] Customise Design/theme
- [x] Setup domain - This will be hosted as *modal.blazored.com*
- Content 
  - [x] Getting Started/Quick Start Guide
  - Usage
    - [x] Passing data to modals
    - [x] Returning data from modals
    - [x] Showing multiple modals
    - [ ] Customisation options (ModalOptions class)

If anyone has any ideas for more content or general input then please get involved 🙂.

**Comment by larsk2009** [comment]
I think this is a good idea. If you need any help let me know.

**Comment by chrissainty** [comment]
Thanks @larsk2009, could probably do with a proof read and some feedback before it goes live. I'll let you know when it's ready. I'm mostly there now.

**Comment by SimonCropp** [comment]
if u think docfx is too much work i am happy to do a PR that leverages https://github.com/SimonCropp/MarkdownSnippets

you can see the type of doco it generates here https://github.com/SimonCropp/Verify

**Comment by chrissainty** [comment]
I've got a site up and working. Would be great if people could have a read over it and see if you can spot any issues. Still adding some bits.

https://blazoredmodaldocs.z33.web.core.windows.net/

**Comment by larsk2009** [comment]
Hi @chrissainty. Do you want seperate issues for things, or should I create 1 issue with things I find?

**Comment by chrissainty** [comment]
If you could add things as separate issues that would be great.
