### ISSUE TITLE
[Bug] Nested modals doesn't work correctly

### ISSUE THREAD

**Issue by sylvainonweb** [Blazored/Modal#115]
**Describe the bug**
When the 2nd modal is closed, modal container refreshs its content so parameters of the 1st modal are reset to their original values

**To Reproduce**
1. Open a 1st modal passing some parameters (CustomerId = 1)
2. Change the value of the property (CustomerId = 2)
3. In the 1st modal, open a 2nd one
4. In the 2nd one, click on the OK button (the modal container must refresh its content)
5. The value of the parameters of the 1st popup are reset (CustomerId = 1 and not 2 as expected)

**Expected behavior**
See point 5.

**Screenshots**
![1](https://user-images.githubusercontent.com/37140661/76676497-645c7e00-65c4-11ea-849e-440d49634da8.gif)

**Additional context**
PLease find the files I used to reproduce the matter
[Popup1.razor.txt](https://github.com/Blazored/Modal/files/4332341/Popup1.razor.txt)
[Popup2.razor.txt](https://github.com/Blazored/Modal/files/4332342/Popup2.razor.txt)

**Comment by chrissainty** [comment]
Thanks for reporting this @sylvainonweb. I think I know where the problem is, I'll try and get a fix coded up today.

**Comment by chrissainty** [comment]
This isn't what I thought and doesn't look like a straight forward fix. It seems like changing any state in the modal resets any other value, which is really odd.

I've added a button to your `Popup1` component which updates the title of the modal using the `BlazoredModalInstance.SetTitle` method. If I increment the customerId to 2 and then press the button, the customerId is set back to 1 again. This is a strange one.

**Comment by sylvainonweb** [comment]
In fact, the matter is that the OnParametersSet is called and so reinitialize the property.
Since a long time, I tried to find a workaround and haven't been able to find one.
And unfortunately, I haven't seen a lot of people trying to write a Modal Service in Blazor

**Comment by chrissainty** [comment]
@sylvainonweb I've worked it out, this isn't a bug, it's how you've designed your component. You shouldn't use `Parameter`s to hold state. I found [this issue that explains what's happening here](https://github.com/dotnet/AspNetCore.Docs/issues/17178) really well, so I won't repeat it. 

The TLDR; of it is store component state in private fields not in `Parameter`s.

**Comment by sylvainonweb** [comment]
I would have never thought about this. Great job, you save my,  day and probably more !!!
Can I ask you :
- if you already created a "real" application in Blazor ?
- if yes, did you use a library or did you finally create your own component ?
