### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by sylvainonweb** [Blazored/Modal#116]
Can I ask you :
- if you already created a "real" application in Blazor ?
- if yes, did you use a library or did you finally create your own component ?

**Comment by chrissainty** [comment]
> if you already created a "real" application in Blazor?

Yes, I've created a few now.

> did you use a library or did you finally create your own component?

I'm not really sure what you mean here.

I'm going to close this issue as there isn't anything about this library. But happy to keep chatting.
