### ISSUE TITLE
[Bug] Cancel button on return data form cause null reference

### ISSUE THREAD

**Issue by frankyjin** [Blazored/Modal#118]
**Describe the bug**
Using the Returning Data example, once the modal opens, click on the Cancel button. This causes an object NULL reference error.

**To Reproduce**
1. Go to Returning Data
2. Click on Show Modal
3. Click on Cancel
4. See error in console window

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Comment by larsk2009** [comment]
hi @frankyjin. I have found the problem. The example doesn't properly cancel the modal, instead just calling `Close`. This will close the modal without setting the `ModelResult.Cancelled`, thus the example tries to access the result data which is indeed null. I will make a pull request to fix this.
