### ISSUE TITLE
[Feature Request] Force the closure

### ISSUE THREAD

**Issue by marciusnery** [Blazored/Modal#120]
**Is your feature request related to a problem? Please describe.**
Was hoping to:

Throw up a modal with a spinner and text, i.e. "Submitting"
Do the actual work of sending the data to the server, checking for success or fail, etc.
On success or fail take down the modal programmatically and throw up a toast with the resulting status
It sounds like once the modal is up the modal is out of my hands and I can't interact with it from where I called it from? i.e. I can't force a close from where it was called.

**Describe the solution you'd like**
Some way to force the modal to close.
Example: Modal.Close ()

**Additional context**
Blazor Webassembly with server

**Comment by benhysell** [comment]
Was about to open my own feature request...I think this pretty much covers it.

I tried getting my hands on ` [CascadingParameter] BlazoredModalInstance BlazoredModal { get; set; }` from the place I was submitting the form from, however when I tried to call close I received a null ref exception.

**Comment by larsk2009** [comment]
I also think this should be possible. I have had a quick look at how to implement it. I think the best way is to add a `Close` function to the `IModalService` which accepts either the `GUID` of the modal or the entire `ModalReference` and closes it. It could work in the same way as adding a modal works now, with an `event Action<ModalReference> OnModalInstanceClosed;
` to which the BlazoredModal subscribes and closes the correct BlazoredModalInstance when required. What do you think @chrissainty?

**Comment by chrissainty** [comment]
Agreed, definitely possible. I was thinking about an implementation similar to your suggestion @larsk2009, but using the `ModalReference`. The nicest API to me would be a simple close method:

```
var myModal = ModalService.Show<MyModal>("My Cool Modal");
myModal.Close();
```

We'd have to inject the `IModalService` into the instance object to make this work and then essentially do what you've suggested.

**Comment by larsk2009** [comment]
Yep that is a better approach I think. Wouldn't be too difficult either I think

**Comment by marciusnery** [comment]
@chrissainty Do you have an implementation forecast and release date for this feature?

**Comment by chrissainty** [comment]
@marciusnery No idea, I've been working in my spare time both evenings and weekends for the last two weeks getting the 4.0 release finished and the new docs site. But I'll get to this as soon as I can.

**Comment by larsk2009** [comment]
@chrissainty If you want I can have a look. If you want to do it yourself, no problems either. I don't want to step on you if you want to work on this.

**Comment by chrissainty** [comment]
Hi @larsk2009, it would be great if you could have a look at this. Are you happy with the approach?

**Comment by larsk2009** [comment]
@chrissainty I think so. I can just have a look at the implementation, and if I run into any big issues we can discuss them?

**Comment by larsk2009** [comment]
Just a quick update. It has been very busy at work, but I it is almost done. Just want to do a last check and then I will make a PR in the coming days.

**Comment by benhysell** [comment]
I saw this issue was closed and was excited to try it out!  Then I realized it wasn't in the 4.0.0 release. 
 Can you kick a new build and publish a new NuGet package?

**Comment by chrissainty** [comment]
Hi Benjamin, apologies this hasn't been released. I want to add another PR but I've just not had the chance to do it yet. I'm hoping to get it done and merged this evening. Once that's done I'll get the release out.

**Comment by chrissainty** [comment]
Just pushed the release to NuGet. Should show up in your feed shortly.

**Comment by benhysell** [comment]
Downloaded, installed, worked like a charm!  Thank you so much for the awesome package!

**Comment by marciusnery** [comment]
Thank you very much for this feature. It's working perfectly.
