### ISSUE TITLE
[Bug] Modal does not get added to the DOM

### ISSUE THREAD

**Issue by NBprojekt** [Blazored/Modal#124]
Im using the Blazored Modal together with Telerik and the Modal dont get displayed.  
Does not even appear in the DOM.  _Im using  Blazor Server_

**To Reproduce**
I followed the instructions in the [readme](https://github.com/Blazored/Modal/blob/master/README.md) and I still dont get it running.

Except [step 3](https://github.com/Blazored/Modal#3-add-modal-component) everything is the same.

My _MainLayout.razor_ from [step 3](https://github.com/Blazored/Modal#3-add-modal-component).
```
@inherits LayoutComponentBase

<BlazoredModal />

<TelerikRootComponent>
    <div style="min-height: 100vh;">
        @Body
    </div>
</TelerikRootComponent>
```

This is my Modal: _Test.razor_
```
<div>
    <p>Please click one of the buttons below to close or cancel the modal.</p>

    <button @onclick="Close" class="btn btn-primary">Close</button>
    <button @onclick="Cancel" class="btn btn-secondary">Cancel</button>
</div>

@code {

    [CascadingParameter] BlazoredModalInstance BlazoredModal { get; set; }

    void Close() => BlazoredModal.Close(ModalResult.Ok(true));
    void Cancel() => BlazoredModal.Cancel();
    
    protected override void OnInitialized() {
      Console.WriteLine("Component started");
      base.OnInitialized();
    }
}
```

And thats how I try to open the Modal: 
```
@inject IModalService Modal

// Other code ...
<button @onclick="@(() => Modal.Show<Test>("Test Modal"))" class="btn btn-primary"> 
    Show Test Modal 
</button>
```

**Comment by chrissainty** [comment]
Hi @NBprojekt, I assume you're not even seeing your "Component Started" message in the console? Have you referenced the Blazored Modal CSS file as per the docs as well?

Have you tried running the modal on its own without the Telerik controls? If so, does it work as expected?

**Comment by NBprojekt** [comment]
Thank you for your fast response.

Yes I added the CSS and I tracked it in the dev-console, so it definitely get downloaded.  
Also I don't get the "Component Started" message.

What exactly do you mean "_without the Telerik controls?_"?

The page where I try to open the Modal does not use Telerik components, the only part where i'm not sure if Telerik and this modal are compatible is in the  _MainLayout.razor_.

Additionally when I check my DOM I don't find any entry which could be the modal.

**Comment by chrissainty** [comment]
Could you put together a repro of the issue with the minimum amount of code?

**Comment by NBprojekt** [comment]
Sure I'll, after that i will notify you.

**Comment by NBprojekt** [comment]
I created a [example repository](https://github.com/NBprojekt/blazor-modal) where I use this modal together with telerik for blazor.

....

And it works, even with telerik components in the modal.

So it is a bug on my side and your modal works perfectly. 😄

**Comment by chrissainty** [comment]
I'm glad the modal is working as it should, sorry to hear you have a bug though. Good luck! 🙂
