### ISSUE TITLE
Valid HTML markup in samples

### ISSUE THREAD

**Issue by c0g1t8** [Blazored/Modal#128]
**Describe the bug**
The HTML markup in the samples don't generate _valid_ HTML.  VS2019 16.5.0 flags it in Intellisense.

**To Reproduce**
For example, in _index.razor_
![image](https://user-images.githubusercontent.com/23250332/76986815-6c3b5b80-68ff-11ea-80a8-7716c0713f5b.png)

**Expected behavior**

The first **p** tag should be a **div**.

![image](https://user-images.githubusercontent.com/23250332/76987139-ed92ee00-68ff-11ea-9a6f-21814e9d1e06.png)

**Screenshots**
See above

**Hosting Model (is this issue happening with a certain hosting model?):**
In both server-side and client-side. 

**Additional context**
N?A

**Comment by chrissainty** [comment]
Thanks for raising this @c0g1t8. It was a known hack I did to get some padding to the bottom of the cards. I meant to fix it before I merged but I forgot. 

Happy to take PRs on this one.

**Comment by c0g1t8** [comment]
I can submit PR :)
