### ISSUE TITLE
missing blazored-modal-content in css file

### ISSUE THREAD

**Issue by ScottyBlazor** [Blazored/Modal#131]
Thanks for this great example
in BlazoredModalInstance.razor there is a class used "blazored-modal-content"
but looking in the CSS file it is not there
I gather it is not super important and probably just has some min-sizes etc, but for completeness it should be added

**Comment by chrissainty** [comment]
Hi @ScottyBlazor, I think this is just a legacy class leftover from a previous version and isn't used anymore. 

I'm not sure about the best way forward, we could remove it from the markup but developers may be using now in live apps and that would make it a breaking change. On the other hand, keeping it there doesn't really cause any harm so I'm leaning more towards leaving it alone.

**Comment by ScottyBlazor** [comment]
Thanks for the quick response and clarification
