### ISSUE TITLE
NU5048 'PackageIconUrl'/'iconUrl' element is deprecated

### ISSUE THREAD

**Issue by c0g1t8** [Blazored/Modal#132]
**Describe the bug**
Warning when creating NuGet package
> warning NU5048: The 'PackageIconUrl'/'iconUrl' element is deprecated

@chrissainty - I suspect you are aware of this issue but I didn't see it logged.

**To Reproduce**

Clean build of solution.

**Comment by chrissainty** [comment]
Thanks @c0g1t8, this is fixed as part of #121 which should be merged anytime now. But thanks for raising.
