### ISSUE TITLE
[Feature Request] Generic Component

### ISSUE THREAD

**Issue by brux88** [Blazored/Modal#133]
excellent library, I was wondering if it was possible or is already in the plans, to be able to pass in addition to the title, also the message to be shown, the type of message so that an icon appears next to the title (wanirng, danger, info, etc ..) and the possibility to pass the type of buttons, for example OK, or Yes, No in order to create a generic window, instead of creating a component for each message

**Comment by chrissainty** [comment]
Hey, this isn't something that we currently have but I don't think it's a bad feature to add to the library.

I think we might need this to be fairly strict in terms of API, so we could have something like this:

```csharp

public void ShowModal()
{
    _ = ModalService.ShowConfirm(Title: "My Title", IconClass: "my-icon-class", ConfirmDelegate: Save);
}

public void Save()
{
    // Perform save or whatever you need to do
}
```

**Comment by larsk2009** [comment]
I agree this is nice, 1 or 2 generic ones, like the save modal, alone might cover most use cases for people

**Comment by brux88** [comment]
my idea was simply this i made a generic component:

`     <div class="custom-header bg-primary text-white w-100">
                    @switch (TipoMessaggio)
                    {
                        case ListeGenerali.TipoMessaggio.Info:
                            <span class="fas fa-info-circle header-icon"></span>
                            break;
                        case ListeGenerali.TipoMessaggio.Warning:
                            <span class="fas fa-exclamation-triangle header-icon"></span>
                            break;
                        case ListeGenerali.TipoMessaggio.Error:
                            <span class="fas fa-exclamation-circle header-icon"></span>
                            break;
                        case ListeGenerali.TipoMessaggio.Success:
                            <span class="fas fa-check header-icon"></span>
                            break;
                        case ListeGenerali.TipoMessaggio.Question:
                            <span class="fas fa-question-circle header-icon"></span>
                            break;
                    }
                    @Title
                    <a class="close-button oi oi-x text-white" href="javascript:;" aria-hidden="true" role="button" aria-label="Close popup" @onclick="@(() => PopUpVisible = false)"></a>
            </div>
        </HeaderTemplate>
        <Content>
            <p>
                @Message
            </p>
        </Content>
        <FooterTemplate>
            @switch (TipoPulsanti)
             {
                case ListeGenerali.TipoPulsanti.YesNo:
                    <button class="btn btn-secondary float-left" @onclick="() => Close(false)">@LocApp.No</button>
                    <button class="btn btn-primary float-right" @onclick="() => Close(true)" >@LocApp.Si</button>
                    break;
                case ListeGenerali.TipoPulsanti.Yes:
                    <button class="btn btn-primary" @onclick="() => Close(true)">@LocApp.Si</button>
                    break;
                case ListeGenerali.TipoPulsanti.Cancel:
                    <button class="btn btn-secondary" @onclick="() => Close(false)">@LocApp.Annulla</button>
                    break;
                default:
                    <button class="btn btn-primary" @onclick="() => Close(true)">@LocApp.Ok</button>
                 break;
             }
        </FooterTemplate>
    </DxPopup>


@code {


    [Parameter] public string Title { get; set; }
    [Parameter] public string Message { get; set; }
    [Parameter] public ListeGenerali.TipoMessaggio TipoMessaggio { get; set; }
    [Parameter] public ListeGenerali.TipoPulsanti TipoPulsanti { get; set; }


}
`

if it was possible to pass these parameters, then just create a generic component that will serve 70% of the modals in an app

**Comment by brux88** [comment]
i send a PR

**Comment by zstarkebaumcalico** [comment]
I agree with this approach, I'd rather incorporate components into a modal component instead of showing components modally.

**Comment by chrissainty** [comment]
I've been thinking about this feature request and upon reflection, I'm not sure it's the right way to go. The goal of this library way to provide an easy and highly customisable way of showing models in Blazor apps. Allowing the developer to create any type of component and having Blazored Modal just display it in a modal UI achieves that goal really well.

If we start creating, essentially hard-coded models we then have to add in a load more customisation options. For example in @brux88 PR it is assumed the icons used will be Fontawesome, however, if someone wants to use Material icons then the modal will break as they require a different set of markup to render correctly. Which means we need even more code to allow for different icon sets.

As it stands with the library, as is, it's a simple task for a developer to create a confirmation component with all of the styling in their control without the need for us to change anything. 

Based on the above I'm going to close this issue, I'm happy to continue the discussion if people still feel strongly this is "must have" feature and we can re-open if it makes sense.
