### ISSUE TITLE
I have updated to the latest version and cannot build the project

### ISSUE THREAD

**Issue by win32nipuh** [Blazored/Modal#135]
After the updating to the latest version
```
void ShowModal()
    {
        var parameters = new ModalParameters();
        var options = new ModalOptions() { Style = "blazored-prompt-modal" };//<-- error not Style
        parameters.Add("BucketId", _customerItemInfo.CustomerItem.Id);
        Modal.OnClose += ModalClosed;//<---------------OnClose err
        Modal.Show<UploadForm>("Upload file", parameters);
    }

```

After it I have rolled back to the previous version 3.1.2.

**Comment by chrissainty** [comment]
Hi @win32nipuh, yes this is because v4 brings in breaking changes, we use semver to version the package so any change the the major version denotes a breaking change.

You need to read the either checkout the [readme ](https://github.com/Blazored/Modal/blob/master/README.md) file or checkout the docs site https://modal.blazored.com to see what changes you need to make to your code.

**Comment by win32nipuh** [comment]
> Hi @win32nipuh, yes this is because v4 brings in breaking changes, we use semver to version the package so any change the the major version denotes a breaking change.
> 
> You need to read the either checkout the [readme ](https://github.com/Blazored/Modal/blob/master/README.md) file or checkout the docs site https://modal.blazored.com to see what changes you need to make to your code.

Please check the code example at [readme ](https://github.com/Blazored/Modal/blob/master/README.md) 

```
@page "/"
@inject IModalService Modal

<button @onclick="ShowModal" class="btn btn-primary">View Form</button>

@code {
    async Task ShowModal()
    {
        var formModal = Modal.Show<SignUpForm>("Please SignUp");
        var result = await formModal.Result;

        if (result.Cancelled)
        {
            Console.WriteLine("Modal was cancelled");
        }
        else
        {
            Console.WriteLine(modalResult.Data); //<---- Typo
        }
    }
}
```

**Comment by chrissainty** [comment]
Thanks for spotting that. Would you mind raising a PR with a fix?

**Comment by win32nipuh** [comment]
As for me, it is not so important
