### ISSUE TITLE
[Bug] Modal is shown for a split second then disappears

### ISSUE THREAD

**Issue by mathiasjensenx** [Blazored/Modal#139]
I have just updated to version 4.0. Most of my modals works as expected, but two of them is only shown for a split second and then disappears. From my point of view there is no difference in my code.

Here is my code for the faulty modal;

Modal:
```
<div>Do you want to delete this message?</div>
<br />
<button @onclick="@Delete" class="btn btn-primary">Delete</button>

@code {
    [CascadingParameter] BlazoredModalInstance BlazoredModal { get; set; }

    [Parameter] public int Talkerid { get; set; }
    [Parameter] public int MessageId { get; set; }

    void Delete()
    {
        AppState_Messages.DeleteMessage(MessageId, Talkerid);
        BlazoredModal.Cancel();
    }
}
```

Metod that calls the modal;

```
    private void DeleteMessageClick(int messageId)
    {
        var parameters = new ModalParameters();
        parameters.Add(nameof(DeleteMessageModal.Talkerid), TalkerId);
        parameters.Add(nameof(DeleteMessageModal.MessageId), messageId);

        Modal.Show<DeleteMessageModal>("Delete Message #" + messageId, parameters);
    }
```

Clickable button;

```
<a href="" @onclick="@(e => DeleteMessageClick(item.MessageId))" class="@(item.Confirmed ? " disabled" : "") @(item.MessageFlash.Any(x=> x.FlashStatus == 1) ? "disabled" : "")">
        <div style="float: left;">
                <img alt="Delete message" title="Delete message" src="@(item.Confirmed || item.MessageFlash.Any(x=> x.FlashStatus == 1) ? "images/icons/delete_disabled.svg" : "images/icons/delete_active.svg")" />
        </div>
</a>
```

**Comment by mathiasjensenx** [comment]
Finally figured it out. Needed to remove href="" from the link.

**Comment by yberstad** [comment]
Thank you so much for this, saved me, spend 3 hours on this yesterday....

**Comment by yberstad** [comment]
My issue was actually something else. I had a link within a tab controller. The tab controller had an onclick event doing a navigation to correspond with the current selected tab. When the I clicked the link it propagated up to the tab control, and triggered a navigation to the same page, making the modal disappear. My fix was eventually adding  @onclick:stopPropagation="true", like this:

`<a @onclick="@(() => Modal.Show<Confirm>("Title"))" @onclick:stopPropagation="true">Open modal</a>`
