### ISSUE TITLE
I'm unable to make this work in a Razor Components project

### ISSUE THREAD

**Issue by dharber** [Blazored/Modal#14]
Calling ModalService.Show() doesn't appear to do anything.

This project seems virtually identical to the article https://www.telerik.com/blogs/creating-a-reusable-javascript-free-blazor-modal which I tried to implement in a Razor Components project. If I put all the files directly in the project it worked but if they were in a Razor Component Library the OnInit method of the BlazoredModal page is never called and no event handlers are hooked up.

Am I doing something obviously wrong?

EDIT: I should mention I'm trying to use ASP.NET Core 3 Preview 3 for this. I think that's implied by the Razor Components but I thought I'd mention it just in case.

**Comment by dharber** [comment]
I found the problem. I was adding the @using's to the wrong _ViewImports.cshtml.

**Comment by chrissainty** [comment]
@dharber glad you got it sorted. If you're happy I'll close the issue, feel free to re-open if you have any further problems.
