### ISSUE TITLE
need to remove NavigationManager.LocationChanged event !

### ISSUE THREAD

**Issue by gcaumont** [Blazored/Modal#140]
To make BlazoredModal work in my application In my Blazor App I have to comment the line 

            //NavigationManager.LocationChanged += CancelModals;

in the file BlazoredModal.razor.cs

Otherwise the modal window is immediately canceled ...

**Comment by chrissainty** [comment]
Is your app opening the modal and then immediately navigating to another route?

**Comment by gcaumont** [comment]
Sorry
I found the bug in my application
The buttton to open the modal form was also validating an edit context ...
Thanks for your fast answer
