### ISSUE TITLE
Modal Dialog size

### ISSUE THREAD

**Issue by win32nipuh** [Blazored/Modal#141]
I have a Form to edit data with 3 tabs
1 tab: 5 fields
2 tab: 3 fields
3 tab: 6 fields

Call it as Modal.
```
   async Task EditCustomerModal()
    {
        var parameters = new ModalParameters();
        parameters.Add("CustomerId", CustomerItem.Id.ToString());
        parameters.Add("AddOrEdit", false);
        parameters.Add("ReturnUrl", @"customers");
        var formModal = Modal.Show<EditCustomer>("Edit", parameters);
        var result = await formModal.Result;
        if (!result.Cancelled)
        {
            await OnRefreshMainGrid.InvokeAsync(0);
        }
    }

```

But when  I switch between tabs the dialog changes size.
Is it possible somehow to fix the dialog size?

**Comment by chrissainty** [comment]
Hi @win32nipuh, the modal doesn't have a size it just expands or contracts to fit whatever is being rendered inside.

You just need to set your `EditCustomer` component to the correct size.

**Comment by win32nipuh** [comment]
Thanks you, btw, I understand that is not question to this topic but how can I set correct size for the razor component? As you wrote: if I call it as modal it will be resized and "jumps" when I click tabs. I see only one way: to set the same count of fields on each tab but it is not possible in a common case.

**Comment by chrissainty** [comment]
No problem, you set the size using CSS. So let's assume your `EditCustomer` component has a main container element, like this:

```html
<div>
    <!-- ... your modals content ... -->
</div>
```

You can define a CSS class which has a width setting, something like this:

```css
.edit-customer {
    width: 250px;
}
```

Then you apply that to your container `div`:

```html
<div class="edit-customer">
    <!-- ... your modals content ... -->
</div>
```

**Comment by win32nipuh** [comment]
Thank you Chris, I see now.
