### ISSUE TITLE
[Bug] DisableBackgroundCancel doesn't seem to work in version 2.3.0

### ISSUE THREAD

**Issue by kevinjpetersen** [Blazored/Modal#142]
**Describe the bug**
Setting DisableBackgroundCancel to True doesn't seem to have any effect. I can still close the Modal by pressing in the background.

I'm using version 2.3.0

**To Reproduce**
My code to open:
`Modal.Show("My App", typeof(MyCustomComponent), parameters, new ModalOptions() { DisableBackgroundCancel = true });`

It's worth noting that I'm using my own BlazorStandardModal from whenever that was a thing in the Repository.

BlazorStandardModal.razor
```
@inherits Blazored.Modal.BlazoredModalBase

<div class="blazored-modal-container @(IsVisible ? "blazored-modal-active" : string.Empty)">

    <div class="blazored-modal-overlay" @onclick="@(() => ModalService.Cancel())"></div>

    <div class="blazored-modal">
        <div class="blazored-modal-header">
            <img src="/assets/img/logo.png" height="60" />
            <h3 class="blazored-modal-title">@Title</h3>
            <button type="button" class="blazored-modal-close" @onclick="@(() => ModalService.Cancel())">
                <span>&times;</span>
            </button>
        </div>
        <div class="blazored-modal-content">
            <CascadingValue Value="@Parameters">
                @Content
            </CascadingValue>
        </div>
    </div>
</div>
```

**Expected behavior**
Expectation would be that it doesn't close the modal when clicking in the background.

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Comment by kevinjpetersen** [comment]
So it seems that it's tied to the line
`<div class="blazored-modal-overlay" @onclick="@(() => ModalService.Cancel())"></div>`

I tried setting an if-statement so it's like this
`<div class="blazored-modal-overlay" @onclick="@(() => { if (DisableBackgroundCancel) ModalService.Cancel(); })"></div>`

But now you can never close it by clicking in the background. It's almost like DisableBackgroundCancel is always True by Default, or it's a global variable being set in the Modal.Show but never set back again.

**Comment by chrissainty** [comment]
Hi Kevin,

I think, looking at your code, you still have elements from before `DisableBackgroundCancel` was added. Looking at specifically at this line in your `BlazorStandardModal`:

```razor
<div class="blazored-modal-overlay" @onclick="@(() => ModalService.Cancel())"></div>
```

We haven't done that for a long time. We now call a method on the modal instance which checks the value of `DisableBackgroundCancel`, if it's true we just `return` from that method, otherwise, we run the cancel logic.

I think that is where your problem lies. But I would really suggest getting yourself up to the latest version as soon as you can as there have been a lot of improvements.

**Comment by kevinjpetersen** [comment]
@chrissainty That makes alot of sense. I would love to get to the latest version, but may I suggest adding an extra overload to Modal.Show then? Otherwise I have to go through manually 150 places in my code and change stuff, and test it all over again.

The overload I'm talking about is:
`Modal.Show("My App", typeof(MyCustomComponent), parameters, new ModalOptions() { DisableBackgroundCancel = true });`

So that's:
- Title,
- Component/Type
- Parameters
- Modal Options

Could this possibly become a thing? :)

Thanks for taking the time to respond!

**Comment by chrissainty** [comment]
We do have that overload, it’s just the order is `Show(ComponentType, Title, Parameters, Options)`. Unfortunately we wouldn’t want to just change the order again. So we can’t help with this I’m afraid. 

I’m not sure if you’ve seen the latest changes but there are further breaks to the old API as well. We no longer have the `Closed` event and we have moved to modal instances which you can await the result of which is a much nicer programming model to work with. So there are probably more changes you would have to make. If there is no benefit to your app, then I understand not wanting to change anything.

**Comment by kevinjpetersen** [comment]
Ahh okay that makes sense then.

We only really use Modals as Confirmation boxes for stuff like "Are you sure you wanna do this?" type of thing, and in the 150 places we're using it there is no issues.

Funny enough, I solved the original issue just now by using the following code:
`<div class="blazored-modal-overlay" @onclick="@(() => { if (!ComponentDisableBackgroundCancel) ModalService.Cancel(); })"></div>`
Where the difference is that using ComponentDisableBackgroundCancel aswell as testing with False, apparently works like if DisableBackgroundCancel was set to true in ModalOptions.

A bit hacky, but I guess it works :D

I'll put it on my todo to actually upgrade to the latest, but that's alot of work so that won't be happening right now then :D But thanks for helping me out! I appreciate it!
