### ISSUE TITLE
.Close() & .Cancel() Methods no longer available in 4.0.0

### ISSUE THREAD

**Issue by ShaunCurtis** [Blazored/Modal#144]
Hi
I have a project running 3.1.2 and have implemented to Close() and Cancel() methods in a component.

I've just added the same component to a new project which has version 4.0.0 installed. These methods appear to no longer be available.

Am I missing something or was this intentional?

**Comment by larsk2009** [comment]
Hi @ShaunCurtis. 

A lot of stuff has changed with version 4.0.0, including breaking changes. Specifically the `close()` and `cancel`, they were removed from the interface as you found out. The modals are not closed using the IModalService anymore. You can read either the readme file or checkout the docs site https://modal.blazored.com to see what changes you need to make to your code for it to work. If you have any questions after that let us know!

**Comment by ShaunCurtis** [comment]
No problem - thanks for replying.  Will go through the documentation.
