### ISSUE TITLE
[Feature Request] Prerelease nuget stream

### ISSUE THREAD

**Issue by larsk2009** [Blazored/Modal#145]
**Is your feature request related to a problem? Please describe.**
I see sometimes people are waiting for new features to be released. I understand this as you are also busy with other things than just working on this repo.

**Describe the solution you'd like**
I was thinking, maybe we can make a custom Nuget feed that hosts a pre-release package for either each commit or for each PR that is merged to master.

**Describe alternatives you've considered**
The alternative is what we have now I think, just releasing a new package every once in a while.

**Additional context**
I am pretty sure you can make a custom Nuget feed in Azure pipelines. I have also used some tools that automatically set version numbers etc based on commit hash and thus can create Nuget packages automatically.

This is only an idea and to see if you like the idea. I haven't thought out all the specifics.

I have no problem waiting for you to release at all so this if you don't like this no problems at all! Just something that popped into my mind and wanted to see what your thoughts on it were.

**Comment by chrissainty** [comment]
Sort of like a nightly build? 

I'm not apposed to the idea, it might be a good chance to try out the new GitHub package management stuff.

**Comment by larsk2009** [comment]
Yeah like nightly indeed. If it can be hosted trough GitHub's packages that would be even better I think!

**Comment by chrissainty** [comment]
With the switch over to GitHub Actions, I've set things up so anything merged into main will be packaged and released to the Blazored GitHub Packages feed (https://github.com/orgs/Blazored/packages). So developers can now get any preview stuff using the packages on GitHub and full releases will be on NuGet as usual.
