### ISSUE TITLE
[Feature Request] Allow CSS customization also for blazored-modal-wrapper and blazored-modal-container

### ISSUE THREAD

**Issue by cyberdarius** [Blazored/Modal#146]
**Is your feature request related to a problem? Please describe.**
I normally use default css with success.
But my needs for some modal are different:

Problem 1 (MOST IMPORTANT):
I can't set a fixed width to "blazored-modal-wrapper" per custom instance (used only in 2 places, the others are component defaults)

![image](https://user-images.githubusercontent.com/51365598/78585356-fe1cf100-7839-11ea-8f77-283a113c45c0.png)

Problem 2:
@Position in "blazored-modal-container" in the last update became managed, and i lost some my custom position css (like "top-center" with i added "overflow-y" to allow scrollable content on mobile view)

Can you consider adding custom @Class support for "blazored-modal-wrapper" and re-adding custom string class support for "blazored-modal-container" ?

Sorry, but i'm a css newbie ... i tried to set my component width without success

Thanks Chris for this awesome component !!!

**Comment by chrissainty** [comment]
Hi @cyberdarius,

**Problem 1**
The modal doesn't have any width settings, the width of the modal is determined by the width of whatever component you display in it. Just set a width on the component being displayed and the modal will accommodate it.

**Problem 2**
I'm guessing you didn't use our preset styling for position before? You created your own? If that's the case I can see why the change we made would break things. I've added the different classes we apply below, you can add those to your CSS and set whatever custom values you wish.

```css
.blazored-modal-topleft .blazored-modal-wrapper { }
.blazored-modal-topright .blazored-modal-wrapper { }
.blazored-modal-bottomleft .blazored-modal-wrapper { }
.blazored-modal-bottomright .blazored-modal-wrapper { }
```

That will get you going again and we can look at adding a custom layout class option.

**Comment by chrissainty** [comment]
Based on the above comments, we need to add an option to allow developers to specify a custom layout class. 

Currently, the class is applied internally based on an enum value. The way I see this working is adding an additional option to the enum called `Custom`. If this is selected the developer would need to provide a class name for us to apply, this would mean adding a new property to `ModalOptions`. Put together it should look something like this.

```
var options = new ModalOptions 
{ 
    Position = ModalPosition.Custom, 
    PositionCustomClass="my-position-class"
};

_ = Modal.Show<Confirm>("My Modal", options);
```

Internally, if `ModalPosition` is set to `Custom` and no value is defined for `PostionCustomClass` we should throw an exception. If the value is set then we should apply the developers class and not apply our own.

```csharp
private string SetPosition()
{
    // other code omitted

    switch (position)
    {
        case ModalPosition.Center:
            return "blazored-modal-center";
        case ModalPosition.TopLeft:
            return "blazored-modal-topleft";
        case ModalPosition.TopRight:
            return "blazored-modal-topright";
        case ModalPosition.BottomLeft:
            return "blazored-modal-bottomleft";
        case ModalPosition.BottomRight:
            return "blazored-modal-bottomright";
        case ModalPosition.Custom:
            if (string.IsNullOrWhiteSpace(Options.PositionCustomClass)
                throw new ArgumentNullException("Position set to Custom without a PositionCustomClass set.");
            return Options.PositionCustomClass;
        default:
            return "blazored-modal-center";
    }
}
```

**Comment by cyberdarius** [comment]
> Hi @cyberdarius,
> 
> **Problem 1**
> The modal doesn't have any width settings, the width of the modal is determined by the width of whatever component you display in it. Just set a width on the component being displayed and the modal will accommodate it.
> 
> **Problem 2**
> I'm guessing you didn't use our preset styling for position before? You created your own? If that's the case I can see why the change we made would break things. I've added the different classes we apply below, you can add those to your CSS and set whatever custom values you wish.
> 
> ```css
> .blazored-modal-topleft .blazored-modal-wrapper { }
> .blazored-modal-topright .blazored-modal-wrapper { }
> .blazored-modal-bottomleft .blazored-modal-wrapper { }
> .blazored-modal-bottomright .blazored-modal-wrapper { }
> ```
> 
> That will get you going again and we can look at adding a custom layout class option.

Problem 1:
For some components didn't work for me (my fault, i'm a newbie, i'll try to deep my css knoledge).
I resolved overriding the css directly in the component:
```
@inherits MyBaseComponentModel

<style>
    @@media only screen and (max-width: 900px) {
        .blazored-modal-wrapper {
            width: 75%;
        }
    }
    @@media only screen and (min-width: 901px) {
        .blazored-modal-wrapper {
            /*max-width: 800px;*/
            width: 30%;
        }
    }
</style>

[ComponentCode]
```
Problem 2:
Yes, used my custom preset styling class for sliding (overflow-y) and mobile view with big modals with many fields that go over the height of the screen. (some sort of master/detail approach)

Temp Solution: I've overridden and unused preset.

**Comment by cyberdarius** [comment]
> Based on the above comments, we need to add an option to allow developers to specify a custom layout class.
> 
> Currently, the class is applied internally based on an enum value. The way I see this working is adding an additional option to the enum called `Custom`. If this is selected the developer would need to provide a class name for us to apply, this would mean adding a new property to `ModalOptions`. Put together it should look something like this.
> 
> ```
> var options = new ModalOptions 
> { 
>     Position = ModalPosition.Custom, 
>     PositionCustomClass="my-position-class"
> };
> 
> _ = Modal.Show<Confirm>("My Modal", options);
> ```
> 
> Internally, if `ModalPosition` is set to `Custom` and no value is defined for `PostionCustomClass` we should throw an exception. If the value is set then we should apply the developers class and not apply our own.
> 
> ```cs
> private string SetPosition()
> {
>     // other code omitted
> 
>     switch (position)
>     {
>         case ModalPosition.Center:
>             return "blazored-modal-center";
>         case ModalPosition.TopLeft:
>             return "blazored-modal-topleft";
>         case ModalPosition.TopRight:
>             return "blazored-modal-topright";
>         case ModalPosition.BottomLeft:
>             return "blazored-modal-bottomleft";
>         case ModalPosition.BottomRight:
>             return "blazored-modal-bottomright";
>         case ModalPosition.Custom:
>             if (string.IsNullOrWhiteSpace(Options.PositionCustomClass)
>                 throw new ArgumentNullException("Position set to Custom without a PositionCustomClass set.");
>             return Options.PositionCustomClass;
>         default:
>             return "blazored-modal-center";
>     }
> }
> ```

Yes, it will be perfect !

Thank you Chris, this component is VITAL for blazor development !

**Comment by pablopioli** [comment]
Seeing this as up for grabs. Need any help with this? Seems you can already figured out, I can make a pull request of it.

Watching the tests I guess another one can be made for this feature.

**Comment by chrissainty** [comment]
@pablopioli Yes, more than happy for you to take this one. Thanks for the help.

**Comment by pablopioli** [comment]
OK, I'll take it. In a couple of days should be done.

**Comment by pablopioli** [comment]
@chrissainty 
I'm working on this and I would like to know how you would like to proceed. To implement the custom position you need to write code like this

```
   .custom-position-class .blazored-modal-wrapper {
       position: absolute;
       top: 0px;
       left: 100px;
  }
```

You need to override the wrapper or the overlay has a wrong position. It's something you would like the user to do? Or you would like to hide the internals of this?

**Comment by chrissainty** [comment]
It would be inline with how we do it now but I'm open to suggestions if you have a suggestion. One thing to consider is that implementing this feature the way I suggested above wouldn't cause any breaking changes.

**Comment by pablopioli** [comment]
So there are 3 options:

1. Make a breaking change modifying the wrapper
2. Make the user to remember overriding .blazored-modal-wrapper
3. Make some ugly changes in BlazoredModalInstance, so the custom class targets the wrapper. You can see what it involves in
https://github.com/pablopioli/Modal/commit/805bdfc7bf851bc301231e3bcc82c769cc9fdb61

It's up to which you prefer regarding the direction you want for the library.

**Comment by chrissainty** [comment]
So looking at the current code now, I'm not sure why I put the position class here:

```razor
<div class="blazored-modal-container @Position">
```

When it could have easily gone here:

```razor
<div class="blazored-modal-wrapper @Position">
```

I think we need to move `@Position` to be alongside `blazored-modal-wrapper` as per the example above.

**Comment by pablopioli** [comment]
I agree, it will make the code simpler, even in other parts. Will make those changes and send them back to you.

The majority of people that restyled the component should be fine, also.

**Comment by pablopioli** [comment]
Sorry for the delay, life and those things. The pull request is ready.

> 
> 
> So looking at the current code now, I'm not sure why I put the position class here:
> 
> ```
> <div class="blazored-modal-container @Position">
> ```
> 
> When it could have easily gone here:
> 
> ```
> <div class="blazored-modal-wrapper @Position">
> ```
> 
> I think we need to move `@Position` to be alongside `blazored-modal-wrapper` as per the example above.

I realized why you made this originally. You need to target the container to center the modal, otherwise you don´t have the viewport width. Other positions can go in the wrapper.

So what I did? It targeted the container for the center position and the wrapper for the other positions.
