### ISSUE TITLE
[Bug] The height of the modal box exceeds the height of the screen without scrolling

### ISSUE THREAD

**Issue by my6521** [Blazored/Modal#148]

**Comment by chrissainty** [comment]
The modal doesn't have a set height or width. It just expands to fit whatever is put in it. You need to set the height and width of whatever you are displaying in the modal.

**Comment by my6521** [comment]
I have set the height and width, the scroll bar appears on the far right to scroll, but the modal window cannot scroll





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chris Sainty"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 凌晨0:05
收件人:&nbsp;"Blazored/Modal"<Modal@noreply.github.com&gt;;
抄送:&nbsp;"Wwb"<22379099@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Blazored/Modal] [Bug] The height of the modal box exceeds the height of the screen without scrolling (#148)





 
The modal doesn't have a set height or width. It just expands to fit whatever is put in it. You need to set the height and width of whatever you are displaying in the modal.

**Comment by chrissainty** [comment]
Here is the link to the same question https://github.com/Blazored/Modal/issues/141. Maybe there is something there to help. But this is all CSS under your control, we don't set anything special on the default styles.
