### ISSUE TITLE
it seems close event is not working!

### ISSUE THREAD

**Issue by Behnam-Emamian** [Blazored/Modal#15]
Hi

this is my code
`void ShowModal()
    {
        ModalService.OnClose += ModalClosed;
        ModalService.Show("Add Database", typeof(AddDatabase));
    }

    void ModalClosed()
    {
        Console.WriteLine("Modal has closed");
        //await GetDatabases();
        ModalService.OnClose -= ModalClosed;
    }`

I cannot see message in console

**Comment by chrissainty** [comment]
Hi @Behnam-Emamian, are you getting any error in the console?

**Comment by Behnam-Emamian** [comment]
nothing :-\

**Comment by Behnam-Emamian** [comment]
when I have change to call from
<button class="btn btn-primary" onclick="@ShowDatabaseModal">Add Database</button>
to
<button class="btn btn-primary" onclick="@(() => ShowDatabaseModal())">Add Database</button>

it is starting to work

**Comment by Behnam-Emamian** [comment]
oh no!

it is because I have closed the modal by code
`ModalService.Close();`

**Comment by chrissainty** [comment]
It looks like you've got everything working so I'm going to go ahead and close this issue. Please re-open it if you have any further problems.

**Comment by chewabledrapery** [comment]
Hi,

I'm having this issue myself now in core 3.1 preview.

Pretty sure i've checked and double-checked my code and it looks correct, any insight appreciated.

Thanks.

**Comment by chrissainty** [comment]
@chewabledrapery Can you provide some code or some other context please.
