### ISSUE TITLE
[Feature Request] Modify Z-Index of Modal Components

### ISSUE THREAD

**Issue by richward1** [Blazored/Modal#152]
**Is your feature request related to a problem? Please describe.**
I can see the `z-index` of the modal container, wrapper, and overlay are set to ~100. My project contains various components that are z-indexed a lot higher than that, and the modal won't show.

**Describe the solution you'd like**
A bit more flexibility in customising certain parts of the modal, like the z-indexing.

**Describe alternatives you've considered**
For the life of me, I've tried targeting `blazor-modal-container` etc through CSS, even using `!important` and messing with the order in which the CSS is loaded, but I can't figure out why it won't let me override these values.

**Comment by chrissainty** [comment]
Hi @richward1, adding CSS overrides is the way to adjust this setting. We won’t expose individual CSS styles through component parameters. 

I would suggest putting a repro together showing what you’ve done and we can take a look and try and spot what’s wrong.

**Comment by richward1** [comment]
Nevermind - I just found some weird character in my CSS that was breaking it! 

I didn't think it was actually an issue with your code - keep up the good work :)

**Comment by chrissainty** [comment]
Glad you got it sorted :)
