### ISSUE TITLE
Focus trap

### ISSUE THREAD

**Issue by StevenRasmussen** [Blazored/Modal#153]
Do you have any plans to implement a focus trap to prevent users from using the keyboard to tab to elements outside of a dialog?

**Comment by chrissainty** [comment]
It has been something that has come up so far. But that doesn't mean it wouldn't be worth look at. Is this a feature you would like to see? If so do you have any ideas about how you would implement it?

**Comment by StevenRasmussen** [comment]
This is definitely something I would like to see... and I think as more people start to use the package this will become something that more are looking for, especially to conform with accessibility requirements.  Unfortunately I don't have any really good input as far as the best way to implement it, especially without introducing JavaScript (and I know that one of the declarations of this library is that it's "JavaScript free").  One of the reasons I was looking at this library was in hopes that this problem was already solved :).

Here are a few solutions that I've come across while researching:
- [allyjs.io](https://allyjs.io/tutorials/accessible-dialog.html#javascript-user-interaction)
- [css way of solving this (partially)](https://css-tricks.com/a-css-approach-to-trap-focus-inside-of-an-element/)
- [w3.org - the spec I believe](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html)
- [A11y Dialog](https://github.com/edenspiekermann/a11y-dialog/blob/master/README.md)

I appreciate your consideration of this. Thanks!

**Comment by chrissainty** [comment]
Thanks for the info @StevenRasmussen. We can take a look and see what we can do. Also, I'm not stubborn about keeping the library JS free, it's just so happened that we have been able to achieve everything so far without the use of JS, but I don't want to limit the usefulness of the library just to keep that claim.

**Comment by sblakemore** [comment]
Would love to see this happen also.

**Comment by chrissainty** [comment]
SO I've spent about 6-7 hours on this so far and I've not managed to get any closer to getting a working solution. I would love to add this feature, I think it's really important but I just can't spend any more time on it at the moment, I just have too many things to do. 

I'll come back to this when I have more capacity unless someone with more experience of the JS needed steps up to help. For now, this issue is on hold.
