### ISSUE TITLE
[Bug] Modal does not show

### ISSUE THREAD

**Issue by nssidhu** [Blazored/Modal#154]
I am using Blazor Serverside.
Objective of the code is to display wait message

In button clicked i the following code

```
 Blazored.Modal.ModalReference modalRef = null;
 var myoptions = new Blazored.Modal.ModalOptions()
                {
                    // Class = "blazored-modal-movies",
                    HideCloseButton = false,
                    DisableBackgroundCancel = true,
                    Position = Blazored.Modal.ModalPosition.Center // "blazored-modal-bottomleft" // blazored-modal-center, blazored-modal-topleft, blazored-modal-topright, blazored-modal-bottomleft and blazored-modal-bottomright.
                };


                var myparameters = new Blazored.Modal.ModalParameters();
                  myparameters.Add("ModalMessage", "Please wiaiting...........");


                modalRef = modal.Show<mySite.Pages.ModalDialog>("Processing..", myparameters, myoptions);
```
In between this is my code that takes a while

 modalRef.Close();

for me the Modal dialog does never shows up. the only other thing is that my button click is not async.

**Comment by chrissainty** [comment]
Hi @nssidhu, could you please provide a minimal repro of the issue so we can see what is happening?

**Comment by pablopioli** [comment]
Don't know if it is related, but I found a case in which the modal don't appear.
```
   <a @onclick="ShowModal">This works</a>
   <a href="#" @onclick="ShowModal">Don't work</a>
   @code {
       void ShowModal() => Modal.Show<Confirm>("Welcome to Blazored Modal");
   }
```
I added the href to keep Bootstrap styling and lost the modal. What puzzled me was that the ShowModal method was called.

Still haven't look at the source code to see what could be happening.

**Comment by chrissainty** [comment]
@pablopioli I would suggest not writing that kind of code. In that scenario, I would suggest you use a button instead and there are classes in Bootstrap which can style a button like a link if that's what you need it to look like.

**Comment by pablopioli** [comment]
Sure, I just ended overriding Bootstrap styles to get the effect I wanted.

**Comment by nssidhu** [comment]
Yes, i am showing modal via method call, the way i got it working is adding Task.Dely(500) right after ShowModal() method call

**Comment by pablopioli** [comment]
You are not triggering the render phase (StateHasChanged), so when you insert a delay Blazor sees it has free time and rerenders the screen.

The way you invoke the method call is not triggering the automatic refresh.

**Comment by chrissainty** [comment]
@nssidhu I don't think there is going to be anything we can do unless you can provide us a working reproduction of the problem. Will you be able to do that?

**Comment by chrissainty** [comment]
As I've not heard back for a few days I'm going to close this issue. Please reopen if you can provide us with a working repro of the issue.

**Comment by NatanBagrov** [comment]
Hi, I can also confirm that once migrated from the latest 3.x.x to 4.1.0 (and fixed the breaking-changed) - the Modal don't show up (however, is initialized).
Maybe there are some additional files that did change but were not committed by mistake?
I can try to provide a repro, in case needed.

Also, just downloaded the repo, and the Modal looks like this:
![image](https://user-images.githubusercontent.com/20153650/81471062-2744ee80-91f7-11ea-876f-fab8032486b8.png)
(MacOS 10.15.4 (19E287), Chrome Version 81.0.4044.138)

**Comment by NatanBagrov** [comment]
> Hi @chrissainty , I can also confirm that once migrated from the latest 3.x.x to 4.1.0 (and fixed the breaking-changes) - the Modal don't show up (however, is initialized).
> Maybe there are some additional files that did change but were not committed by mistake?
> I can try to provide a repro, in case needed.
> 
> Also, just downloaded the repo, and the Modal looks like this:
> ![image](https://user-images.githubusercontent.com/20153650/81471062-2744ee80-91f7-11ea-876f-fab8032486b8.png)
> (MacOS 10.15.4 (19E287), Chrome Version 81.0.4044.138, same in Safari as well)

With regards to the original issue, looks like the current `.css` override I had breaks it. I will try to locate the problematic line.

**Comment by NatanBagrov** [comment]
> > Hi @chrissainty , I can also confirm that once migrated from the latest 3.x.x to 4.1.0 (and fixed the breaking-changes) - the Modal don't show up (however, is initialized).
> > Maybe there are some additional files that did change but were not committed by mistake?
> > I can try to provide a repro, in case needed.
> > Also, just downloaded the repo, and the Modal looks like this:
> > ![image](https://user-images.githubusercontent.com/20153650/81471062-2744ee80-91f7-11ea-876f-fab8032486b8.png)
> > (MacOS 10.15.4 (19E287), Chrome Version 81.0.4044.138, same in Safari as well)
> 
> With regards to the original issue, looks like the current `.css` override I had breaks it. I will try to locate the problematic line.

Ok, so this was the relevant `.css` snippet that worked for 3.x.x, and was overriden:
```
.blazored-modal-container {
    display: none; <-- bug here
    ...
}
```

And the fixed:
```
.blazored-modal-container {
    display: flex;
    ...
}
```

**Comment by chrissainty** [comment]
@NatanBagrov Sorry I’m confused, are you saying there is a bug in our CSS or yours?

**Comment by NatanBagrov** [comment]
Mine. Just for others to note, that this might be the case.

**Comment by chrissainty** [comment]
Got ya, thanks for the clarification 👍

**Comment by NatanBagrov** [comment]
> Got ya, thanks for the clarification 👍

No problem :)
Note however, that the screen-shot has to deal with the downloaded .zip from this repo.

**Comment by chrissainty** [comment]
@NatanBagrov I think you may have an issue with cached CSS in your screenshot. I edit the modal repo on 4 different machines and there is no issue with how things display.

**Comment by NatanBagrov** [comment]
@chrissainty, I've invalidated cache, and also tried both Chrome and Safari, both regular and incognito - still same result. I was running Blazor Server. Anyway, maybe that's just a glitch in my machine...

**Comment by chrissainty** [comment]
That's interesting, thanks for letting me know - I've done the same my end and everything still displays as expected. I can't really do anything if I can't replicate the problem though :( We'll just have to see if it comes up for anyone else and deal with it then.

**Comment by OverlordEx3** [comment]
Hi, I don't know if this may help but i experienced the same issue.
In my case, I solved it by changing in _hosts.cshtml the css link:
``` html
<link href="~/css/blazored-modal.css" rel="stylesheet" />
```
to:
``` html
<link href="_content/Blazored.Modal/blazored-modal.css" rel="stylesheet" />
```
The first snippet is what i had. I don't know when or who wrote it, since i was assigned to this project recently, but changing that made my modals appear.

**Comment by kiwiingenuity** [comment]
For the past two days I have been strugling with a very similar problem.
I upgraded my WASM app to 3.2.0 and at the same time updated the Blazored Modal off GitHub.
From that moment on I could not get my Modal windows to appear.
I started from the basics and created a new WASM app, added Blazord Modal and it worked just fine.  So there was something wrong with my code???
After reading this post I decided I would.
(a) Copy blazored-modal.css into my application.
(b) Change the link in index.html to the css file.

And now it all works....   I suspect my issue was reading the wrong css file???
I haven't given this much thought up to now, but where does href="_content/Blazored.Typeahead...." point to anyway?

**Comment by chrissainty** [comment]
@OverlordEx3 There used to be an issue with referencing CSS from NuGet packages, a long time ago. The first code sample you've added seems to be from that time, as developers had to copy the CSS into their projects. The second example is how things work now and have done for a while.

**Comment by chrissainty** [comment]
@kiwiingenuity You shouldn't copy the CSS into your app as if/when we make any changes you will not receive them and it could possibly break your app or at least cause strange errors. 

Blazor allows developers to use static assets from NuGet packages by exposing them via the `_content` location. You can think of this as a sort of virtual folder in your published app. You can reference assets from any third party library using a naming convention of `_content/[package name]/[asset name]`. So for Blazored Models CSS it is `_content/Blazored.Model/blazored-model.css`.
