### ISSUE TITLE
Providing ModalResult.Ok(value) does not close modal

### ISSUE THREAD

**Issue by dbaule** [Blazored/Modal#156]
When I'm closing my modal with the following method the Transit value is provided to the awaiting method but the modal window does stay open, only when I call the HandleSubmit() method again does the modal close.
BlazoredModal is a CascadingParameter of type BlazoredModalInstance.

`public void HandleSubmit()
        {
            BlazoredModal.Close(ModalResult.Ok(Transit));
        }`

My awaiting method looks like this:
`
public async void AddRestApiTransit()
        {
            var restApiModal = ShowEditTransitModal(transit);
            var result = await restApiModal.Result;

            if (result.Cancelled) return;

            SaveTransitToArea(result);
        }
`

Calling BlazoredModal.Cancel() or calling BlazoredModal.Close() does close the modal. 
But when i provide a ModalResult within the Close() method, it does not close.
Anyone here has the same issue or a hint on how to prevent this?
If you need further information I'm happy to provide it.

**Comment by larsk2009** [comment]
I don't know if anyone else has had this issue, but if you provide a minimal repro of this issue then it will be easier to help.

**Comment by dbaule** [comment]
Alright, I'm dumb... sorry.. i had a loop in my code that reopened the modal after i closed on the first time... closing this issue now, sorry.. but thanks for your quick reply
