### ISSUE TITLE
[Bug] cannot dismiss the dialog

### ISSUE THREAD

**Issue by nssidhu** [Blazored/Modal#158]
I am displaying the dialog
  var modalRef= modalDialogService.Show<CustomDialog>("This is my title");
 then trying to close using
     modalRef.Close();
but the dialog stay open.
I have tried StateHaschanged etc but nothing seem to work

Hosting Model used is
 - Blazor WebAssembly

**Comment by chrissainty** [comment]
Can you provide your code so we can see exactly what you've done? A full repro of the issue would be preferred.

**Comment by digitalsigi** [comment]
Hi,
thx for this piece of Software, helped me already to make the GUI very user friendly.
Now it seems that I have same issue.
My code looks like this:
```
       protected async Task DeleteClicked(Guid Id)
        {
            var titel = $"Anforderung löschen";
            var modalParms = new ModalParameters();
            modalParms.Add(nameof(AnforderungDeleteConfirmModalPageCode.Title), $"Anforderung vom {DetailVm.AngefordertPerString}");
            modalParms.Add(nameof(AnforderungDeleteConfirmModalPageCode.Message), $"Wollen Sie die Anforderung {DetailVm.Id} von {DetailVm.AbgerufenVonName} wirklich löschen?");
            var modalOptions = new ModalOptions() { HideCloseButton = true };
            var formModal = Modal.Show<AnforderungDeleteConfirmModalPage>(titel, parameters: modalParms, options: modalOptions);
            var modalResult = await formModal.Result;
            if (modalResult.Cancelled)
            {
                Logger.LogInformation("Delete cancelled for {DetailVm}", DetailVm);
                return;
            }

            StateHasChanged();
            SetSpinnerVisibility(true);
            var response = await Mediator.Send(new DeleteAnforderungCommand() { Id = DetailVm.Id });
            Result = response.Result;
            if (Result.Succeeded)
            {
                IsDeleted = true;
                //DetailVm = null;
            }
            SetSpinnerVisibility(false);
            StateHasChanged();

        }
```
I observed, that changes to the UI became effectiv after return from the method.
SetSpinnerVisibility sets a binary value to show a spinning wheel from awesome fonts.
IsDeleted hides parts of the blazor page.
I tried to include the spinner in the modal code, and switch on/off with binary field. But does not work either. The Modal window is attached. No idea whether it occures in an isolated environment.
[ModalPage.zip](https://github.com/Blazored/Modal/files/4722830/ModalPage.zip)

**Comment by chrissainty** [comment]
@nssidhu @digitalsigi I've been trying to replicate this issue, but I can't. If you could provide a repro of the issue that I can use and see the problem rather than just the odd file, I might be able to help. But as of right now I would have to say it is probably a local issue to do with something else in your applications.

**Comment by digitalsigi** [comment]
@chrissainty OK, accepted. I can't post the whole project. But as this functionality it is vital to me, I'll finish the current sprint and will then try to recreate issue in isolated environment.

**Comment by chrissainty** [comment]
Thanks @digitalsigi, hopefully then we can get to the bottom of it.

**Comment by chrissainty** [comment]
As there has been no further communication I'm going to assume this turned out to be some kind of local issue and close this issue.

**Comment by digitalsigi** [comment]
OK, understand that. Unfortnuately I can't not follow up on this because of other priorities. However, its not solved and I'll look into it asap.

**Comment by larryfura** [comment]
@digitalsigi I am just getting started with this modal component and just run in to the same issue as you.

When I would try to close the modal the screen it would blink and the grayed out background  behind the modal (which was a very dark gray) would get a little less gray but the modal would not actually close out.  Just like you I did not want to provide all of my source as it is a rather large project that I was incorporating it in to.  So I started to build a small demo app to try and demonstrate the issue, but found I could not replicate it.  

But after pulling my hair out, I figured out what my issue was!  

I originally was following the instructions at https://modal.blazored.com/getting-started/installation.html vs this github repo and on step 4 of that page it says to add the BlazoredModal component to your applications  MainLayout.razor page which is what I originally did but realized I never had to do this step when following the instructions on this github repo when creating my demo app.

As soon as I removed the <BalzoredModal /> component tag from my MainLayout.razor page the modal will now close.

Not sure if maybe you had also followed this original step or not.  But it would be worth double checking to see if you have that tag in your MainLayout.razor page if you do see if removing it resolves the issue for you.

NOTE: I am using blazor server side. Not sure if that makes a difference.

**Comment by chrissainty** [comment]
Thanks for pointing out the inconsistancy in the docs @larryfura. I'll take a look at this. But you're quite right since v5 you no longer need the `BlazoredModal` component you only need the` CascadingBlazoredModal` component.

**Comment by digitalsigi** [comment]
Hurray! It works now.
@larryfura Thx a lot for your solution. Like you, I am using blazor server side and did follow exactly the same docs.
@chrissainty I believe it would be helpful to mention the blazor server side [Point 4.](https://github.com/Blazored/Modal#4-add-reference-to-style-sheet--javascript-reference) on the main pager here as well. I just added the blazored model js and left out the webassembly.js ...

**Comment by chrissainty** [comment]
@digitalsigi Already done :)
