### ISSUE TITLE
 Possibility to close modal via modalReference or modalService

### ISSUE THREAD

**Issue by troepolik** [Blazored/Modal#159]
Now we can close modal only inside the modal content via ModalInstance obtained from the cascading parameter.
But outside of modal content we can not do that.
For example something like this:
```
var modalref = modalService.Show<Foo>();
modalref.Close();
``` 
or
```
var modalref = modalService.Show<Foo>();
modalService.Close(modalref.Id);
``` 

To achieve that I modify ModalService, ModalReference and BlazoredModal
1) Change Id of ModalReference to public
2) add method Close to ModalService
3) add internal BlazoredModal Modal { get; set; } to ModalService
4) link them in void OnInitialized() of BlazoredModal 
((ModalService)ModalService).Modal = this;

mb  it will be better to move Collection<ModalReference> Modals to modalService but I'am not  sure.

Why did I need it:
I created ProgressbarService which I can use in code that do not directly related with UI:
```
IProgressbarService progressService; //obtained from DI

public async Task ExecuteOperation()
{            
      using var progressbarScope = progressService.Show();
       await operation();            
}
```
progressService  freeze UI and shows progress indicator (spinner)
But in operation may appear modal message dialogs, and of course it  should be over progress indicator,  that why  progress indicator should be as part of modals engine.
And I must be able to close modal inside progressService

**Comment by chrissainty** [comment]
Hi @troepolik,

I'm sorry but I don't understand what you're asking for. We have introduced the `ModelReference` which is what you get back when you call `Show` and you can use this to close a modal as per the docs. Could you please clarify what it is you're asking for?

**Comment by troepolik** [comment]
I'm sorry, I was a little behind in the product version. ModalReference has Close Method now.
I feel so ashamed...
