### ISSUE TITLE
Modal Send/ Modal Return

### ISSUE THREAD

**Issue by scalarerp** [Blazored/Modal#160]
I tried using passingdata and will get returningdata, can you help me?

`
@page "/passingdata"
@inject IModalService Modal

<input class="form-control" type="text" @bind="_message" />

<button @onclick="ShowModal" class="btn btn-primary">Show Modal</button>

@if (!string.IsNullOrWhiteSpace(_return_message))
{
    <p>return_message : @_return_message</p>
}

@code { 
    string _message = "";
    string _return_message;

    async Task ShowModal()
    {
        var parameters = new ModalParameters();
        parameters.Add(nameof(DisplayMessage.Message), _message);

        var messageForm = Modal.Show<MessageForm>("Passing Data", parameters);
        var result = await messageForm.Result;

        if (!result.Cancelled)
            _return_message = result.Data?.ToString() ?? string.Empty;

        _message = _return_message;
    }
}
`

**Comment by larsk2009** [comment]
Could you explain what is going wrong or differently from what you expect?

Below I copied the code you posted. This should show up properly formatted, for everyone's readability.

```
@page "/passingdata"
@Inject IModalService Modal

<input class="form-control" type="text" @Bind="_message" />

<button @OnClick="ShowModal" class="btn btn-primary">Show Modal

@if (!string.IsNullOrWhiteSpace(_return_message))
{
return_message : @_return_message


}
@code {
string _message = "";
string _return_message;

async Task ShowModal()
{
    var parameters = new ModalParameters();
    parameters.Add(nameof(DisplayMessage.Message), _message);

    var messageForm = Modal.Show<MessageForm>("Passing Data", parameters);
    var result = await messageForm.Result;

    if (!result.Cancelled)
        _return_message = result.Data?.ToString() ?? string.Empty;

    _message = _return_message;
}
}
```

**Comment by scalarerp** [comment]
Ok, but dosent work for me

**Comment by larsk2009** [comment]
Yes I understand that it doesn't work, but exactly what is not working?

**Comment by scalarerp** [comment]
I post a new Issue to open a model with a component.
Resuming:, i will send a parameter, a will get a return parameter from modal,

sorry by my english
thanks

**Comment by scalarerp** [comment]
I just need to know if you have to do it, or if it works, or if have a special method etc...

**Comment by scalarerp** [comment]
ok i resolved: 
in MessageForm i change:
[Parameter] public string Message { get; set; }

its works fine.
