### ISSUE TITLE
[Feature Request] Simplify IModalService interface to make it easy to mock

### ISSUE THREAD

**Issue by Liero** [Blazored/Modal#163]
**Is your feature request related to a problem? Please describe.**
`IModalService` contains o lot of methods that are just overload of a single real method. It makes it unnecessarily difficult to create a mock, fake implementation or any implementation. Interface should be as simple as possible.

**Describe the solution you'd like**
There is a [C# 8 feature called default interface methods](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#default-interface-methods), targeting exactly this.

Unfortunatelly, this requires upgrading to .NET Standard 2.1.
Fortunatelly, there is no reason not to upgrade Blazor compnent library to .NET Standard 2.1, since all Blazor runtimes support supports it (.NET Core 3, WebAssembly) and you cannot use the component library anywhere else

**Describe alternatives you've considered**
You can extend interface using extension methods. Take `IServiceCollection` as an example.
`AddSingeton<T>(...)`, `AddTransient<T>(...)` are all just extension methods, that call `IServiceCollection.Add(ServiceDescriptor)`

**Comment by Liero** [comment]
The implementation then would be that simple:
https://github.com/Liero/Modal/blob/f6f63d8dfd8e6ea75c230c3f7bfb3b95dbd67702/src/Blazored.Modal/Services/ModalService.cs

**Comment by chrissainty** [comment]
How would you suggest we surface the overloads without them being present in the interface? 

I wouldn't agree with your view on C# 8 default interfaces. That feature is for providing a default implementation for a new method added to an existing interface. I'm not sure how that fits in here.

**Comment by Liero** [comment]
@chrissainty: 
> How would you suggest we surface the overloads without them being present in the interface?
Well, if it's not possible with optional parameters, than using extension methods. That's how .NET Core API's are designed today by Microsoft.

> I wouldn't agree with your view on C# 8 default interfaces. ... I'm not sure how that fits in here.
Well, Mads Torgersen uses exactly method overloading as example, when preseting default interface method feature, e.g. just last week: https://channel9.msdn.com/Events/Build/2020/BOD108 (0:10:15)

"The reasoning behind is, that when almost all interface implementation implements some of the methods the same way, wouldn't it be nice, if we could just provide default implementation"

I would like more extensions methods, but it would a breaking change.

**Comment by chrissainty** [comment]
Again, I think you’ve misunderstood default interfaces. In the video you’ve linked Mads example is adding a new overload to an existing interface and providing a default implementation as to not break existing code. 

I’m not keen on the idea of extension methods as that can cause issues with mocking frameworks which some people may choose to use. It’s an issues with some of the .NET Core implementations. 

Can you explain why you’re struggling to mock out the existing interface?

**Comment by Liero** [comment]
Backward compatibility when extending interface is of course one of the usecases and it was his second point, however I cited Mads literally: 

**"The reasoning behind is, that when almost all interface implementation implements some of the methods the same way, wouldn't it be nice, if we could just provide default implementation" - Mads Torgersen  **

Which is exactly this case - I need to mock the interface and in the mock I need to implement all the overloads the same way as in real implementation - which is a code smell at least.  This has nothing to do with backward compatibility.

**Comment by chrissainty** [comment]
But why are you struggling to mock the existing interface? Normally you would verify a call to the particular overload on the interface you were calling in your test. What is stopping you doing this? Are you calling every overload of the service in a single test, therefore needing to mock all overloads?

**Comment by Liero** [comment]
1. I usually create a fake implementation of the interface, that I use across all tests. In the fake imlementation I'm basically forced copy & paste the overload implementations.
2. In my tests, I don't like relying on mocking specific overload, because that is implementation details that I don't care in my tests. If I decide do use another overload, the test will fail even when the code is completely valid and does not break the logic that I actually want to test.

Anyway, I can live with that. That was just a suggestion. If you think, it's not a good idea or it's not worth it, then OK, feel free to close this issue.

**Comment by chrissainty** [comment]
@Liero Apologies for taking a while to come back to this. If you want to raise a PR with your default interface implementation, I'll be happy to merge it.
