### ISSUE TITLE
[Bug] Modal is not showing

### ISSUE THREAD

**Issue by lewinskimaciej** [Blazored/Modal#165]
Every step of readme was followed, nothing besides basic component(TestModal) and button on Index page were added.
Modal should show after clicking on the button, yet nothing happens. Tried on Chrome/chromium-Edge.

Created repo to reproduce:
https://github.com/lewinskimaciej/BlazorTest

This is a fresh blazorserver template with a button added on Index page

Hosting model:
 - Blazor Server

I can't get it to work. I tried various paths to css, I tried with `<button>` and `<a>`, with an async method in `@onclick` and void one. Tried adding `StateHasChanged();` in multiple places, even tried the `Task.Delay(500)` someone mentioned in one of the issues. Modal just doesn't show.

In order to further reproduce this, I've cloned this repo, ran server sample, this is the result:
![image](https://user-images.githubusercontent.com/1175985/83387667-6842b400-a3ed-11ea-8482-ccb0146fd1cd.png)
I believe someone already posted similar screenshot in one of the issues. Never touched anything else besides running the project.

There's no console issues, I see .css being downloaded properly in dev console, no exceptions thrown anywhere.

**Comment by larsk2009** [comment]
If I add <BlazoredModal/> to the MainLayout.razor page in your repo like it says in the readme, it does work. See [step 3](https://github.com/Blazored/Modal#3-add-modal-component).

**Comment by lewinskimaciej** [comment]
You're right, I guess I'm legally blind then... Thank you! I've looked at it for an hour and still didn't notice...
I guess this can be closed. I have no clue why Sample doesn't layout nicely though.
