### ISSUE TITLE
[Bug] Blazor Server hosting model

### ISSUE THREAD

**Issue by standsed** [Blazored/Modal#168]
Is Modal working in Blazor Server hosting model?
1. Cloned Modal repo.
2. cd Modal/Samples/BlazorServer
3. dotnet run

Firefox 76.0.1
![image](https://user-images.githubusercontent.com/37961304/83726043-a0473280-a64b-11ea-811d-3582d4b7922f.png)

Chrome 83.0.4103.61
![image](https://user-images.githubusercontent.com/37961304/83726344-13e93f80-a64c-11ea-85ec-4886570de6f6.png)

**Comment by chrissainty** [comment]
@standsed Yes, I've been working on the repo this morning. It looks like you could have something cached, if you've previously cloned the repo. But it will be a local issue.

**Comment by standsed** [comment]
Tried on different machine Windows 10, Firefox 77 (before was macOS). 
Same exact result

**Comment by chrissainty** [comment]
It's definitely working fine, I use two Windows machines and a MacBook and all are working as expected. 

![image](https://user-images.githubusercontent.com/6171719/83728196-18a6f700-a63e-11ea-92e1-8a357b4abc8c.png)

**Comment by larsk2009** [comment]
@chrissainty Actually, if you run it like he described, with `dotnet run`, I get the same result. But using VS it does work. See image below, for some reason it cannot download the css file from the server.
![image](https://user-images.githubusercontent.com/7924568/83728739-054c5980-a647-11ea-807d-21a4dd655131.png)

**Comment by chrissainty** [comment]
Thanks for the comment @larsk2009. It runs fine for me under `dotnet run`, that's what I use on the Mac. Just tried it on Windows and it works as expected as well. But as you've pointed out. I've run the project in VS previously. 

Either way, I don't think it has anything to do with this project and seems more like a tooling issue.

**Comment by larsk2009** [comment]
I agree @chrissainty

**Comment by standsed** [comment]
For someone not using VS, enabling in config [UseStaticWebAssets](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.webhostbuilderextensions.usestaticwebassets?view=aspnetcore-3.1) fixed the issue

It then uses YourProject/obj/Debug/netcoreapp3.1/staticwebassets/YourProject.StaticWebAssets.xml
to resolve these files. In my case from local nuget directory.
