### ISSUE TITLE
passing parameters needs an update on https://chrissainty.com/blazored-modal-released/

### ISSUE THREAD

**Issue by gregorvilkner** [Blazored/Modal#169]
**Is your feature request related to a problem? Please describe.**
This package is super useful 👍 
I struggled quiet a bit getting parameter passing to work. I worked of your sample code on https://chrissainty.com/blazored-modal-released/ It's correct in the md here and in obviously it works in your repo. Cheers.

**Describe the solution you'd like**
current content:
`[CascadingParameter] ModalParameters Parameters { get; set; }`
`int MovieId { get; set; }`

needed content:
`[CascadingParameter] BlazoredModalInstance BlazoredModal { get; set; }`
`[Parameter] public int MovieId { get; set; }`

**Comment by chrissainty** [comment]
@gregorvilkner That post is getting quite old now. As I've mentioned in other issues, I just can't keep every post I write updated, there just isn't the time available. I've added a call out section to the post to highlight that people should checkout modal.blazored.com or here for the latest instructions.
