### ISSUE TITLE
[Feature Request] Easier mocking of Modal interactions

### ISSUE THREAD

**Issue by anemitoff** [Blazored/Modal#170]
**Is your feature request related to a problem? Please describe.**
I am trying to mock out some behavior for a test case where the sut invokes modalService.ShowModal().  

**Describe the solution you'd like**
Have the ModalReference constructor accept an IModalService instance instead of the concrete ModalService 

OR 

IModalService.Show return a mockable IModalReference (which doesn't exist)

**Describe alternatives you've considered**
I am considering implementing my own MockModalReference class that inherits from ModalReference but has its own implementations.  But this seems like overkill.

**Additional context**
None

**Comment by chrissainty** [comment]
Hi @anemitoff, apologies for taking so long to address your issue. I think my preference would be to return an `IModalReference` from the `Show` call. That way you can mock whichever response you wish. Adjusting the `ModalReference` to take an `IModalService` would be more tricky.

Happy to mark this as a new feature.

**Comment by anemitoff** [comment]
Hi @chrissainty, no worries on the delay.  Thank you for all of your Blazor projects and blog entries!!!
I think returning an `IModalReference` would work just fine.
