### ISSUE TITLE
[Feature Request] Make the Modal Top Center-able

### ISSUE THREAD

**Issue by Karamethien** [Blazored/Modal#177]
Currently, the default positions enum have Top Left, Top Right, but it does not have Top Center.

**Comment by pablopioli** [comment]
I build a pull request to implement custom position via CSS.
https://github.com/Blazored/Modal/pull/180

This would accomplish what you want here.

**Comment by chrissainty** [comment]
I'm going to close this issue as its actually a duplicate of #146
