### ISSUE TITLE
Nuget package v4.1.0 does not have blazored-modal.css

### ISSUE THREAD

**Issue by wvmstr** [Blazored/Modal#178]
FYI

Was not able to trigger a modal, found an earlier closed issue where someone found the blazored-modal.css to be empty the browser.

Mine was empty to.

Copied this css from the blazored-modal repo, and now it works.

**Comment by larsk2009** [comment]
I just had a look at the V4.1.0 package with the [Nuget Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) and there the css file definitely exists. I am not sure what is going wrong, but the package does seem to contain the css file.

![image](https://user-images.githubusercontent.com/7924568/85132688-91f73a00-b239-11ea-974f-9d869c32517d.png)

**Comment by wvmstr** [comment]
I did a wildcard seach in the solution for *.css, and there was no blazored-modal.css. Copied it from the cloned repo on my local machine.

Is it possible this file in the package but somehow is not getting it installed?

**Comment by larsk2009** [comment]
The css file is not really in your own solutions, but it is in the nuget package, so I think it is possible you can not find the css file like that.. Could you maybe show how you included the css file in your project? The issue is probably in there, or if it is not we have at least ruled it out.

**Comment by wvmstr** [comment]
This project's readme says:
`Add the following line to the `head` tag of your `_Host.cshtml` (Blazor Server) or `index.html` (Blazor WebAssembly).

```html
<link href="_content/Blazored.Modal/blazored-modal.css" rel="stylesheet" />
````
Ended up keeping it in the same folder as app.css
`<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>UserNameClient</title>
    <base href="/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/app.css" rel="stylesheet" />
    <link href="_content/MatBlazor/dist/matBlazor.css" rel="stylesheet" />
    <link href="css/blazored-modal.css" rel="stylesheet" />
    
</head>

<body>
    <app>Loading...</app>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <script src="_framework/blazor.webassembly.js"></script>
    <script src="_content/MatBlazor/dist/matBlazor.js"></script>
</body>

</html>`

**Comment by wvmstr** [comment]
Remember that I searched the entire project for "blazored-modal.css". There was nothing there

**Comment by larsk2009** [comment]
If you use the sample project provided and in that folder look for "blazored-modal.css" you will also see that it is not there. This is normal behaviour. You have the include the css file like it says in the readme to work.

`<link href="_content/Blazored.Modal/blazored-modal.css" rel="stylesheet" />`

That is the way the css will get used from the Nuget package. The fact that you cannot find the "blazored-modal.css" in your entire project is because it is included from the Nuget package.

**Comment by chrissainty** [comment]
As there hasn't been any comment on here for a few days I'm going to assume the problem has been resolved. Please re-open if you're still experiencing an issue.
