### ISSUE TITLE
Does the example close the form after the Save?

### ISSUE THREAD

**Issue by tomRedox** [Blazored/Modal#18]
Hi Chris

Sorry, another question:

The example code has these two methods wired up in the `EditMovie` component:

```
    void SaveMovie()
    {
        MovieService.Save(Movie);
    }

    void Cancel()
    {
        ModalService.Cancel();
    }
```

The Cancel method is calling back to the `ModalService.Cancel()` to close the modal again, but the `SaveMovie` method doesn't appear to trigger the modal to close?  Is there some magic wiring in the background that makes that happen automatically (I don't think there is, but just checking) or would I need to do something like this to make the form close:

```
    void SaveMovie()
    {
        MovieService.Save(Movie);
        ModalService.Close(ModalResult.Ok<Movie>(Movie));
    }
```

If so, I think it might be worth adding that to the example?  I'm can do a PR in with that change if that's useful?

**Comment by chrissainty** [comment]
Ask as many as you like 😄 

You're correct there is no magic, you would have to make an additional call to the `Close` method on the modal service.

If you're happy to update the example I'd love to take the PR.

**Comment by tomRedox** [comment]
Hi Chris, PR submitted!  I wonder if a convenience method of ModalService.Close() would be useful for those scenarios where a return object isn't needed?
