### ISSUE TITLE
Scrollable content

### ISSUE THREAD

**Issue by pablopioli** [Blazored/Modal#183]
**Is your feature request related to a problem? Please describe.**
If you have an scrollable modal over a scrollable body, the scroll action can be unintitive as the mouse wheel will act upon the main body.
This is a problem already referenced in
https://github.com/Blazored/Modal/issues/35

**Describe the solution you'd like**
I would like an option or a default that disables this behaviour.

**Describe alternatives you've considered**
I have implemented this disabling the overflow in the main body via Javascript interop. But you must do it manually before calling the modal.

This could be implemented in Blazored Modal, I could do it. But it will require Javascript that the user will need to include manually, making it a breaking change. Automatic Javascript injection is possible but, resorts to some kind of hacks.

**Comment by matko238** [comment]
Something like [this](https://css-tricks.com/prevent-page-scrolling-when-a-modal-is-open/) would be proper solution...

**Comment by pablopioli** [comment]
> 
> 
> Something like [this](https://css-tricks.com/prevent-page-scrolling-when-a-modal-is-open/) would be proper solution...

Yes, there are a couple of solutions. But you must remember to implement them everywhere you use the modal.

On the other hand it can be integrated in Blazored Modal, but it will always requiere a bit of Javascript, wich can be a breaking change. 

So I posted here for consideration by the author.

**Comment by chrissainty** [comment]
I believe this could be fixed by the focus trap implemented with #185

**Comment by szmalec** [comment]
Does this change make it impossible to achieve the effect of a sticky window (e.g. with information about cookies or e.g. a tool panel)? I mean something similar to the modal from [this website](https://mdbootstrap.com/docs/jquery/modals/generator/) (set "Backdrop?" = "No" and then set "Postition" = "Fluid modal" - eg. "Right" or set "Postion" = "Frame modal" - eg. "Bottom", etc. ) - as you can see when such a modal window is open, you can still navigate (scroll) on the page...

Does the current version of Blazored modal let you turn off the backdrop effect at all?

**Comment by chrissainty** [comment]
@szmalec Hi, thanks for your enquiry but could you please raise this as a new issue? That way if it leads to any work its easier to track everything. Thanks.
