### ISSUE TITLE
Question Updating Modal 4.1.0 to 5.0.1

### ISSUE THREAD

**Issue by Orgbrat** [Blazored/Modal#195]
I am trying to update Blazor.Server Blazored.Modal from version 4.1.0 to the new version 5.0.1 and it is beating me up. 
The 4.1.0 version works perfectly though.  If I add your CascadingBlazoredModal  component as you request when the application starts it crashes on the `<app>` line in the _Host.cshtml below with a error of "InvalidOperationException: Blazored.Modal.BlazoredModal requires a cascading parameter of type IModalService".  Is there an issue with having two components wrapping the router in the App.razor file? How do I get around this issue?

The App.razor page already has a "CascadingAuthenticationState" component wrapping the router and has some additional
parameters the application needs that are stored in your loacalStorage component.

`@code{
    [Parameter] public string UserAgent { get; set; }
    [Parameter] public string IPAddress { get; set; }
    [Parameter] public string ServerUrl { get; set; }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await localStorage.SetItemAsync("UserAgent", UserAgent);
            await localStorage.SetItemAsync("IPAddress", IPAddress);
            await localStorage.SetItemAsync("ServerUrl", ServerUrl);
        }
    }
}
`
And then the _Host.cshtml has some code like below inside the body tags:

`       <app>
        <component type="typeof(App)" render-mode="ServerPrerendered" param-UserAgent="@Model.UserAgent" param-IPAddress="@Model.IPAddress" param-ServerUrl="@Model.ServerUrl" />
    </app>`

Orgbrat

**Comment by chrissainty** [comment]
Hey @Orgbrat, have you added the services in your Startup? I'm guessing as you're upgrading you already had that added in but just want to check.

`services.AddBlazoredModal();`

**Comment by Orgbrat** [comment]
@chrissainty  yes I walked thru your setup guide step by step to make sure everything was correct. Plus I compared my project with your sample projects to make sure I had not missed any thing. Have spent hours trying to figure out what I am doing wrong.  I have the below entries in ConfigureServices. Undo changes and rollback to 4.1.0 and all is happy again.

`
services.AddBlazoredModal();
services.AddBlazoredToast();
services.AddBlazoredLocalStorage();`

**Comment by chrissainty** [comment]
Are you able to share your code?

**Comment by Orgbrat** [comment]
I might could share the Blazor.Server project but the dependent projects will not let you run it.

**Comment by chrissainty** [comment]
That would be great, it's really hard for me to diagnose issues like this without a working repro of the problem.

**Comment by nyash** [comment]
Hi,

Might not be related to your problem, but check if you have removed the leftover `<BlazoredModal/>` from `<MainLayout>` component. 

After upgrade to the new version I have added the new `CascadingBlazoredModal` to `App.razor`  and got tripped by this (App would crash, or double Modals would appear).

**Comment by Webreaper** [comment]
> Might not be related to your problem, but check if you have removed the leftover `<BlazoredModal/>` from `<MainLayout>` component.

This fixed it for me.

**Comment by frablaser** [comment]
For me too.

Definitely the the <BlazoredModal/> from <MainLayout> component was missing in my project and everything worked after I added it...

**Comment by nyash** [comment]
> For me too.
> 
> Definitely the `<BlazoredModal/>` from `<MainLayout>` component was missing in my project and everything worked after I added it...

Are you certain? In the previous version `<BlazoredModal/>` was present in MainLayout, but in the new version we are supposed to add the new '<CascadingBlazoredModal/>`. It's easy to forget about the old component, so removing `<BlazoredModal/>` would be the fix, not adding it.

**Comment by Orgbrat** [comment]
Ok,  I think the leftover  `<BlazoredModal/>` in the `<MainLayout>` component was causing the initial crash on application startup. After removing that crash seems to be fixed.

Now, if I add the `<CascadingBlazoredModal/>` component not wrapping the Router the application starts and runs but all modals crash when showing because the Modal CascadingParameter in the code-behind is null.

Since there is already a `<CascadingAuthenticationState>` component wrapping the Router as soon as you add the `<CascadingBlazoredModal/>`  component wrapped around the Router as you request the application crashes on startup with the error "InvalidOperationException: Authorization requires a cascading parameter of type Task<AuthenticationState>.  Consider using CascadingAuthenticationState to supply this."

Evidently there is an issue with multiple components wrapping the Router at the same time in the App.razor page. I did get a demo sample created. It does run but even it shows the requested page loaded twice in the same browser window. One side has the model null and the other side works. This is all so weird.  :)

Just test this demo app and see the dual items. There is a "Show Modal" button on the Counter page.
Left side button crashes because Modal is null and right side works as expected.

[BlazoredDemo.zip](https://github.com/Blazored/Modal/files/4932187/BlazoredDemo.zip)

Orgbrat

**Comment by frablaser** [comment]
> 
> 
> > For me too.
> > Definitely the `<BlazoredModal/>` from `<MainLayout>` component was missing in my project and everything worked after I added it...
> 
> Are you certain? In the previous version `<BlazoredModal/>` was present in `<MainLayout>`, but in the new version we are supposed to use `<CascadingBlazoredModal/>` (that wraps it). It's easy to miss the old component declaration, so removing `<BlazoredModal/>` would be the fix, not adding it.

I saw where was the problem, I was using the source code of the 4.1, and it works with  `<BlazoredModal/>`, I downloaded the 5.0.1 with the new way it works... But...

When I tried to compile the Blazor.Modal library, I have this error... 

> Error	MSB3073	The command "npm install" exited with code 9009.	Blazored.Modal	P:\Download\Prog\Blazor\Modal-main\src\Blazored.Modal\Blazored.Modal.csproj

It bumping into the:
```
  <Target Name="NpmInstall" BeforeTargets="BeforeBuild" Inputs="package.json" Outputs="$(NpmInstallStampFile)">
    <Exec Command="npm install" />
    <Touch Files="$(NpmInstallStampFile)" AlwaysCreate="true" />
  </Target>
```

**Comment by chrissainty** [comment]
@frablaser ahh, my bad. That code should only run in a debug build not on every build. I'll take a look at that.

@Orgbrat Have you tried swapping the order of the various cascading parameters? There isn't any reason multiple cascading parameters can't be used together so this must be something causing some interference.

**Comment by Orgbrat** [comment]
@chrissainty  Yes I have swapped the order around but still issues.  The issue is the in the App.razor file try the demo I sent you.

**Comment by larsk2009** [comment]
@Orgbrat See the attached zip. I changed your app.razor and it seems to work fine on my machine that way. What you did in your example was create 2 routers, one which had the authentication and one which had the modal. Just combine them like I did in this zip file:

[BlazoredDemo.zip](https://github.com/Blazored/Modal/files/4933159/BlazoredDemo.zip)

**Comment by Orgbrat** [comment]
@larsk2009 Thank you, thank you...  That fixed my issues with the application starting and running.

I still have issues with the Modals,  Old way passed modal parameters as CascadingParameters and now I must change that to  individual parameters with the Parameter attribute.  I will change to the new way on everything and see where I am at.

Sure is a lot of stuff changed but if I fix it now then I will be ok for awhile.

Again thanks @frablaser, @larsk2009  and @chrissainty  for the help. Thanks...

Orgbrat

**Comment by chrissainty** [comment]
As far as I can see the original issue is now resolved, so I'm going to close the issue.
