### ISSUE TITLE
[Bug] Showing the modal throws an unhandled error has occurred (version 5.0.1)

### ISSUE THREAD

**Issue by AlexandreBeauchamp** [Blazored/Modal#196]
**Describe the bug**
I updated to 5.0.1 (it was 4.1.0 and working without problem) and follow every step to make sure everything works.
The app will start normally without errors. But the moment i click a button for showing a modal, it will throws *an unhandled error has occurred* at the bottom page and the modal doesn't appear. The project is a Blazor assembly with ASP.NET Core hosted.

**Expected behavior**
It should open the modal without throwing exception.

**Screenshots**
Here the errors i got from the console. It mostly said that JSInterop could not find BlazoredModal in window
![image](https://user-images.githubusercontent.com/51452852/87672168-8287e580-c740-11ea-95c8-09f109accae6.png)

**Comment by larsk2009** [comment]
Can you confirm you have added the JS file? See [step 4](https://github.com/Blazored/Modal#4-add-reference-to-style-sheet--javascript-reference) of the readme? Without seeing your code, it seems like the JS file is missing.

**Comment by AlexandreBeauchamp** [comment]
Yes i added the JS File in index.html

**Comment by larsk2009** [comment]
And do you also see it being loaded in the development console?

**Comment by AlexandreBeauchamp** [comment]
The first time i compiled the project and start. The js file will not be loaded, but if i reload then the js file is loaded and i can open the modal with some weird behavior.

![image](https://user-images.githubusercontent.com/51452852/87674694-5706fa00-c744-11ea-8fe0-1c639ed017cc.png)

**Comment by larsk2009** [comment]
If you can share your project/code we can have a look what is going wrong.

**Comment by AlexandreBeauchamp** [comment]
I can't share the code because it in a private repository, but i can share in zip file :)

So yeah, you can check Handler page and click on Edit quantity received, the modal should popup. In the code, you can check Handlers folder where contains the component which have the AirwayBillAction (contais the action to show the modal) and the page handler who render this component. AirwayBillList is in the shared folder. All razor file have the code behind

[GMTS.Web.zip](https://github.com/Blazored/Modal/files/4931760/GMTS.Web.zip)

**Comment by larsk2009** [comment]
Thanks, I will have a look.

**Comment by chrissainty** [comment]
@AlexandreBeauchamp This could be a caching issue, this seems to happen quite a lot with JavaScript files in Blazor. Could you try a private tab and/or also clearing out your browser cache as well.

**Comment by AlexandreBeauchamp** [comment]
I confirm is a cache issue. I try in a private tab and clearing the browser cache. Everything work now!! :D The modal is showing correctly without errors and working perfectly

**Comment by AlexandreBeauchamp** [comment]
Thx for these quick responses :) really appreciated. Have nice day. I will close the issue since it is resolved

**Comment by adriantether** [comment]
this might be late for some but a few things I went through to get this going as I wrote my own code not used the github project..
1/ npm install the package 
2/ @using Blazored.Modal @using Blazored.Modal.Services to the _imports razor
3/ wrap your page or component in a <CascadingBlazoredModal>
4/  <script src="_content/Blazored.Modal/blazored.modal.js"></script>
     <script src="_content/Blazored.Modal/Blazored.Modal.activateScrollLock.js"></script>  add these to the imports razor
i think i coverd every thing , all the rest was my creation of the modal and the data for it ... gl
