### ISSUE TITLE
Edit form model validation does not work

### ISSUE THREAD

**Issue by DSBhogal** [Blazored/Modal#199]
I have a modal that contains an edit form but the validation for all fields does not show/work. This is the case for custom validation attributes and built in attributes by Microsoft. Any ideas what the issue is whether it be to do with my code or something related to the modal?

I'm using Blazored Modal v4.1.0

**Code**

![image](https://user-images.githubusercontent.com/33750091/87781508-b0e0f000-c828-11ea-92ad-3f3dda8d1a41.png)

**Model**

![image](https://user-images.githubusercontent.com/33750091/87781540-c0f8cf80-c828-11ea-96be-3d0cdc57a4d9.png)

**Comment by chrissainty** [comment]
Hi @DSBhogal, have you proved this code works when it's not in the modal?

**Comment by DSBhogal** [comment]
I have seen no errors as of yet, the validation does work when not in the modal.

**Comment by DSBhogal** [comment]
I redid the component and for some reason it has started to work so I'm unsure what the issue was. Appreciate the help, I will close this
