### ISSUE TITLE
Getting error after v5 upgrade on Blazor 3.2 wasm project

### ISSUE THREAD

**Issue by wgrs** [Blazored/Modal#203]
Thanks for the great components Chris - I use them everywhere!

I am probably doing something wrong but this piece of code is throwing the following error since I updated Modal Component to v5.02.

This line of code is throwing an error.
`formModal = Modal.Show<EditAgentForm>("Edit Managing Agent", parameters);`

The error is "cannot convert Blazored.Modal.IModalReference to Blazored.Modal.ModalReference"

I have removed the Modal tag from  MainLayout and wrapped the App.Razor with CascadingBlazoredModal

**Comment by chrissainty** [comment]
Glad you like the components, @wgrs :)

We changed what is returned from the show method from `ModalReference` to `IModalReference`. Based on the error it looks like you've got a type mismatch somewhere. How is `formModal` typed?

**Comment by wgrs** [comment]
OK - thanks. That was it.
