### ISSUE TITLE
Modal without backdrop (tool window)

### ISSUE THREAD

**Issue by szmalec** [Blazored/Modal#204]
**Is your feature request related to a problem? Please describe.**
There was lately introduced change #186 (due to #183). Does this change make it impossible to achieve the effect of a sticky window (e.g. with information about cookies or e.g. a tool panel)?

**Describe the solution you'd like**
I would like to achieve something similar to the modal from [this website](https://mdbootstrap.com/docs/jquery/modals/generator/) (set "Backdrop?" = "No" and then set "Postition" = "Fluid modal" - eg. "Right" or set "Postion" = "Frame modal" - eg. "Bottom", etc. ) - as you can see when such a modal window is open, you can still navigate (scroll) on the page... Does the current version of Blazored modal allows to achieve something like that (turn off the backdrop effect completly + allow to scroll main page content)?

**Comment by chrissainty** [comment]
Hi @szmalec, the current version doesn't allow this behaviour. I don't think I'd want to put anything to specific into the library for this, I think if we just expose an options to enable background scrolling, then developers can use the existing custom position functionality to achieve whatever experience they wish.

Does this sounds like it would enable your scenario?

**Comment by szmalec** [comment]
@chrissainty 
Finally, to achieve the tool window effect, I used a different solution than the blazored modal.
However, in order for Blazored Modal to create any possibilities of achieving a similar effect, apart from the option to enable background scrolling, an option to disable automatic closing of modal windows when changing locations would probably have to be added ([see this code here](https://github.com/Blazored/Modal/blame/8b121825936a94c24d373cacf508e2d631d96c9d/src/Blazored.Modal/BlazoredModal.razor.cs#L39)).
Introducing both options would seem sufficient if somebody in the future would use blazored modal in order to get the tool window effect.
Best regards!

**Comment by chrissainty** [comment]
Thanks for the update @szmalec. I think at the moment, this isn't something that will be added. But perhaps if more requests come in we could look at it in the future. For now I'm going to close this issue and will reopen if there is more interest.
