### ISSUE TITLE
Problem after upgrade (v4 to v5): Modal acting like background

### ISSUE THREAD

**Issue by jsarnikorpi** [Blazored/Modal#205]
Upgraded from v4.1.0 to v5.0.2.

BlazorServer / Modal dialog will open but is acting like background:

- Dialog is "greyed"
- If I click anywhere inside (or outside) dialog then dialog is closed. 
- If "DisableBackgroundCancel=true" is used then nothing will happen when clicking dialog

screenshot (whole page including modal dialog is greyed):
![BlazoredModal-problem](https://user-images.githubusercontent.com/68731603/88376222-a0d78c00-cda5-11ea-8824-3824228477ce.png)

I guess there is something I have missed after upgrade or maybe some v4 setting will cause the problem. But I have no idea where to start.

**Comment by chrissainty** [comment]
The most common mistake is forgetting to remove the old `<BlazoredModal>` tag from your `MainLayout`. If that isn't the issue, then it's possibly a caching issue.

**Comment by jsarnikorpi** [comment]
> The most common mistake is forgetting to remove the old `<BlazoredModal>` tag from your `MainLayout`. If that isn't the issue, then it's possibly a caching issue.

Forgot to mention that <BlazorModal> is removed. What kind of cache do you mean? I tested another browser (Edge -> I haven't used Edge before with this project...) and the same problem exists.

I am developing with Visual Studio Community 2019 (version 16.6.3). Is there anything I could do with the project?

**Comment by jsarnikorpi** [comment]
I did found solution.

I have used custom styling via ModalOptions. Problem occurs if only custom class is defined (I was used this kind of code with version 4):

```
var options = new ModalOptions()
        {
            Class = "custom-class"
        };
```

If I add class "blazored-modal" 

`Class = "blazored-modal custom-class"` 

then everything is working without problem.

**Comment by chrissainty** [comment]
@jsarnikorpi We take the view that if you're passing a custom class you only want that applied, so we remove the `blazored-modal` class and replace it with whatever you provide.

**Comment by chrissainty** [comment]
As there isn't anything to do here I'm going to close this issue.
