### ISSUE TITLE
After updating to v5 Close and OnClose not recognised methods?

### ISSUE THREAD

**Issue by chewabledrapery** [Blazored/Modal#208]
Hi,

I've tried to look through the issues/upgrade notes so I'm sure I've missed something and being dumb but after updating from v3 to v5 i get this error for Close and OnClose 

"CS1061	'IModalService' does not contain a definition for 'Close' and no accessible extension method 'Close' accepting a first argument of type 'IModalService' could be found (are you missing a using directive or an assembly reference?"

I've re-followed the wiki and it seems i have made the neccessary tweaks to use Blazored.Modal correctly, any obvious things i ought to check/refactor?

Using core 3.1 preview.

Many thanks,

Dean

**Comment by chrissainty** [comment]
Hi Dean,

Could you provide some code showing where the problem is occurring?

**Comment by chewabledrapery** [comment]
Hi Chris,

Thanks for the reply I appreciate it, razor code below, I also cannot access the Cancel method.

Intellisense in VS 2019 only shows the following methods...

![image](https://user-images.githubusercontent.com/33089517/89169516-3f1ddb80-d576-11ea-86c0-ab6c8b1a706c.png)


`@page "/ArchiveInboxFileModal"
@using DoculogIQ.Data
@using DoculogIQ.Data.Models
@using DoculogIQ.Validation

@inject AuthenticationStateProvider AuthenticationStateProvider
@inject DataAccessService DataAccessService
@inject IModalService ModalService
@*
	Using OwningComponentBase ensures that the service and related services
	that share its scope are disposed with the component.
	Otherwise DbContext in DataAccessService will live for the life of the
	connection, which may be problematic if clients stay
*@
@inherits OwningComponentBase<DataAccessService>
@if (inboxfiletoarchive != null)
{
	<EditForm Model="@inboxfiletoarchive" OnValidSubmit="@Submit">
		<FluentValidationValidator />
		<ValidationSummary />
		<p>@inboxfiletoarchive.Sourcefilename</p>
		@if (DataAccessService.lstInboxes_SubCategories.Count > 1)
		{
			<div class="form-group row">
				<label for="selectSubCategory" class="filesearch-label">Sub Category</label>
				<select id="selectSubCategory" class="form-control" @bind="@inboxfiletoarchive.SubCategoryId">
					<option value="0">Please select...</option>
					@if (DataAccessService.lstInboxes_SubCategories != null)
					{
						@foreach (var subcategory in DataAccessService.lstInboxes_SubCategories)
						{
							<option value="@subcategory.SubCategoryId">@subcategory.SubCategoryName</option>
						}
					}
				</select>				
			</div>
		}
		@foreach (var archiveinboxfilefieldvalues in inboxfiletoarchive.ArchiveInboxFileFieldValues)
		{
			<div class="form-group row">				
				<div class="col-lg-12">
					<label for="@archiveinboxfilefieldvalues.CategoryFieldDefinitionId" class="archiveinboxfile-label">@(@archiveinboxfilefieldvalues.IsRequired == true ? @archiveinboxfilefieldvalues.CategoryFieldName + "*" : @archiveinboxfilefieldvalues.CategoryFieldName)</label>
					<InputText id="@archiveinboxfilefieldvalues.CategoryFieldDefinitionId" class="form-control" autocomplete="off" @bind-Value="@archiveinboxfilefieldvalues.FieldValue"></InputText>
				</div>
			</div>
		}
		<div class="form-group">
			<button type="submit" class="btn btn-primary">Save</button>
			<button @onclick="@Cancel" class="btn btn-secondary">Cancel</button>
		</div>				
	</EditForm>
}





@code {
	[CascadingParameter] private Task<AuthenticationState> authenticationStateTask { get; set; }

	[CascadingParameter] ModalParameters ModalParameters { get; set; }

	private List<CategoryFieldDefinition> categoryfielddefinitionList;

	InboxFileToArchive inboxfiletoarchive = new InboxFileToArchive();

	private bool blnCancelClicked = false;

	protected override async Task OnInitializedAsync()
	{
		await GetInboxFile();
	}

	protected async Task GetInboxFile()
	{
		var user = (await authenticationStateTask).User;

		InboxFile inboxfile;

		inboxfile = await DataAccessService.GetInboxFile_Async(ModalParameters.Get<int>("InboxFileID"));

		inboxfiletoarchive.CategoryId = ModalParameters.Get<int>("CategoryID");
		inboxfiletoarchive.SubCategoryId = 0;
		inboxfiletoarchive.InboxFileId = inboxfile.InboxFileId;
		inboxfiletoarchive.Sourcefilename = inboxfile.Sourcefilename;

		categoryfielddefinitionList = await DataAccessService.GetCategoryFieldDefinitions_Async(user.Identity.Name, ModalParameters.Get<int>("CategoryID"));

		foreach (var categoryfielddefinition in categoryfielddefinitionList)
		{
			inboxfiletoarchive.ArchiveInboxFileFieldValues.Add(new InboxFileToArchiveFieldValue { CategoryFieldDefinitionId = categoryfielddefinition.CategoryFieldDefinitionId, CategoryFieldName = categoryfielddefinition.CategoryFieldName, IsRequired = categoryfielddefinition.IsRequired });
		}

		await DataAccessService.GetInboxesSubCategories_Async(ModalParameters.Get<int>("CategoryID"));

		if (DataAccessService.lstInboxes_SubCategories.Count == 1)
		{
			inboxfiletoarchive.SubCategoryId = DataAccessService.lstInboxes_SubCategories.First().SubCategoryId;
		}
	}

	protected async void Submit()
	{
		if (!blnCancelClicked)
		{
			int updateresult = 0;

			updateresult = await DataAccessService.UpdateInboxFile(inboxfiletoarchive);

			ModalService.Close(ModalResult.Ok<int>(updateresult));
		}		
	}

	protected void Cancel()
	{
		blnCancelClicked = true;
		ModalService.Cancel();
	}
}`

**Comment by larsk2009** [comment]
At least one issue I see is that the `IModalService` is injected. In V5 this is changed to a CascadingParameter, so getting the IModal is done like this:

`    [CascadingParameter] public IModalService Modal { get; set; }`

I am not sure if this fixes your issue. Could you try to fix the formatting of the code you posted, so it is easier to look trough?

**Comment by chewabledrapery** [comment]
Hi,

Thanks for the reply, i hadn't noticed that in the wiki examples.

I've refactored the code, removed the injection and declared a public cascading parameter for the service and i have the same problem...

See refactored code below. Many thanks.

`
@page "/ArchiveInboxFileModal"
@using DoculogIQ.Data
@using DoculogIQ.Data.Models
@using DoculogIQ.Validation

@inject AuthenticationStateProvider AuthenticationStateProvider
@inject DataAccessService DataAccessService

@inherits OwningComponentBase<DataAccessService>
@if (inboxfiletoarchive != null)
{
	<EditForm Model="@inboxfiletoarchive" OnValidSubmit="@Submit">
		<FluentValidationValidator />
		<ValidationSummary />
		<p>@inboxfiletoarchive.Sourcefilename</p>
		@if (DataAccessService.lstInboxes_SubCategories.Count > 1)
		{
			<div class="form-group row">
				<label for="selectSubCategory" class="filesearch-label">Sub Category</label>
				<select id="selectSubCategory" class="form-control" @bind="@inboxfiletoarchive.SubCategoryId">
					<option value="0">Please select...</option>
					@if (DataAccessService.lstInboxes_SubCategories != null)
					{
						@foreach (var subcategory in DataAccessService.lstInboxes_SubCategories)
						{
							<option value="@subcategory.SubCategoryId">@subcategory.SubCategoryName</option>
						}
					}
				</select>				
			</div>
		}
		@foreach (var archiveinboxfilefieldvalues in inboxfiletoarchive.ArchiveInboxFileFieldValues)
		{
			<div class="form-group row">				
				<div class="col-lg-12">
					<label for="@archiveinboxfilefieldvalues.CategoryFieldDefinitionId" class="archiveinboxfile-label">@(@archiveinboxfilefieldvalues.IsRequired == true ? @archiveinboxfilefieldvalues.CategoryFieldName + "*" : @archiveinboxfilefieldvalues.CategoryFieldName)</label>
					<InputText id="@archiveinboxfilefieldvalues.CategoryFieldDefinitionId" class="form-control" autocomplete="off" @bind-Value="@archiveinboxfilefieldvalues.FieldValue"></InputText>
				</div>
			</div>
		}
		<div class="form-group">
			<button type="submit" class="btn btn-primary">Save</button>
			<button @onclick="@Cancel" class="btn btn-secondary">Cancel</button>
		</div>				
	</EditForm>
}



@code {

	[CascadingParameter] public IModalService BlazoredModalService { get; set; }

	[CascadingParameter] private Task<AuthenticationState> authenticationStateTask { get; set; }

	[CascadingParameter] ModalParameters ModalParameters { get; set; }

	private List<CategoryFieldDefinition> categoryfielddefinitionList;

	InboxFileToArchive inboxfiletoarchive = new InboxFileToArchive();

	private bool blnCancelClicked = false;

	protected override async Task OnInitializedAsync()
	{
		await GetInboxFile();
	}

	protected async Task GetInboxFile()
	{
		var user = (await authenticationStateTask).User;

		InboxFile inboxfile;

		inboxfile = await DataAccessService.GetInboxFile_Async(ModalParameters.Get<int>("InboxFileID"));

		inboxfiletoarchive.CategoryId = ModalParameters.Get<int>("CategoryID");
		inboxfiletoarchive.SubCategoryId = 0;
		inboxfiletoarchive.InboxFileId = inboxfile.InboxFileId;
		inboxfiletoarchive.Sourcefilename = inboxfile.Sourcefilename;

		categoryfielddefinitionList = await DataAccessService.GetCategoryFieldDefinitions_Async(user.Identity.Name, ModalParameters.Get<int>("CategoryID"));

		foreach (var categoryfielddefinition in categoryfielddefinitionList)
		{
			inboxfiletoarchive.ArchiveInboxFileFieldValues.Add(new InboxFileToArchiveFieldValue { CategoryFieldDefinitionId = categoryfielddefinition.CategoryFieldDefinitionId, CategoryFieldName = categoryfielddefinition.CategoryFieldName, IsRequired = categoryfielddefinition.IsRequired });
		}

		await DataAccessService.GetInboxesSubCategories_Async(ModalParameters.Get<int>("CategoryID"));

		if (DataAccessService.lstInboxes_SubCategories.Count == 1)
		{
			inboxfiletoarchive.SubCategoryId = DataAccessService.lstInboxes_SubCategories.First().SubCategoryId;
		}
	}

	protected async void Submit()
	{
		if (!blnCancelClicked)
		{
			int updateresult = 0;

			updateresult = await DataAccessService.UpdateInboxFile(inboxfiletoarchive);

			BlazoredModalService.Close(ModalResult.Ok<int>(updateresult));			
		}
	}

	protected void Cancel()
	{
		blnCancelClicked = true;
		BlazoredModalService.Cancel();
	}





`

**Comment by chewabledrapery** [comment]
Hi @larsk2009 

Thanks for the reply, much appreciated i hadn't noticed the new use case in the wiki examples.

I've refactored the code, removed the injection and declared a public cascading parameter for the service and i have the same problem...

See refactored code below, I figured out to use the triple backtick to insert a code block properly ;)

Many thanks.


```
@page "/ArchiveInboxFileModal"
@using DoculogIQ.Data
@using DoculogIQ.Data.Models
@using DoculogIQ.Validation

@inject AuthenticationStateProvider AuthenticationStateProvider
@inject DataAccessService DataAccessService

@inherits OwningComponentBase<DataAccessService>
@if (inboxfiletoarchive != null)
{
	<EditForm Model="@inboxfiletoarchive" OnValidSubmit="@Submit">
		<FluentValidationValidator />
		<ValidationSummary />
		<p>@inboxfiletoarchive.Sourcefilename</p>
		@if (DataAccessService.lstInboxes_SubCategories.Count > 1)
		{
			<div class="form-group row">
				<label for="selectSubCategory" class="filesearch-label">Sub Category</label>
				<select id="selectSubCategory" class="form-control" @bind="@inboxfiletoarchive.SubCategoryId">
					<option value="0">Please select...</option>
					@if (DataAccessService.lstInboxes_SubCategories != null)
					{
						@foreach (var subcategory in DataAccessService.lstInboxes_SubCategories)
						{
							<option value="@subcategory.SubCategoryId">@subcategory.SubCategoryName</option>
						}
					}
				</select>				
			</div>
		}
		@foreach (var archiveinboxfilefieldvalues in inboxfiletoarchive.ArchiveInboxFileFieldValues)
		{
			<div class="form-group row">				
				<div class="col-lg-12">
					<label for="@archiveinboxfilefieldvalues.CategoryFieldDefinitionId" class="archiveinboxfile-label">@(@archiveinboxfilefieldvalues.IsRequired == true ? @archiveinboxfilefieldvalues.CategoryFieldName + "*" : @archiveinboxfilefieldvalues.CategoryFieldName)</label>
					<InputText id="@archiveinboxfilefieldvalues.CategoryFieldDefinitionId" class="form-control" autocomplete="off" @bind-Value="@archiveinboxfilefieldvalues.FieldValue"></InputText>
				</div>
			</div>
		}
		<div class="form-group">
			<button type="submit" class="btn btn-primary">Save</button>
			<button @onclick="@Cancel" class="btn btn-secondary">Cancel</button>
		</div>				
	</EditForm>
}



@code {

	[CascadingParameter] public IModalService BlazoredModalService { get; set; }

	[CascadingParameter] private Task<AuthenticationState> authenticationStateTask { get; set; }

	[CascadingParameter] ModalParameters ModalParameters { get; set; }

	private List<CategoryFieldDefinition> categoryfielddefinitionList;

	InboxFileToArchive inboxfiletoarchive = new InboxFileToArchive();

	private bool blnCancelClicked = false;

	protected override async Task OnInitializedAsync()
	{
		await GetInboxFile();
	}

	protected async Task GetInboxFile()
	{
		var user = (await authenticationStateTask).User;

		InboxFile inboxfile;

		inboxfile = await DataAccessService.GetInboxFile_Async(ModalParameters.Get<int>("InboxFileID"));

		inboxfiletoarchive.CategoryId = ModalParameters.Get<int>("CategoryID");
		inboxfiletoarchive.SubCategoryId = 0;
		inboxfiletoarchive.InboxFileId = inboxfile.InboxFileId;
		inboxfiletoarchive.Sourcefilename = inboxfile.Sourcefilename;

		categoryfielddefinitionList = await DataAccessService.GetCategoryFieldDefinitions_Async(user.Identity.Name, ModalParameters.Get<int>("CategoryID"));

		foreach (var categoryfielddefinition in categoryfielddefinitionList)
		{
			inboxfiletoarchive.ArchiveInboxFileFieldValues.Add(new InboxFileToArchiveFieldValue { CategoryFieldDefinitionId = categoryfielddefinition.CategoryFieldDefinitionId, CategoryFieldName = categoryfielddefinition.CategoryFieldName, IsRequired = categoryfielddefinition.IsRequired });
		}

		await DataAccessService.GetInboxesSubCategories_Async(ModalParameters.Get<int>("CategoryID"));

		if (DataAccessService.lstInboxes_SubCategories.Count == 1)
		{
			inboxfiletoarchive.SubCategoryId = DataAccessService.lstInboxes_SubCategories.First().SubCategoryId;
		}
	}

	protected async void Submit()
	{
		if (!blnCancelClicked)
		{
			int updateresult = 0;

			updateresult = await DataAccessService.UpdateInboxFile(inboxfiletoarchive);

			BlazoredModalService.Close(ModalResult.Ok<int>(updateresult));			
		}
	}

	protected void Cancel()
	{
		blnCancelClicked = true;
		BlazoredModalService.Cancel();
	}


```

![image](https://user-images.githubusercontent.com/33089517/89192870-10ffc200-d59d-11ea-9566-0399fe1ff7e7.png)

**Comment by larsk2009** [comment]
Is what you are showing the modal itself? Also if you type `razor` after the triple back tick, it will highlight the code for you :).

**Comment by chewabledrapery** [comment]
Hi,

Yes this code is the modal itself in a separate razor file... Maybe i'm implementing it wrongly? It worked prior to the update but that in itself doesn't mean i was using it correctly in the first place :)

**Comment by larsk2009** [comment]
In that case, you should use this:

`    [CascadingParameter] BlazoredModalInstance BlazoredModal { get; set; }`

instead of the IModalService. See [this component](https://github.com/Blazored/Modal#editmovie-component) as an example.

**Comment by chewabledrapery** [comment]
Ahhhhhhhhh......

So I've basically misunderstood/not recognised the changes in use, oops.

I'll have a go and report back, hope i've not wasted anyone's time i do appreciate the effort and assumed it was something i'd missed...

Thanks!

**Comment by larsk2009** [comment]
Definitely not wasted our time @chewabledrapery. Hopefully this fixes your issue, otherwise let us know and we will figure it out together.

**Comment by chewabledrapery** [comment]
@larsk2009 Right then i've got everything working now, i also had to refactor all my ModalParameter stuff too, but you definitely set me on the right track and after re-reading the wiki properly I knew what to look out for and what to modify to get it working.

REALLY appreciate the help, closing this (non) "issue"

Dean.

**Comment by Shashanksud** [comment]
@chewabledrapery  Just curios, how did you replace the OnClose event after nuget update?
