### ISSUE TITLE
[Question] Why OnInitialized?

### ISSUE THREAD

**Issue by Halfbax** [Blazored/Modal#210]
In your examples you are using the OnInitialized method. Doesnt it make more sense to use the OnParameterSet method. The parameter might be not set in some cases.

```cs

    [CascadingParameter] BlazoredModalInstance BlazoredModal { get; set; }

    [Parameter] public int MovieId { get; set; }

    Movie Movie { get; set; }

    protected override void OnInitialized()
    {
        Movie = MovieService.Load(MovieId);
    }

    void SaveMovie()
    {
        MovieService.Save(Movie);
        BlazoredModal.Close(ModalResult.Ok<Movie>(Movie));
    }
```

**Comment by chrissainty** [comment]
The samples are just to show off the features of the modal. In most cases OnInitialized is probably fine, but it's up to the consuming developer to decide what their specific app needs.
