### ISSUE TITLE
Add aria attributes to the close (x) in the modal header

### ISSUE THREAD

**Issue by chrissainty** [Blazored/Modal#211]
Reference: https://www.w3.org/TR/WCAG20-TECHS/ARIA14.html#:~:text=The%20%27close%27%20element%20is%20implemented,accessible%20name%20to%20the%20button.&text=Working%20example%3A%20Close%20button%20example.

To help with accessibility, we need to add an aria attribute to the x in the modal header as per the link above. We should also reenable the `tabindex` so the x can be tabbed into. This was removed and shouldn't have been, in hindsight.

**Comment by larsk2009** [comment]
Maybe we can also implement all ARIA attributes according to [this](https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html) page? It doesn't seem like much more effort.

Reference: https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html

**Comment by chrissainty** [comment]
I think that would be really great to do that.

**Comment by larsk2009** [comment]
Alright, I can pick this up if you want?

**Comment by chrissainty** [comment]
That would be great. Might be worth checking if there is someway to validation the use of the aria attributes in some way? I've seen people say they can be easy to get wrong at time. Don't know how true that is.
