### ISSUE TITLE
[Bug] Form freezes if you open a modal window with actions and then go back in the browser

### ISSUE THREAD

**Issue by GisliSig** [Blazored/Modal#212]
If you open up a modal window with result associated with it then go back in the browser either by clicking the back button in the browser or go back using a mouse button, everything freezes up and you cannot navigate or interact with anything

Steps to reproduce the behaviour:
1. Startup the WASM sample
2. Navigate to Styling
3. Click on Show Modal
4. Without closing the modal, go back by pressing the back button

Expected:
The modal should close, and you should navigate to the Home screen, and should be able to navigate to any page

Reality:
The modal closes, you navigate to the Home screen, but you can not click on any navigation links or the Show Modal button on the Home screen

Hosting models that have this behaviour
 - Blazor Server
 - Blazor WebAssembly

Additional Context:
This does not affect every page, only pages that have a modal window that has a result associated with it (Custom Layout page does not show this behaviour).

**Comment by GisliSig** [comment]
I cloned the repo and looked into it, and I see that in the BlazoredModal there is a subscription to the LocationChanged event which calls the method CancelModals.
It dismisses all the Modals and then clears them, but it doesn't invoke the BlazoredModal.deactivateFocusTrap javascript function.

I added it and it fixes the error.

@chrissainty want me to create a PR with my proposed fix?

**Comment by chrissainty** [comment]
@GisliSig Thanks for raising this issue. Yes, it would be great if you could create a PR
