### ISSUE TITLE
Modal is not showing up

### ISSUE THREAD

**Issue by robertsundstrom** [Blazored/Modal#215]
I updated from an older version by adding the CascadingBlazoredModal but the modal does not appear. The overlay is there but not the modal. It seems like it is not positioned correctly.

I go and toggle the ```position: fixed;``` in the ```.blazored-modal-container```selector and it shows up.

What am I doing wrong?

**Comment by chrissainty** [comment]
Have you removed the old `<BlazoredModal />` component reference in the `MainLayout`?

**Comment by robertsundstrom** [comment]
@chrissainty Yes, I have.

**Comment by chrissainty** [comment]
Then the other usual suspect is caching. Have you tried clearing your browser cache and/or trying the app in a private/incognito window?

If all of that doesn't yield any improvements then could you share your code so we can help diagnose.

**Comment by robertsundstrom** [comment]
Here's my code:

I have added the service, of course.

App.razor:
```razor
<CascadingBlazoredModal>
    <CascadingAuthenticationState>
        <Router AppAssembly="@typeof(Program).Assembly">
            <Found Context="routeData">
                <CascadingValue Value="routeData">
                    <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)">
                        <NotAuthorized>
                            <RedirectToLogin />
                        </NotAuthorized>
                    </AuthorizeRouteView>
                </CascadingValue>
            </Found>
            <NotFound>
                <LayoutView Layout="@typeof(MainLayout)">
                    <h1>Obs!</h1>
                    <p>Finns inget p? denna sida.</p>
                    <div style="margin-bottom: 300px"></div>
                </LayoutView>
            </NotFound>
        </Router>
    </CascadingAuthenticationState>
</CascadingBlazoredModal>
```

MainLayout.razor:
```razor
@inherits LayoutComponentBase
<SmartButton IsVisible="false" />

<IntegrityNotice @ref="integrityNotice" OnDismissed="OnDismissed" />

<TopBar />

<TopBarLogo />

<NavBar />

<section class="container flex-grow-1">
    @Body
</section>

<Footer />
```

**Comment by robertsundstrom** [comment]
The rendered structure:
![Screenshot 2020-08-07 at 14 26 53](https://user-images.githubusercontent.com/919580/89645452-1a996a80-d8ba-11ea-80c3-8bf4deb979e2.png)

**Comment by chrissainty** [comment]
Thanks for the code but have you checked you cache? That is the cause of the majority of these problems.

I would also suggest swapping the CascadingBlazoredModal and the CascadingAuthenticationState around otherwise you won't be able to do any authentication operations inside of modals.

**Comment by robertsundstrom** [comment]
I guess my problem is with the CSS.
