### ISSUE TITLE
Modal Window seems to be disabling click event of a select? [Bug]

### ISSUE THREAD

**Issue by chewabledrapery** [Blazored/Modal#217]
Hi,

This is a tricky one, I can't work out if the issue lies with Blazored Modal or the Syncfusion PdfViewerServer component that i'm using.

If I embed the syncfusion pdf viewer in a modal it disables the zoom dropdown list click events, you can edit the zoom level with keyboard and use the plus + and minus - buttons, but click of an item in the zoom dropdown does not work, the event doesn't fire.

The syncfusion pdfviewerserver component works when not used in a modal, I've attached a screenshot with my comments in red with red arrows in case someone can see something obvious, but I cannot work out what attributes may be getting disabled or set to readonly in error...

Apologies is this isn't the correct forum I have contacted SyncFusion too.

Hosting Model - Blazor Server

Thanks, Dean

![syncfusionpdfviewerserver](https://user-images.githubusercontent.com/33089517/90417861-38ca4c00-e0ac-11ea-9004-d84b20642c0a.png)

**Comment by chrissainty** [comment]
That does sound odd. I don't know what we'd be doing in the modal that would cause this behaviour. It would be great to know what Syncfusion come back with as I don't think there will be much we can do without some more information.

**Comment by chewabledrapery** [comment]
Thanks for the reply @chrissainty I'll let you know if/when i get a reply from SyncFusion or have a eureka moment.

Many thanks, Dean

**Comment by chewabledrapery** [comment]
Hi,

I've created a sample project that I've sent to SyncFusion, I'm adding it here in case anyone has the inclination to take a look?

Issue can be demonstrated via the button on the index page with description **"Show PDFViewerServer Modal"**

[BlazorServer.zip](https://github.com/Blazored/Modal/files/5097444/BlazorServer.zip)

You'll notice that the click of the zoom level dropdown doesn't trigger, whereas typing a zoom value or clicking plus/minus icons does...

Many thanks,

Dean

**Comment by chewabledrapery** [comment]
**Update:** SyncFusion have been able to reproduce my issue and are looking into it, they've given me a target date of the 25/8/20 to get back to me with further analysis of the problem...

Many thanks,

Dean

**Comment by chewabledrapery** [comment]
Hi, just an update, i'm still waiting for a detailed reponse/fix from SyncFusion, they've now given me the 28th as target for a response.

Cheers.

**Comment by chewabledrapery** [comment]
Hi,

I've had a reply from SyncFusion, apprently its to do with the "stopImmediatePropagation" event being disabled?

Link to their response here :- https://www.syncfusion.com/support/directtrac/incidents/289951

They also state that this is the same cause as issue 224 :- https://github.com/Blazored/Modal/issues/224

I see that a change has been suggested in issue 224 shall i now close this issue?

Thanks,

Dean.

**Comment by chrissainty** [comment]
Thanks for the update Dean. I'll tag this issue in the PR for the fix and it will close automatically when it's merged.
