### ISSUE TITLE
Option to support scrollable content for modals with a lot of content

### ISSUE THREAD

**Issue by lukepat** [Blazored/Modal#220]
When the content of the modal exceeds the viewport it can make the modal hard to scroll or even close.

Ability to add option to enable content to be scrollable (like bootstrap) would be handy.

I have done the code and can create a pull request with the change if liked.

**Comment by chrissainty** [comment]
Hi @lukepat,

I'd be happy to take a look at your proposal if you want to raise a PR, I'm not exactly sure of the problem so it would be useful to see the fix.

**Comment by andregeuze** [comment]
Any progress on this? Currently running into the same problem :(

**Comment by larsk2009** [comment]
@andregeuze This was fixed in #222, but hasn't been released just yet. For now, you can use the pre-release package, found [here](https://github.com/Blazored/Modal/packages/288921), which hopefully should fix your problem. Let me know!
