### ISSUE TITLE
Allow custom class for overlay

### ISSUE THREAD

**Issue by TravisNorwood** [Blazored/Modal#223]
I'd like the change the transparency of the overlay. This could be done by adding an option to change the class of the overlay.

**Comment by chrissainty** [comment]
Could you not just override the existing class and change that style property?

**Comment by TravisNorwood** [comment]
That would change it every time the modal is used. I need to have different transparency levels.

On Aug 28, 2020, at 00:39, Chris Sainty <notifications@github.com> wrote:

﻿

Could you not just override the existing class and change that style property?

**Comment by chrissainty** [comment]
You need different transparency level every thing you open the modal?

**Comment by taylorchasewhite** [comment]
I overall agree with Chris that it seems odd to have an inconsistent overlay transparency level. What are you trying to communicate with the transparency level?

For what its worth though Chris--I personally don't like having to couple my CSS styles with those of open source components if possible, so I _do_ support being able to do the same type of "class override" you allowed with the modal popup itself.

I'd be willing to add this enhancement and submit a pull request if you are open to it.

Thanks!

**Comment by taylorchasewhite** [comment]
The other use case I have in mind that would be cool to do in a separate pull request / issue, but want to get your thoughts is doing something like a [popover](https://getbootstrap.com/docs/4.0/components/popovers/)? 

Is that something you'd be open to doing in this package as a "ModalOption" "IsPopover" or something like that? The triangle would jut against the button that launched it. I know that adds a fair amount of DOM complexity, so just thinking I'd bring it up to hear your thoughts.

**Comment by chrissainty** [comment]
> The other use case I have in mind that would be cool to do in a separate pull request / issue, but want to get your thoughts is doing something like a [popover](https://getbootstrap.com/docs/4.0/components/popovers/)?
> 
> Is that something you'd be open to doing in this package as a "ModalOption" "IsPopover" or something like that? The triangle would jut against the button that launched it. I know that adds a fair amount of DOM complexity, so just thinking I'd bring it up to hear your thoughts.

It's a nice idea @taylorchasewhite I'm not sure it would fit in this library though. While popovers and modals are similar I think we'd be blurring the lines a bit to much.

**Comment by taylorchasewhite** [comment]
> It's a nice idea @taylorchasewhite I'm not sure it would fit in this library though. While popovers and modals are similar I think we'd be blurring the lines a bit to much.

I agree, that makes sense. I would like to contribute more to the Blazored components you've been adding and would be interested in creating an equivalent package (based on Modal) under the Blazored/Popover, would that be something you'd be open to or would you prefer sole responsibility of all the repositories/packages in Blazored/ :)?

**Comment by chrissainty** [comment]
@taylorchasewhite I'd be more than happy for you to do that. If you could head over to the [Home repo](https://github.com/Blazored/Home) and open an issue describing the package you want to add we can chat it over there an not pollute this issue with random chat 🙂
