### ISSUE TITLE
Not capturing clicks || GoogleMaps AutoComplete 

### ISSUE THREAD

**Issue by rezasfl** [Blazored/Modal#224]
Hello Chris,

Using Server Side, we have been trying to embed an instance of GoogleMaps' Places AutoComplete (Using BlazorGoogleMaps) with Blazored.Modal. The issue we faced was that the only way to select a result from the AutoComplete, would be to use the Up and Down Arrow keys to highlight an item and then press the Enter key to select it. You couldn't click on a list item directly. Every other button on the modal page works. 

We're not sure, but it appears to be the same problem in #217.

The simplest way to reproduce this:

1. We cloned Blazored.Modal and installed BlazorGoogleMaps NuGet package on Samples/BlazorServer.
2. Inside _Host.cshtml, within the `head` we added:
```
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE&v=3&libraries=places"></script>
```
and inside `body` we added:
```
<script src="_content/BlazorGoogleMaps/objectManager.js"></script>
```

3. Replace the contents of `Confirm.razor` with:
```
@using GoogleMapsComponents.Maps.Places;

@inject IJSRuntime JsRuntime

<div>
    @*<p>Please click one of the buttons below to close or cancel the modal.</p>*@

    <input type="text" @ref="_searchBoxRef" />

    <button @onclick="Close" class="btn btn-primary">Close</button>
    <button @onclick="Cancel" class="btn btn-secondary">Cancel</button>
</div>

@code {
    private ElementReference _searchBoxRef;

    [CascadingParameter] BlazoredModalInstance BlazoredModal { get; set; }

    void Close() => BlazoredModal.Close(ModalResult.Ok(true));
    void Cancel() => BlazoredModal.Cancel();

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        await Autocomplete.CreateAsync(JsRuntime, _searchBoxRef);
    }
}
```
4. Run the application and click and on the Home page, click on Show Modal. You should get something like this:

![2](https://user-images.githubusercontent.com/24213094/91778879-042bc800-ec48-11ea-88ea-2c263787e4cf.JPG)

5. Type in a location and try to click on a location. You will see that it highlights, but you are not able to select a location. Here the red dot is where i clicked and yet location was not selected.

![5](https://user-images.githubusercontent.com/24213094/91779974-8ddc9500-ec4a-11ea-8ebc-b6066aab1e44.png)

### Solution
In Focus-Trap's documentation, there is a setting called "allowOutsideClick" which: "If set and is or returns true, a click outside the focus trap will not be prevented, even when clickOutsideDeactivates is false". 

So after cloning Blazored.Modal, we found that in `blazored.modal.ts` file on line 10 where you define the options inside the constructor:
```
export class BlazoredModal {

    readonly _options: Options = { escapeDeactivates: false };
.
.
.
```

Simply adding ```, allowOutsideClick: true ``` will allow the outside clicks to be captured. 
The final constructor looks like this:
```

export class BlazoredModal {

    readonly _options: Options = { escapeDeactivates: false, allowOutsideClick: true };
.
.
.
```

We don't think this will cause any problems for users that don't have `UseCustomLayout` set to true as the `blazored-modal-overlay` div will stop any background clicking.

However, for anyone providing their own custom layout, focus-trap will no longer stop background clicking. Not sure how you might want to deal with that.

**Comment by SevvandhiN** [comment]
I am also encountering the same issue in ComboBox and DropDownList component. Any solution would be helpful.

**Comment by chrissainty** [comment]
Thank you so much @rezasfl for the detailed information. I'd be happy to accept this change, would you like to raise a PR for it?

**Comment by rezasfl** [comment]
No worries, I just raised a PR for it. I'll close this issue when the PR gets accepted :)
