### ISSUE TITLE
[Bug] 5.0.3 Throws InvalidaOperationException

### ISSUE THREAD

**Issue by dfkeenan** [Blazored/Modal#230]
**Describe the bug**
After updating from 5.0.2 to 5.0.3 I started getting `System.InvalidOperationException: Collection was modified; enumeration operation may not execute.` Happens in the `Blazored.Modal.BlazoredModal.CancelModals` method.

**To Reproduce**

**Expected behavior**
Not throw exception

**Screenshots**

**Hosting Model (is this issue happening with a certain hosting model?):**
I am currently using 
 - Blazor WebAssembly

**Additional context**
I am using the `CEC.Routing` package to prevent users from navigating with unsaved changes. The modal is being shown upon navigation.

**Comment by Enfis** [comment]
Same here,

Here a await Task.Yield (); just after the Modal await, probably await dialog.Result, (temporary) solves the problem.

**Comment by larsk2009** [comment]
Could you provide some clear steps to reproduce this issue, or a repo showing this problem?

**Comment by Enfis** [comment]
This is the simplest project using default Blazor wasm template, hope this help, just press "TEst Modal" button.

[TestModal.zip](https://github.com/Blazored/Modal/files/5187826/TestModal.zip)

**Comment by larsk2009** [comment]
Ah Right, I may be getting what is going wrong. I will try some stuff to see if I can fix it.

**Comment by larsk2009** [comment]
I can reproduce it in the sample project as well. I might have a fix for it, so I will make a PR so we can all review it.
