### ISSUE TITLE
[Bug] Unable to close modal when modal is empty

### ISSUE THREAD

**Issue by ronfur** [Blazored/Modal#236]
**Describe the bug**
Unable to close modal when modal is empty (No html)
Same problem when modal only contains a list of a-tags generated by a for each.
The modal works when I add a button in the modal.

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Comment by larsk2009** [comment]
Can you provide a project which reproduces this error? I just tried with a modal with no contents, but it works fine on my machine.

**Comment by ronfur** [comment]
In my project modal A opens modal B and the problem occurs with modal B.

The problem only occurs with sub modals.

________________________________
Från: Lars Koopmans <notifications@github.com>
Skickat: den 12 september 2020 20:32
Till: Blazored/Modal <Modal@noreply.github.com>
Kopia: ronfur <ronfur@live.se>; Author <author@noreply.github.com>
Ämne: Re: [Blazored/Modal] [Bug] Unable to close modal when modal is empty (#236)


Can you provide a project which reproduces this error? I just tried with a modal with no contents, but it works fine on my machine.

**Comment by larsk2009** [comment]
Right, so the bug only happens with submodals. In that case, I can reproduce this error. I will see if I can find the problem.

**Comment by larsk2009** [comment]
Seems this issue is related to #217 and #224. Once PR #226 is merged, I think this issue will be fixed.
