### ISSUE TITLE
Demo project broken

### ISSUE THREAD

**Issue by scott-david-walker** [Blazored/Modal#241]
Trying to open a modal in the demo project causes this error:

![image](https://user-images.githubusercontent.com/13588473/96174133-2728e780-0f29-11eb-990d-3420805dfe81.png)

**Comment by larsk2009** [comment]
Which browser are you using?

**Comment by scott-david-walker** [comment]
Happens both in Edge and Chrome

**Comment by larsk2009** [comment]
If you look at the developer console in chrome, do you see the 'blazored.modal.js' like in this window:

![image](https://user-images.githubusercontent.com/7924568/96175066-9eab4680-0f2a-11eb-9b4e-959d3d5648a0.png)

**Comment by scott-david-walker** [comment]
There's no js files in the console . . .

![image](https://user-images.githubusercontent.com/13588473/96175354-111c2680-0f2b-11eb-88bf-f3a8db979634.png)

**Comment by larsk2009** [comment]
If you are using the demo project without changing anything and this is happening, it is probably a caching issue. You could try clearing the browser cache and/or using a private window.

**Comment by scott-david-walker** [comment]
Nothing changed, it's a fresh clone of the repo.
Tried on incognito, even downloaded Firefox and I'm still having the same error.

**Comment by larsk2009** [comment]
Do you have the blazored.modal.js file in VS?

![image](https://user-images.githubusercontent.com/7924568/96176794-22663280-0f2d-11eb-8c50-dc817554f4d6.png)

**Comment by scott-david-walker** [comment]
I'm using Rider but yes, the Blazored.Modal project exists and is referenced

**Comment by larsk2009** [comment]
Does the 'blazored.modal.js' file also exist, on the location I showed in the image?

**Comment by scott-david-walker** [comment]
Just tried running it on Visual Studio and it works perfectly. It doesn't seem to work using the Rider IDE.

**Comment by larsk2009** [comment]
I suspect Rider is not compiling the TypeSript to Javescript for some reason.

**Comment by scott-david-walker** [comment]
That would be unusual, I use RIder for everything as I don't really like VS and I've never had any issues writing TypeScript. Is it worth raising a bug?

**Comment by chrissainty** [comment]
Hi @scott-david-walker, we use MSBuild tasks in the csproj to compile the TypeScript. It could be that Rider doesn't support them. You could also try building the sample project with the .NET CLI, if that also works, I would suggest it's either Rider or a local issue.

**Comment by chrissainty** [comment]
As there has been no further communication on this issue I'm going to close it.
