### ISSUE TITLE
Question about usage and credit

### ISSUE THREAD

**Issue by Garderoben** [Blazored/Modal#242]
Hello Chris

I have learned alot from your repos and examples since i started learning blazor, i'm not a "real" developer but i started my own private library that in the end turned out to go public instead and is now a open source team project licensed under MIT. 

Our Dialog component is mostly based on your modal source code, but redone and changed in ways to fit our needs.

You are already credited in our project [MudBlazor,](https://mudblazor.com/) but we are reworking it and firstly want to ask everyone for permission, and secondly we would like to link to your profile/github repo on our credit page if its okay with you.

Thanks in advance!

**Comment by chrissainty** [comment]
Hi @Garderoben,

Thank you for asking, that is a very nice thing to do. You have my permission to use the modified Blazored Modal source code in your project, with credit. I've just had a look over your project and it looks really great, I wish you luck with it.
