### ISSUE TITLE
Why Ok(T result) don't pass the typeof T for resultType in ModalResult constructor

### ISSUE THREAD

**Issue by VGib** [Blazored/Modal#244]
Hello,

**Is your feature request related to a problem? Please describe.**
the constructor has this signature:
```csharp
      protected ModalResult(object data, Type resultType, bool cancelled)
        {
            Data = data;
            DataType = resultType;
            Cancelled = cancelled;
        }
```

But it seems to be filled with the modalType:
```csharp
        public static ModalResult Ok<T>(T result) => Ok(result, default);

        public static ModalResult Ok<T>(T result, Type modalType) => new ModalResult(result, modalType, false);
```
**Describe the solution you'd like**
I don't understand what is the resulttype purpose:
- the type of the data object ?
- the type of the used modal ?

I I don't understand well, could this be better named ?

**Describe alternatives you've considered**
If this is the result type, can we have:
```csharp
        public static ModalResult Ok<T>(T result) => Ok(result, typeof(T));
```

**Additional context**
Any way great work and great project.

**Comment by VGib** [comment]
OK I didn't think that you used javascript for result, I understand better. 
Can you put a comment on DataType and a custom where close on T, every thing will be better.
Thx

**Comment by chrissainty** [comment]
Hi @VGib,

I've been trawling the issues trying to find a reason for this. I'm sure there was one but for the life of me I can't find it now. While this is possible not optimal it's not something that will be changed without a decent benefit as developers could be relying on this now.

I'm going to close this as a won't fix but this can be re-opened if needed.
