### ISSUE TITLE
[Feature Request] Remove inline styles

### ISSUE THREAD

**Issue by RMarcinkowski** [Blazored/Modal#249]
**Describe the bug**
Firstly, we have a Content Security Policy directive that forbids inline style.
![grafik](https://user-images.githubusercontent.com/32728206/97860399-59e12700-1d02-11eb-9a0f-67b951299414.png)

[There](https://github.com/Blazored/Modal/blob/main/src/Blazored.Modal/Interop/Blazored.Modal.ts) are functions implemented in #186 that set inline style on the `body` element. Therefore we receive several error message like this:
![grafik](https://user-images.githubusercontent.com/32728206/97860521-92810080-1d02-11eb-9a28-ca5e366c6dc3.png)

Setting some hashes or nonce won't solve our problem, because of the way the properties get set.

Secondly, why are those styles applied to the `body` element anyway? We have a navigation bar and a footer, so the scroll bar in our page is attached to the `main` element and window.scrollTo() does not work as well.

**To Reproduce**
1. Use Conent Security Policy that forbids inline style.
2. Open a BlazoredModal dialog.
3. Inspect console in any browser.

**Expected behavior**
It would be nice if there weren't any inline styles used.

**Comment by chrissainty** [comment]
Hi @RMarcinkowski, those styles are applied as part of the focus trap library we use. I've not had anyone use a security policy which restricts inline styles before, I'll be honest I had to look up why it was a security risk in the first place. 

Time is extremely tight for me at the moment and unless lots of other people upvote this I don't think anything will be being action on this issue in the near future. I just want to set expectations.

**Comment by larsk2009** [comment]
@chrissainty @RMarcinkowski I have some time for this so I will look into it if that is okay. Might take a bit though.

**Comment by chrissainty** [comment]
@larsk2009 That would be awesome, thank you.

**Comment by RMarcinkowski** [comment]
@chrissainty Thank your for your answer and the explanation.
@larsk2009 I would appreciate that, thanks.

**Comment by larsk2009** [comment]
Sorry that it has been a while. I had a proper look at this, but it seemed difficult to fix properly from my experience. The problem is we are setting some inline styles for things like animations. I didn't find a very good/clean way to still allow animations (with custom durations) without using inline styles. If anyone has any idea about that I would be glad to now, but otherwise I think this is going to be difficult.

**Comment by chrissainty** [comment]
I've also spent some time looking into this and I agree with @larsk2009 findings. This is just going to cause to many headaches and it seems like a edge case at this point in time. I'm going to close this as a won't fix but we can always revisit it if it becomes a more requested change.
