### ISSUE TITLE
Feature Request: Add FluentApi

### ISSUE THREAD

**Issue by AmarjeetBanwait** [Blazored/Modal#25]
It will be nice if the plugin will have fluent apis
eg.

```
ModalService
       .AddTitle("Modal Title")
       .AddBody("Modal Body")     //string or typeOf ComponentBase
       .AddFooter("Modal Footer")
       .ShowCloseIcon(true)
       .CloseIconTemplate("<i class='fa fa-close'/>")
       .OnClose("EventCallback Here")
       .Show()
```

we can add many options like
```
Header Class
Header Template
Footer Class
Footer Template etc.
```

**Comment by natsuo** [comment]
A fluent interface / API would be nice, especially if more features are added (as seen in #44).

As for the example above. Are you looking to just customize the style of the modal, or make reusable modal templates (large modal, message box, error message, user information window)?

You could make a razor component with the design you want, then use the `ModalParameters` to fill the `RenderFragment` and any of the other necessary bindings you need. Then you'd have reusable modal templates. It wouldn't be the most elegant thing in the world, but it would work.

**Comment by chrissainty** [comment]
I think with the changes we have made since this issues was opened, I'm not sure having a fluent API would be a good option anymore. I'm going to close this issue for now and if it is something people really want then we can take another look at it in the future.
