### ISSUE TITLE
Hides JSInterop Drop-Down

### ISSUE THREAD

**Issue by jkears** [Blazored/Modal#250]
In Blazor server while attempting to include CodeEffects Rules Editor within a Blazored Modal and when I select the CodeEffects Rules Editor drop-down it renders underneath the modal.  
  
![image](https://user-images.githubusercontent.com/1290937/97912848-68880800-1d1b-11eb-981d-80390fd7f9da.png)

When this is not wrapped in a Blazored Modal based component this works.   

Can I control the z-index of Blazored Modal if this is the reason why the CodeEffects Rules Editor is showing up under the dialog view.

**Comment by chrissainty** [comment]
Yes, you can modify the z-index by overriding .blazored-modal-overlay and .blazored-modal and changing their z-index to a different number.

**Comment by jkears** [comment]
Many thanks Chris...

I actually had to change the z-index of the ceMenu class on CodeEffects = 200 works for my needs.  

![image](https://user-images.githubusercontent.com/1290937/97921015-519be280-1d28-11eb-8eb0-bc4622f6c0c4.png)
