### ISSUE TITLE
Have to click close twice

### ISSUE THREAD

**Issue by RobBowman** [Blazored/Modal#252]
Thanks for creating this project. I'm new to Blazor, need a modal box and this is easy to use!

My problem is, on displaying the modal, the user has to click to close twice.

![CloseTwice](https://user-images.githubusercontent.com/6296919/98570541-77d2fc80-22ab-11eb-9bb8-ba4f06b854c2.gif)

On my razor page, I have a "ReQueue" mthod bound to a button click:

```
protected void ReQueue()
        {
            var parameters = new ModalParameters();
            parameters.Add(nameof(selectedRowId), selectedRowId);

            Modal.Show<ModalReQueue>("Confirmation Required", parameters);
        }
```
My modal razor page is:

```
@inherits ModalReQueueBase
<div class="row">
    <div class="col-md-8">
        <p>Are you sure you want to re queue for id:@selectedRowId?</p>
        <span class="@(successState==true ? "label label-success" : "label label-default")">@resultMsg</span>
    </div>

    <button @onclick="ReQueue" class="btn btn-primary">Yes</button>
    <button @onclick="Close" class="btn btn-secondary">Close</button>
</div>
```
and the code behind for this is:

```
public class ModalReQueueBase : ComponentBase
    {
        [CascadingParameter] public IModalService Modal { get; set; }

        [Parameter] public string selectedRowId { get; set; }

        [Inject]
        public IBamDataService BamDataService { get; set; }

        protected string resultMsg;
        protected bool successState;
    
        protected async Task ReQueue()
        {
            bool result = await BamDataService.RequeueActivation(selectedRowId);
            if (result)
            {
                resultMsg = "Success!";
                successState = true;
            }
            else
            {
                resultMsg = $"Failue. Response msg:{BamDataService.ErrorMessage}";
                successState = false;
            }
        
            this.StateHasChanged();

        }
```
At the foot of the MainLaylout.razor page I have `<BlazoredModal />`

My _hots.cshtml file contains a link to the css and javascript files:

`<link href="_content/Blazored.Modal/blazored-modal.css" rel="stylesheet" />`
`<script src="_content/Blazored.Modal/blazored.modal.js"></script>`

Can anyone see where I went wrong?

**Comment by larsk2009** [comment]
Going of of your GIF, it seems the modal is opened twice, which is why you need to close it twice. Could you also post the full contents of MainLayout.razor?

**Comment by chrissainty** [comment]
It looks like you've not made some changes required by the latest version. If you have a run through of the readme you can see what needs doing. But essentially, you need to remove the `<BlazoredModel />` component from `MainLayout` and add `<CascadingBlazoredModal>` around the router component. You then no longer inject `IModalService`, instead you access it via a cascading value in each component: `[CascadingParameter] public IModalService Modal { get; set; }`.

As I said, the sample projects and readme show all of this if the above is unclear.

**Comment by RobBowman** [comment]
@chrissainty that worked great, thanks very much
