### ISSUE TITLE
Use as MessageBox

### ISSUE THREAD

**Issue by duetscha** [Blazored/Modal#253]
First of all: Great work, I really like all your Blazored "Tools" :)

One thing I´m missing (or just haven´t found yet) is a kind of "MessageBox" with different types (icons) like INFO, QUESTION, WARNING... and a set of buttons to display (like Yes/No/OK/Cancel)
I´ve seen something similar here at Github "LiquidTechnologies/blazor-modal-dialog" but I don´t feel comfortable using to many packages but rather have on package covering all :)

Did I miss something or is there an easy way without creating my own message.razor to display?

Thanks,

Andre

**Comment by larsk2009** [comment]
Hi Andre,

There isn't a prebuilt `MessageBox` Modal with icons. This is however, something you could implement yourself using this package. Basically, I think you should make your own `message.razor` component. You can hide the default header, and add your own header with the icon you want.

Also take a loot at #198. It seems like this issue shows an example of what you are trying to achieve. Also #133 gives more insight into why this has not been implemented in Blazored.Modal.

**Comment by duetscha** [comment]
Hi Lars, 
thanks for your answer. I already assumed something like this - but since I´m a lazy one ... :)
Stay healthy
Andre

**Comment by chrissainty** [comment]
Based on the above discussion I'm going to close this issue as this is a road we've decided not to go down.
