### ISSUE TITLE
Integrate Modal with Grid.Blazor

### ISSUE THREAD

**Issue by brentgiesler** [Blazored/Modal#254]
**Is your feature request related to a problem? Please describe.**
I've been unable to show the modal from inside his grid, by creating a custom column
[https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Custom_columns.md](https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Custom_columns.md)

**Describe the solution you'd like**
I'd like to create a hyperlink that will open the modal with the details of my record, in the selected row

**Describe alternatives you've considered**
I've considered using an "old-fashioned" JS modal, but prefer to use you component

**Additional context**
![image](https://user-images.githubusercontent.com/10464889/98739404-e7f68680-236e-11eb-9db3-bff2b1f100dc.png)

I'd like to click the pencil icon and have these details inside the modal

![image](https://user-images.githubusercontent.com/10464889/98739533-255b1400-236f-11eb-95ab-f95db0b59427.png)

**Comment by larsk2009** [comment]
I am not entirely sure what exact code you are trying now, but it seems like you should make a button in the custom column, which on its click event will open the modal. That should work I think. Can you try that?

**Comment by brentgiesler** [comment]
Hi Lars.  Thanks for commenting.

I've been trying that, but haven't been able to have the grid even render, when I have the call to the code that sets up the modal.  I do have a separate button outside the grid, which calls the modal just fine.

I pinged Chris to see if he had anyone that had implemented these two components together.  He asked me to open an issue so he could investigate.

**Comment by larsk2009** [comment]
Are you able to share the code for this issue? That way Chris, me or someone else can easily replicate your issue and try and fix it.

**Comment by larsk2009** [comment]
@brentgiesler I have just made a fork of Grid.Blazor, and I could add a simple modal to it which works. Maybe you can have a look at what I did and see if that is what you were trying to do?

Check out [this commit](https://github.com/larsk2009/Grid.Blazor/commit/5526150a5b74b4923d8366c6c503445bea398780) to see what I did. You can clone that repo and try for your self. To try it, go to the **Edit rows** page and click on the **edit** button on a row. This should open a modal like in the image below:

![image](https://user-images.githubusercontent.com/7924568/98834799-e9dc4a80-243f-11eb-97f4-49bc00507243.png)

**Comment by brentgiesler** [comment]
Wow Lars.  Thank you very much.

I'll check it out and let you now how I end up.

**Comment by brentgiesler** [comment]
@larsk2009 It worked great.  I saw some of the things I missed.  Thanks for the education.
