### ISSUE TITLE
[Feature Request] .NET 5

### ISSUE THREAD

**Issue by larsk2009** [Blazored/Modal#255]
Now that .NET 5 is released, I guess we should upgrade to .NET5. The changes required are very small, so if you want I can make a PR for it.

**Comment by chrissainty** [comment]
Sorry this took so long to get to. Yes, I agree. 

We will need to dual target .NET5 and .NetStandard2.1, I believe. This will give everyone some time to migrate.

I'm not sure what happens regarding features like scoped CSS if the package is installed in an older version of Blazor. I've not had a chance to test this yet.

**Comment by larsk2009** [comment]
I don't have much experience with multi-targeting, but it seems like we would need to include some #IF statements in the .csproj to use the correct versions of the Nuget packages for both .net5.0 and .netstandard2.1

I will try to have a go at it maybe next week, but it doesn't seem very easy (at least nog as easy as just updating to .net5.0, which I could accomplish very easily, but I can see why we would want to multi-target to also .netstandard2.1).

**Comment by larsk2009** [comment]
I have had a look at this, but it seems like it is a better idea to either stay at netstandard for a while, or to move to .net5. If we multitarget we need to support both versions and also make sure the nuget dependencies are correct for each version as far I can see. My preference would be to move to .net5.0 with the next major release and drop .netstandard entirely.

**Comment by chrissainty** [comment]
As .NET 5 isn't a LTS version perhaps we should stick with NET Standard for now and then move to .NET 6 in November. The only thing I think we'd potentially use from  .NET 5 is scoped CSS and JS modules and it doesn't seem worth the hassle right now to dual target just for those.

I'll close this issue and we can check out .NET 6.
