### ISSUE TITLE
[Bug] Respect GlobalModalOptions

### ISSUE THREAD

**Issue by larsk2009** [Blazored/Modal#256]
**Describe the bug**
Some options don't seem to use/respect the `GlobalModalOptions`. For example, the Animation doesn't in [this file](https://github.com/Blazored/Modal/blame/main/src/Blazored.Modal/BlazoredModalInstance.razor.cs#L93) (it only uses the one set in `Options`, doesn't check `GlobalModalOptions`.) The option `FocusFirstElement` also seems to forget this, for example in [this line](https://github.com/Blazored/Modal/blame/main/src/Blazored.Modal/BlazoredModalInstance.razor.cs#L55).

**To Reproduce**
Most likely can be reproduced by using the `GlobalModalOptions`

**Expected behavior**
Use/resport `GlobalModalOptions`

**Screenshots**
Not applicable

**Hosting Model (is this issue happening with a certain hosting model?):**
Not applicable

**Additional context**
I want to make a PR for this in the coming days, this is as a placeholder/reminder in case I forget.

**Comment by chrissainty** [comment]
Good spot Lars. Looks like you've got this in hand. Shout if you need anything.

**Comment by David-Moreira** [comment]
Hello @larsk2009 
I added this one `FocusFirstElement`.
I just went straight to the point and I didn't notice a cascading GlobalOptions, my bad.
Thanks for noticing and fixing!! 👍

**Comment by larsk2009** [comment]
No problem! I myself also missed one when I added Animations, so you were definitely not the only one 😉
