### ISSUE TITLE
Update or Take Down Documentation on modal.blazored.com [Feature Request] 

### ISSUE THREAD

**Issue by sleeplessninja** [Blazored/Modal#257]
I had followed the steps outlined at the [separate documentation site]( https://modal.blazored.com/usage/returning-data-from-modals.html) first.  Only after running into issues trying to follow the simple samples had I come across this GitHub repo with the latest documentation. 

At the very least the documentation could explicitly say its dated and point to GitHub.

Also if you do decide to keep the separate site active.  Please put an explicit version number of the library, so at least there is a point in time indicator should they fall out of sync again. (E.g. this documentation is for Blazored.Model v5.0.1)

The documentation on this Github repo page is top notch.  Thank you for your awesome contributions!!

**Comment by chrissainty** [comment]
Thank you for raising this @sleeplessninja. This was an error on my part, we explored using DocFx but never got on with it so moved to publishing the sample app instead. I completely forgot that the site you referenced was still running. I'll get it takes down and apologies for the confusion.

**Comment by chrissainty** [comment]
The old docs site is now offline. Thanks again for raising this.
