### ISSUE TITLE
[Bug] Could not find 'BlazoredModal' in 'window'.

### ISSUE THREAD

**Issue by ryantgray** [Blazored/Modal#261]
**Describe the bug**
I have followed the steps on GitHub and to the best of my knowledge I did everything as described. I then tried doing a very basic test using the instructions as described under "Usage - Showing a modal with no parameters" in Github but when i click the button that calls Modal.Show I get the following error in developer tools in Chrome:

Microsoft.JSInterop.JSException: Could not find 'BlazoredModal' in 'window'.

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly

**Additional context**
I am using Visual Studio 2019 Community Edition. 

I am using the following Nuget packages in the Client:
Microsoft.AspNetCore.Components.WebAssembly 3.2.1
Microsoft.AspNetCore.Components.WebAssembly.Build 3.2.1
Microsoft.AspNetCore.Components.WebAssembly.DevServer 3.2.1
System.Net.Http.Json 5.0.0

I am using the following Nuget packages in the Server project:
Microsoft.AspNetCore.Components.WebAssembly.Server 3.2.1

It's possible that I did not do something in the steps correctly but as far as I know I did. Thanks.

**Comment by larsk2009** [comment]
Hi @ryantgray, please have a look at #259 to see if it fixes your issues. My comment there specifies some other issues to check out for a fix. The conclusion is that this is most of the time a caching issue.

Also in your nuget packages I don't see Blazored.Modal, but If you are getting an error in chrome then probably you are using that package also?

**Comment by ryantgray** [comment]
Hi @larsk2009, since posting my issue I had reverted all my changes and then I tried reimplementing them once I got your response. In short, it is working now and I did not do anything extra to get it to work. So, either it was a caching issue or I missed something the first time but I'm leaning more towards the caching thing. Thanks.
