### ISSUE TITLE
Rename the cascading parameter property in the readme to something less confusing

### ISSUE THREAD

**Issue by pha3z** [Blazored/Modal#263]
The readme example for EditMovie contains this line for the Cancel button:

`<button @onclick="BlazoredModal.Cancel" class="btn btn-secondary">Cancel</button>`

When I try to implement a button referencing BlazoredModal.Cancel, I receive the error:

`BlazoredModal does not contain a definition for Cancel`

- Using Blazor Server

_On an unrelated note: I notice the @bind pattern in the example code is @bind="@field".  I believe this should be @bind="field"._

**Comment by pha3z** [comment]
As a matter of fact, Intellisense shows pretty much NOTHING on BlazoredModal -- except for the standard C# class members.

**Comment by pha3z** [comment]
Woops.  I was missing

`[CascadingParameter] BlazoredModalInstance BlazoredModal { get; set; }`

Probably ought to change the property name from "BlazoredModal" to something clearer like "thisModal" since BlazoredModal is a class available in the same scope.

Honestly, this makes way more sense also.  Because I thought it was strange that I was supposed to be calling a static method to close an instance. :D

**Comment by chrissainty** [comment]
This's a fair point @pha3z. I'll repurpose this issue to track the required changes.
