### ISSUE TITLE
[Feature Request] Hide Modal Header via Boolean Property

### ISSUE THREAD

**Issue by ryantgray** [Blazored/Modal#264]
**Is your feature request related to a problem? Please describe.**
Only a slight aesthetic problem.

**Describe the solution you'd like**
Would be nice if we could hide the modal header via setting a property the same way HideCloseButton works. I assume we could accomplish the effect by supplying our own css but... who wants to do that? =)

**Describe alternatives you've considered**
I can almost accomplish the desired result by passing in an empty string for the title and haveing HideCloseButton set to true but the element still occupies space on the page.

**Additional context**

**Comment by larsk2009** [comment]
Hi @ryantgray,

Have you tried the `HideHeader` option? I think that does what you want.

**Comment by ryantgray** [comment]
I did not. I missed that option and yes, it does exactly what i was wanting. Thanks.
