### ISSUE TITLE
[Feature Request] Change generic type constraint of ModalService.Show<T> to IComponent

### ISSUE THREAD

**Issue by ChristianJNPRR** [Blazored/Modal#269]
Currently, I'm experimenting with a custom implemetation of IComponent which I use as base class instead of ComponentBase. I also use your ModalService in this experiment which requires that every component inherits from ComponentBase.

In theory it should be sufficient if the generic type constraint of Show<T> is just of IComponent instead of ComponentBase. In a quick test implementation it worked for my scenario, but I'm unsure if this would have other implications as well.

What do you think?

**Comment by larsk2009** [comment]
I can't necessarily find a reason why that can't be done, but maybe @chrissainty has some more insights there? I also tested it and it does indeed seem to work fine with `IComponent` instead of `ComponentBase`.

**Comment by chrissainty** [comment]
I agree, there doesn't seem to be any issues with making this change. There is nothing we rely on from `ComponentBase`, the check there to make sure the type to be rendered is a component, `IComponent` gives us that.
