### ISSUE TITLE
npm install" exited with code 9009 (project doesn't build)

### ISSUE THREAD

**Issue by qfyra** [Blazored/Modal#276]
Extracting project from zip and running it in Visual Studio 2019 yields

1>C:\Users\__________\Desktop\Modal-main\src\Blazored.Modal\Blazored.Modal.csproj(35,5): error MSB3073: The command "npm install" exited with code 9009.
1>Done building project "Blazored.Modal.csproj" -- FAILED.

Offending code: 

```
  <Target Name="NpmInstall" BeforeTargets="BeforeBuild" Inputs="package.json" Outputs="$(NpmInstallStampFile)">
    <Exec Command="npm install" />
    <Touch Files="$(NpmInstallStampFile)" AlwaysCreate="true" />
  </Target>
```

**Comment by chrissainty** [comment]
I going to take a wild guess here and suggest you don't have nodeJS and NPM installed. If you install those you will be able to build the project.

**Comment by qfyra** [comment]
Ah, correct, I don't have NodeJS. I downloaded the project to see the sample modals in action before deciding on whether I will be able o use it in my own application. The NodeJS dependency it's unfortunately out of scope for my applications since I have no way of hosting it. Thanks for the info.

**Comment by chrissainty** [comment]
What do you mean by the Node JS dependency? It's a dev dependency and nothing to do with the shipped NuGet package.

**Comment by berellax** [comment]
Hi, I'm getting the same error. I've tried approaching it the same way as described in the video/installation steps. I've also tried approaching it by setting up a SpecFlow project and then adding this as an external assembly. It seems that the referenced versions are not compatible with the latest version of SpecFlow. Any suggestions would be really helpful!
