### ISSUE TITLE
[Bug] Readme fixes/improvements

### ISSUE THREAD

**Issue by larsk2009** [Blazored/Modal#278]
The readme still states the following:

![image](https://user-images.githubusercontent.com/7924568/103865274-3cdf2080-50c4-11eb-9b5c-eb4f30823785.png)

I think in there, the `IModalService` should not be injected, but it should be a `CascadingParameter`. This is, at least, also the case for the *Multiple Modals* part of the readme.

Also, maybe we should change [Please note: When upgrading from v4 to v5 you must remove the <BlazoredModal> tag from your MainLayout component.](https://github.com/Blazored/Modal#please-note-when-upgrading-from-v4-to-v5-you-must-remove-the-blazoredmodal-tag-from-your-mainlayout-component) to **Please note: When upgrading from v4 to v5 *(or higher)* you must remove the <BlazoredModal> tag from your MainLayout component.**

Lastly, it might be smart to remove the part from the readme where it says how to enable it for IE11. As #228 showed, the javascript containing versions of the Modal don't work on IE11 anymore, and there doesn't seem to be much progress on the issue or many people pushing for it to be added. Before removing that text, I want to make 1 last effort to fix IE11, but otherwise I think we should at least add some notes that IE11 is not supported anymore, or remove that part of the readme entirely.

Let me know what you think!

**Comment by chrissainty** [comment]
That all sounds good to me. I hadn't realised the readme was so out of date! I also agree with your proposal regarding IE11, if we can't support it we should make sure we're explicit about it.

**Comment by larsk2009** [comment]
I will make a PR for this after #228 is resolved.
