### ISSUE TITLE
[Feature] Add a list of all parameters and the meaning/use to the readme

### ISSUE THREAD

**Issue by larsk2009** [Blazored/Modal#286]
I always find it very handy if there is just a table with all available settings and their usage or meaning. Maybe this is something we can add to the readme. I also think this will provide a better overview to contributors which functions already exist.

The reason this popped in my head now, is that we have the setting `FocusFirstElement`. While it is true that that setting control whether or not the first element gets focus, it ***also*** control whether or not the Focus Trap is enabled at all. To prevent this kind of confusion, maybe it is a good idea to have an overview of all these options.

- [ ] Release notes
- [ ] Make table of settings
- [ ] Explanation about the Focus Trap

**Comment by larsk2009** [comment]
@chrissainty Maybe this issue can be used to also track the release notes in the readme?

**Comment by chrissainty** [comment]
I think this sounds like a great idea. Documentation is definitely something we could improve on and this would be a great place to start.

**Comment by chrissainty** [comment]
I beleive the new documentation site now fills this requirement so I'm going to close this as complete.
