### ISSUE TITLE
[Bug] FocusFirstElement

### ISSUE THREAD

**Issue by larsk2009** [Blazored/Modal#287]
**Describe the bug**
`FocusFirstElement` also disables the FocusTrap

**To Reproduce**
-

**Expected behavior**
Either we should rename FocusFirstElement, accept the there is some (desirable) side effect to the setting, or add a separate setting to enable or disable the FocusTrap.

**Comment by larsk2009** [comment]
@chrissainty Any thoughts?

**Comment by chrissainty** [comment]
This is the code in question:

```csharp
protected override async Task OnAfterRenderAsync(bool firstRender)
{
    if (firstRender)
    {
        if (FocusFirstElement)
            await JSRuntime.InvokeVoidAsync("BlazoredModal.activateFocusTrap", _modalReference, Id);
        _closeBtnAttributes.Clear();
        StateHasChanged();
    }
}
```

Was `FocusFirstElement` the setting to enable the focus trap and its possible just badly named? I'm struggling to remember how this came into being now. But perhaps we did it this way to make it optional for people? I honestly can't remember now.

**Comment by larsk2009** [comment]
Yeah I am not sure anymore how it came to be either. I looked trough the file history but it was still difficult to pinpoint the reason it was named this way. I don't think it is possible to both activate the focustrap and not focus the first element right? It seems like FocusTrap will always focus the first element when it is activated.

Personally I think we should rename it to something like `ActivateFocusTrap`. That is what it does, and a side-effect of that is that the first element get's focus when FocusTrap activates. I don't think there is anything we can do about that. Another option would be that there is 2 variables (one for activating and one for focusing the first element or not) but then I think we would have to force unfocus the first element in TS after we activate the focus trap.

**Comment by chrissainty** [comment]
> Personally I think we should rename it to something like ActivateFocusTrap. That is what it does, and a side-effect of that is that the first element get's focus when FocusTrap activates. I don't think there is anything we can do about that.

I agree, this seems like the best way forward. It will take away the confusion. We might need to add some more info to the read me or the sample app, to explain to developers what the focus trap is as I don't think many people have come across them.
