### ISSUE TITLE
Detect multiple modals on deactivateFocusTrap

### ISSUE THREAD

**Issue by georgeemr** [Blazored/Modal#288]
**Describe the bug**
When I open more than one modal, when I close the second modal the function deactivateFocusTrap is executed.

**To Reproduce**
Open two modals, close the last one.
I'm using custom layout bootstrap.

**Expected behavior**
Detect that are more than one modal and avoid removing the position, top, and width in the body.
Something like:
if($(".modal.show").length == 1)
{
![image](https://user-images.githubusercontent.com/3822009/105801942-ded58880-5f5f-11eb-841e-00585299702b.png)

}

**Screenshots**
![image](https://user-images.githubusercontent.com/3822009/105798213-41765680-5f57-11eb-8ac1-d6cf0af1b192.png)
When I close the second modal.

Or if I missing something, please let me know.

**Comment by georgeemr** [comment]
Solved with this:
![image](https://user-images.githubusercontent.com/3822009/105804366-3cb89f00-5f65-11eb-916d-426e48e6942f.png)

**Comment by georgeemr** [comment]
Can this be solve like that?:

`import focusTrap, { Options, FocusTrap } from 'focus-trap';

interface FocusTrapInstance {
    id: string;
    focusTrap: FocusTrap;
}

interface ModalInstance {
    id: string;
}

export class BlazoredModal {
    
    readonly _options: Options = { escapeDeactivates: false, allowOutsideClick: () => true };
    private _traps: Array<FocusTrapInstance> = [];
    private _modals: Array<ModalInstance> = [];

    public activateScrollLock(id: string): void {
        const scrollY = window.scrollY;
        const body = document.body;
        body.style.width = `${body.offsetWidth}px`;
        body.style.position = 'fixed';
        body.style.top = `-${scrollY}px`;
        this._modals.push({ id });
    }

    public activateFocusTrap(element: any, id: string): void {
        const trap = focusTrap(element, this._options);

        try {
            trap.activate();
            this._traps.push({ id, focusTrap: trap });
        } catch (e) {
            if (e instanceof Error && e.message === 'Your focus-trap needs to have at least one focusable element') {
                console.log('Focus trap not activated - No focusable elements found.');
            }
        }
    }

    public deactivateFocusTrap(id: string): void {
        const trap = this._traps.find(i => i.id === id);
        const scrollY = document.body.style.top;
        if (this._modals.length == 1) {
            document.body.style.position = '';
            document.body.style.top = '';
            document.body.style.width = '';
        }
        const currentModal = this._modals.find(i => i.id === id);
        if (currentModal) {
            const index = this._modals.indexOf(currentModal);
            if (index > -1) {
                this._modals.splice(index, 1);
            }
        }
        window.scrollTo(0, parseInt(scrollY || '0') * -1);

        if (trap) {
            trap.focusTrap.deactivate();

            const index = this._traps.indexOf(trap);
            if (index > -1) {
                this._traps.splice(index, 1);
            }
        }
    }
}

declare global {
    interface Window { BlazoredModal: BlazoredModal; }
}

window.BlazoredModal = new BlazoredModal();`

---------------

![image](https://user-images.githubusercontent.com/3822009/105806745-24974e80-5f6a-11eb-8105-6c80427f0665.png)

**Comment by chrissainty** [comment]
@georgeemr That looks like it could do the job. Would you be willing to raise that as a PR and I will take a look?
