### ISSUE TITLE
Causing Build Failure since VS 2019 Preview Ver 16.3.0 Preview 1.0

### ISSUE THREAD

**Issue by dbowser** [Blazored/Modal#29]
This was working great for my Blazor project. However, after installing the VS update my build fails. This is on the Blazor.MonoRuntime.targets line with a huge list of parameters and gives a return of '-532462766' so not real helpful. 
To reproduce just create the basic template blazor project from VS, test it, then add this package.

**Comment by chrissainty** [comment]
Hi David, I’m using that version of Visual Studio without any issues. Also my team at work is as well. Have you installed the latest .NET Core preview and the latest blazor templates via the dotnet CLI?

**Comment by dbowser** [comment]
Hmm, what specific steps do I need to take after installing the VS update? When I look at the NuGet package versions related to Core they seem to be the latest.

**Comment by dbowser** [comment]
Sorry, I didn't have the latest package version. Got it working now. Thanks :)

**Comment by chrissainty** [comment]
Glad you got it sorted :smile:
