### ISSUE TITLE
[Bug] [Typeahead] Cannot focus other inputs in modal with Typeahead component

### ISSUE THREAD

**Issue by robertsundstrom** [Blazored/Modal#291]
I have a program with nested modals, each containing Blazored.Typeahead controls. 

When I open the second modal (the child modal), I'm only able to select and open the Typeahead control. I'm not able to select and type into other input elements. It does not respond to clicks - although I have experienced it to allow me at random times.

One thing to notice is that, when clicking a text input in the child modal the Typeahead component in the modal behind gets active. It is like it (the component) has hijacked the input of the sub-modal.

Originally posted in Blazored.Typeahead: https://github.com/Blazored/Typeahead/issues/187

**Comment by larsk2009** [comment]
Could you provide a code example of this issue, which we can run on our own machines to test this? That is the easiest way to find out what is happening and prevent it in the future, I think.

**Comment by robertsundstrom** [comment]
I spent some time. I honestly could not reproduce it in a clean project. It works as expected.

 Something must be wrong with the project where it fails.

**Comment by larsk2009** [comment]
Hopefully you can also fix it in your project 😄. If you can reproduce the problem or still think it might be a problem with Blaazored.Modal, don't hesitate to re-open this issue!

**Comment by robertsundstrom** [comment]
I think I know what the problem is. 

Recap: Modals did not work with Typeahead.

In my Modal component, I have a ```Model``` property. It is initialized in ```OnInitializedAsync``` after doing some asynchronous operation to fetch data. Yes. I guard the content to render it when the ```Model``` property has been set too. I have noticed the modal flashing.

```razor
@if (Model) 
{
    <Typeahead  @bind-Value="Model.Person"  ... />
}

@code 
{
    Model { get; set; }

    protected async Task OnInitializedAsync() 
    {
         var data =await FetchData();
         
         Model = new ModelClass();
    }
}
```

Initializing ```Model``` first, before the operation, and then do the stuff, works. My input fields respond now.

I guess that the problem has to do with Typeahead and it initializing at the wrong point. Because then I cannot focus the inputs.
