### ISSUE TITLE
Double opening error modal

### ISSUE THREAD

**Issue by parente89** [Blazored/Modal#295]
Hi, when I set the Modal, it opens normally, it must be called 2 times.

So when I close the screen, I find myself 2 modals to close.

Why does this happen?

**Comment by chrissainty** [comment]
Have you upgraded from an older version? If so, have you removed the `<BlazoredModal>` component from the MainLayout as described in the readme?

**Comment by parente89** [comment]
Thanks so much! I solved it thanks to this solution.
