### ISSUE TITLE
Scrollbars on main window rather than the content [Feature Request]

### ISSUE THREAD

**Issue by peterthorpe81** [Blazored/Modal#299]
The scrollable content option was a nice addition for large dialogs but it puts scrollbars within the modal. I would think a nicer default (or option) would be for the scrollbars to appear to be at page level when the content expands too far.

The CSS would be something like below although this only works for using the mouse wheel or touch controls as the physical scrollbars are under the overlay.

/*scrollbar appears like it is at page level*/
.blazored-modal-container {
    overflow: auto;
}

/*stops flex expanding past the top of the screen*/
.blazored-modal {
    margin: auto;
}

**Comment by chrissainty** [comment]
Hi @peterthorpe81. Thanks for raising this but I don't think this is a change we will make. We're trying to be inclusive of everyone and this option would essentially exclude keyboard only users from being about to access a site which used this modal. As you've found, developers can adjust the CSS in their apps to override our defaults if they choose.
