### ISSUE TITLE
ScrollBar And Buttons Dosnt Work

### ISSUE THREAD

**Issue by matinfathi19** [Blazored/Modal#301]
hi man .thanks for this nice modal package 
i do below :
        ModalOptions _Options = new ModalOptions();
        _Options.HideHeader = true;
        _Options.Position = ModalPosition.BottomLeft;
        _Options.ContentScrollable = true;
And Modal Work Corrrectly .
When I Zooming in Explorer  , ScrollBar Apears But it is in a Disable Mode and i Cant Change its Position.
What is my Mistake?

**Comment by larsk2009** [comment]
Hi @matinfathi19.

Could you provide an example picture of your problem, and maybe a more complete example of the code you are using to show the modal?

**Comment by matinfathi19** [comment]
@larsk2009 
no i couldnt bro.
but  almost found that it is because of Options in Modal.
when i set Options.Class = "Class_A" all the object in modal onShow are Locks and disable(Even <Buttons/> Dosnt Work OnClick).
I Comment All Lines In Class_A but it dosnt solve probleem.
just removing Options.Class would solve this probleem.
what shall i to do larsk2009 ??

**Comment by matinfathi19** [comment]
solved!!!!!
this Property in css class should be inserted then all object will work correctly
z-index: 102;
