### ISSUE TITLE
Modal does not show - button click event to display fires 1 time

### ISSUE THREAD

**Issue by grumpykiwi** [Blazored/Modal#307]
**Describe the bug**

I have a list of users populated from MS Graph and displayed with a for loop

I have a click event on a div element containing a users name. Unique ID is passed to click event handler.  Event handler fires on the first click (breakpoint hit) but modal does not display. Since the user list contains nearly 100 users, there is a vertical scroll bar
visible on initial display.

After the 1st click being captured, the modal does not show, the scroll bar vanishes and clicks no longer fire
**To Reproduce**

Click F5 to run the app in VS. Click on any name in the user list
![1](https://user-images.githubusercontent.com/43825887/115485818-09f80d00-a21b-11eb-8eb3-71f7038ffa33.png)
![2](https://user-images.githubusercontent.com/43825887/115485849-14b2a200-a21b-11eb-8ccc-f88b3422b98e.png)

**Expected behavior**
Modal shows with further info about that user, retrieved from MS Graph

**Screenshots**

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server
  MS Graph / AAD

**Additional context**
I can provide the entire source as a zip for reference, but since this is an Azure app authenticated with AD you wont be able to reproduce it. Cannot post the zip here due to sensitivity of settings in the appsettings.json etc

**Comment by larsk2009** [comment]
hi @grumpykiwi,

Are you coming from an older version of Blazored.Modal to the newest version of is this a fresh 'install'.

**Comment by grumpykiwi** [comment]
It came from an old version that I ripped out completely then followed the instructions to install clean with the latest repo. Or so I thought. Its entirely possible I missed something along the way but I have been over the code multiple times comparing to the example but dont see the problem.

**Comment by larsk2009** [comment]
Yeah in my head there is something about this happening to other people who updated as well, but I am not sure. Best way to solve this is when you can reproduce it on a project we can run.

**Comment by grumpykiwi** [comment]
Thanks Lars

If you can provide me an email address, I can pull out the client id etc and send you a zip. You will need an Azure account since the goal of the app is to run as a tab inside Teams


Mark Nash
Senior Software Engineer        [cid:PC_42x23_fbb4e57e-65d2-4c41-b09e-ffa9f4a3c468.png]

PartnerComm, Inc.
Winner of 63 IABC Gold Quills
2304 W Interstate 20, Suite 250
Arlington, TX 76017
        [cid:pcomm25+_471933a4-f842-490b-84d4-910cf0397a29.png]

Office: (817) 465-9277
***@***.***
www.partnercomm.net<http://www.partnercomm.net>





This e-mail transmission may contain confidential information or may be otherwise legally privileged. If you are not the intended recipient you are hereby notified that any use, disclosure, copying, forwarding, or distribution of any of the information contained in or attached to this message is STRICTLY PROHIBITED.
________________________________

**Comment by chrissainty** [comment]
Closing due inactivity
