### ISSUE TITLE
Modal Css not being included

### ISSUE THREAD

**Issue by 2nd4ce** [Blazored/Modal#31]
Hi Chris,

First, I must admit that I am new to blazor and asp.net. 

I followed the installation guide, but in the end, I saw that the CSS is not included or at least not in 2.0.5. 
When I added manually the css from the source here in site.css, it works fine.

Thanks for the great work!
Emiliyan

**Comment by chrissainty** [comment]
@2nd4ce Thanks for reporting this. There have been a lot of issues with preview 7 and including static assets. I’m leaving things now till preview 8 comes out.

In preview 8 there will only be one way to include static assets and it will work for both client-side and server-side applications. Where as at the moment I have do fudge things to get it working for both hosting models. 

Sorry I don’t have a been solution for you right now, but come preview 8 things should be back to normal.

**Comment by 2nd4ce** [comment]
I'm sorry Chris. I missed the "Important" notice in the beginning and went straight to the installation guide.
