### ISSUE TITLE
Responsive Modal[Bug]

### ISSUE THREAD

**Issue by kamranghamsari** [Blazored/Modal#314]
Hi,
I cant make the modal responsive and I need help. Is there any feature for being responsive?

**Comment by larsk2009** [comment]
Hi @kamranghamsari,

Maybe have a look at #309 and see if that helps you? Generally the modal just takes the size of the component it hosts, so the component would be responsible for making the modal responsive.

**Comment by kamranghamsari** [comment]
I have seen the issue but I'm really new to the front-end developing. can you give me a hint

**Comment by larsk2009** [comment]
It really depends on exactly what you are trying to make, but maybe look up some tutorials for responsive web design? That might help you out.

**Comment by kamranghamsari** [comment]
Many thanks
