### ISSUE TITLE
css not loaded

### ISSUE THREAD

**Issue by FrikkinLazer** [Blazored/Modal#32]
I am running dotnet 3.0.100-preview7-012821.
This is a serverside app.

The css is not being loaded, even when adding the `<link href="_content/Blazored.Modal/blazored-modal.css" rel="stylesheet" />` line to _Host.cshtml.

Installing the nuget package does not add the blazored-modal.css file anywhere into the solution that I can see.

I have added the css file into my solution manually,  which works.

**Comment by chrissainty** [comment]
Thanks for reporting this @FrikkinLazer.

Static assets have been a real pain in Preview 7 for some reason. Preview 8 will be out hopefully today or tomorrow and then everything changes again. Preview 8 will have a single, consistent way of managing library content. So I"m holding out till then and hopefully these issues will resolve themselves. 

Apologies for now.
