### ISSUE TITLE
Can't get Blazored Modal to run from examples.

### ISSUE THREAD

**Issue by jdosser** [Blazored/Modal#320]
I've tried building the sample application from this site: https://www.thecodehubs.com/modal-popup-in-blazor/
And when I had trouble, I checked out the resolutions here and downloaded the supplied. .zip example as well.
In both cases, I receive the following error:

An unhandled exception occurred while processing the request.
InvalidOperationException: Blazored.Modal.BlazoredModal requires a cascading parameter of type IModalService.
Blazored.Modal.BlazoredModal.OnInitialized()

Note: This isn't a version upgrade or any sort of modification to an existing example, only trying to get the app to run the first time.
My platform is Windows 10 running Visual Studio 2019 Community and .Net 5.0.
Again, all steps have been followed and verified, but am still getting this issue.

**Comment by larsk2009** [comment]
Hi @jdosser,

`Again, all steps have been followed and verified, but am still getting this issue.` Do you mean all the steps as mentioned in the website you linked, or all the steps as mentioned in the readme? The article on the website you linked is over a year old and in that time a lot has changed in this project.

**Comment by jdosser** [comment]
The steps on the link were the ones I followed, and 'yes', my down downloaded version (6) was quite
a bit newer than the one in the example.
I'll try the example here: https://github.com/Blazored/Modal/tree/main/samples
and try the server version.

And thanks for the quick response,
Jeff


________________________________

**Comment by jdosser** [comment]
Lars,
Since I've got you on the line and am following the directions, I'd like to point out this highlighted line:
4. Add reference to style sheet & javascript reference

Add the following line to the head tag of your _Host.cshtml (Blazor Server) or index.html (Blazor WebAssembly).

<link href="_content/Blazored.Modal/blazored-modal.css" rel="stylesheet" />

Then add a reference to the Blazored Modal JavaScript file at the bottom of the respective page after the reference to the Blazor file.

<script src="_content/Blazored.Modal/blazored.modal.js"></script>



I'm going to download the application and see if I can't find 'the respective page' which the instuctions

say to use, but I don't know what 'the respective page' means. Is this the page I want displayed as modal or another page?
It might make more sense to new BLazor users if this was explained better.


Jeff


________________________________

**Comment by larsk2009** [comment]
Yes try the sample, if that is still giving issues let me know!

With respective page either `_Host.cshtml` or `index.html` is meant, as mentioned in the line above that line.

**Comment by jdosser** [comment]
I did run into this particular problem after downloading the GitHub version and trying to add 'Blazored.Modal' to the project through NuGet manager.
When I click on the 'Install' button after selecting 'Blazored.Modal' (in NugGet Mgr), I get the following errors so that Blazored.Modal never gets included.
Error messages:  'npm install exited with code 9009'. Additional errors all read some variant of: "<project path name & folder list>\netstandard2.1\Blazored.Modal.dll' could not be found.
Not sure what's up with that, but maybe that error message will help.

________________________________

**Comment by larsk2009** [comment]
Could you provide the project that is causing this? Then I can check if that also happens on my system and how to solve it.

**Comment by jdosser** [comment]
Hey Lars,
I tried looking through my history, and couldn't ID which github file location it was.
I only remember the download page showed both Server and Webassembly examples
inside the same project package.
On the plus side, I downloaded another example and everything ran great.
Nice product you folks have made. It's been a huge help and looks great.

Jeff

________________________________

**Comment by larsk2009** [comment]
Nice to hear that it works now. If you do run into another issue, please don't hesitate to open another issue!

**Comment by sanongpost** [comment]
I download latest version 7.1.0.  I also use MudBlazor and looking for modal confirm like java confirm function.
follow all steps, manage to get things show up but, all show at top left of screen. And whenver you add <BlazoredModal /> all will be shownup twice.
Anyone pls advise...
