### ISSUE TITLE
Add ModalResult.Ok w/o parameter

### ISSUE THREAD

**Issue by leotsarev** [Blazored/Modal#325]
**Is your feature request related to a problem? Please describe.**
Not all dialogs should return anything when successful

**Describe the solution you'd like**
I like to have ModalResult.Ok() w/o result type

**Comment by larsk2009** [comment]
Hi @leotsarev,

Thanks for using the our component!
Could you elaborate on the use case of this, or the advantage this offers over the current solution?

**Comment by Fulborg** [comment]
I have a case, where it would be useful. 
There is a page, which displays data from an external system (accessible via REST api).
Dialog, opened from that page doesn't change anything in the website itself, but modifies some data in external service (with REST api). If the dialog is processed successfully (and the data is changed) - calling page data should be refreshed (as the external dependency changed). Of course, model can be fetched in the dialog and passed as a dialog result, but it looks like a code duplication, compared to returning some simple result to the caller (was data updated, or not), and processing it there.

**Comment by larsk2009** [comment]
Hi @Fulborg,

Thanks for the info. If I read your situation correctly, you *do* actually need to return something right? A `bool` or something to confirm if the data should be updated or not?
