### ISSUE TITLE
Combine with Blazor island

### ISSUE THREAD

**Issue by leotsarev** [Blazored/Modal#326]
**Is your feature request related to a problem? Please describe.**
There is possible to add island of Blazor functionality into "old" server-side razor application.
For example, you could have full page of server side controls and add somewhere
```<component type="typeof(MyDynamicControl)" render-mode="WebAssembly" />```

I need guidance how to use Blazored.Modal from  MyDynamicControl

**Comment by larsk2009** [comment]
Hi @leotsarev,

I am afraid I don't entirely understand what you are trying to achieve. Could you maybe clarify or give us some documentation site for reference?

**Comment by leotsarev** [comment]
There is possible to use Blazor control inside "regular" Razor pages/MVC application.
https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-5.0&pivots=webassembly#render-components-in-a-page-or-view-with-the-component-tag-helper


What I' m trying to achieve:

Regular MVC Razor page with regular layout that host some Blazor control with button. When this button is clicked, Blazored.Modal is opened over page.

What will happen:

Blazored.Modal will open over just this control.

**Comment by chrissainty** [comment]
Blazored Modal needs a cascading parameter in order to function. This would need to wrap whatever component you wanted to use in the island. For example:

```razor
// BlazorIsland.razor

<CascadingBlazoredModal>
	<YourComponent />
</CascadingBlazoredModal>
```

You can then use the component tag help to display the `BlazorIsland` component:

```razor
<component type="typeof(BlazorIsland)" render-mode="WebAssembly" />
```

What I'm not sure about is how well everything will render. The modal is designed to be high on the component tree, preferably in App.razor. You might end up needing to tweak the CSS.

**Comment by leotsarev** [comment]
>Blazored Modal needs a cascading parameter in order to function. This would need to wrap whatever component you wanted to use in the island. 

Yeah, thx, I figured this out.

>What I'm not sure about is how well everything will render
It will look extremely bad :-(

Could it be solved on Blazored level?

**Comment by chrissainty** [comment]
Are you saying you've got it working but it doesn't look right?

> Could it be solved on Blazored level?
Maybe, but I doubt it. This library is designed for pure Blazor apps. The usage of it in Razor Page apps is really really tiny. I couldn't warrant the time to look into it, I'd also be concerned about doing anything which could potentially break a standard Blazor app.

**Comment by chrissainty** [comment]
Closed as no further communication
