### ISSUE TITLE
[Feature Request] Refresh button

### ISSUE THREAD

**Issue by Fragger5000** [Blazored/Modal#328]
Good morning, first of all thanks for your work and your dedication. 

I'm looking for a suitable way to refresh the contents of a modal window.

I'm thinking to a method that "remembers" also the options and parameters which were used to open the modal the first time.

In this moment I'm canceling the modal than I reopen it. [edit]The following code is present in the component displayed in the modal[/edit]

`<button class="btn btn-info" @onclick="() => RefreshTicketDetails()">Refresh</button>`

```
    protected async Task RefreshTicketDetails()
    {
        await BlazoredModal.CancelAsync();

        var options = new ModalOptions
        {
            Class = "blazored-prompt-modal",
            OverlayCustomClass = "custom-modal-overlay"
        };

        var parameters = new ModalParameters();
        parameters.Add(nameof(MyComponent.fstPar), TheFstPar);
        parameters.Add(nameof(MyComponent.sndPar), TheSndPar);
        ...
        parameters.Add(nameof(MyComponent.nthPar), TheNthPar);

        Modal.Show<MyComponent>("MyTytle", parameters, options);
    }
```

It works. If there aren't other ways to reach my scope, well, I've a solution, but I'm wondering if you can implement a cleaner way to do it.

**Comment by chrissainty** [comment]
Why don't you make a request from the component being displayed in the modal to get the new data? That would seem the simplest thing to do.

**Comment by Fragger5000** [comment]
Infact I make the request from the component displayed in the modal.

I'll try to be clearer.

It's a master/detail scenario, the first time I open the modal I pass the options and the parameters from the master component to the detail, but when I need to refresh the detail component I close and the reopen the modal passing the same options and parameters from itself.

**Comment by chrissainty** [comment]
I'm sorry I don't understand. Could you create a simple project showing what you're currently doing?

On a general note. Unless you're destroying the component being displayed in the modal, the values you pass to it will persist. But I'm guessing as you've mentioned reopening the model, that you're possible closing it and then reopening it. As I said at the start, I'm not quite sure what you're doing.

**Comment by Fragger5000** [comment]
![image](https://user-images.githubusercontent.com/22413422/127614101-eb94819d-f944-41c8-97e0-6cbfacb069d6.png)

**Comment by chrissainty** [comment]
So are you passing the data which the component displays from the master page? If so, then the only improvement I can see would be to implement a simple state class which exposes the data used by the master page. This can then be injected into the component displayed in the modal and refreshed from there.

**Comment by Fragger5000** [comment]
I pass only the record Id and something else to the component displayed in the modal. 

In that component I have a method that retrieves tha data from the database. 

In effect, using a class which exposes the data is abetter practice than pass sparse parameters of various kind.

Thanks

**Comment by chrissainty** [comment]
> I pass only the record Id and something else to the component displayed in the modal.
> In that component I have a method that retrieves tha data from the database.

Why can't you just trigger a new database call when the refresh button is pressed on the component displayed in the modal?

**Comment by Fragger5000** [comment]
:-) right! I'm converting an old web app to blazor, I didn't considered this optimization

**Comment by chrissainty** [comment]
No worries. It's easy to get into a certain way to approach a problem. Happened to me more time than I'd care to remember 🙂. 

As there is nothing to do here I'm going to close this issue.
