### ISSUE TITLE
Edit Form - Pressing Enter key on input field closes modal rather than submitting form

### ISSUE THREAD

**Issue by GFOX91** [Blazored/Modal#329]
Hi,

I've set up a modal for the purposes of editing the details of an entity in this example an Organisation. When submitting the form via button click it works as it should, however, I've noticed when I attempted to change the name field then press the enter the key whilst in this text input the modal is closed. I feel a better user experience would be for the form to do all the relevant validation checks and submit if they all pass. Any ideas on the best way to handle this? I have attached my code thus far for the modal

**Razor**
![razor](https://user-images.githubusercontent.com/51232749/128487785-5f690545-7fb3-45a2-9161-e178173b4943.PNG)

**Code Behind**
![CodeBehind](https://user-images.githubusercontent.com/51232749/128487828-6524f0c3-f436-4418-8d5b-1ca4d9587630.PNG)

**Comment by chrissainty** [comment]
Could you put together a minimal repro of the issue? I can't think of anything in the modal code which should trigger this behaviour.

**Comment by GFOX91** [comment]
Of Course. 

I have created a small example here.

[https://github.com/GFOX91/ModalExample](url)

Simple set up that changes a string based on what the form does, if you test pressing the enter key in the same field rather than the submit button the form is closed rather than being submitted.

**Comment by chrissainty** [comment]
Awesome. Thanks for this @GFOX91. I'll have a look into this and let you know what I find.

**Comment by GFOX91** [comment]
That's awesome @chrissainty thanks a lot.

**Comment by GFOX91** [comment]
Hi @chrissainty,

Are there any updates on this?

Thanks

**Comment by chrissainty** [comment]
Apologies @GFOX91 I thought I'd come back to you already! 

The issue is actually your cancel button. You need to set its type to button and this issue will be resolved.

```razor
<button @onclick="Cancel" type="button" class="btn btn-secondary btn-sm mr-2">Cancel</button>
```

This is because the default type for a button is `submit` (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type), so essentially your form had two submit buttons.

**Comment by GFOX91** [comment]
Hi @chrissainty,

That's awesome I would of never made that connection, thanks for your help!
