### ISSUE TITLE
Modal is not working with CascadingAuthenticationState component tag in App.razor file

### ISSUE THREAD

**Issue by MRakesh** [Blazored/Modal#334]
Keeping CascadingBlazoredModal component Inside  CascadingAuthenticationState component Is not working in App.razor page. Getting can not process request message on browser  
Ex
CascadingAuthenticationState
      CascadingBlazoredModal
        Route....
      CascadingBlazoredModal
CascadingAuthenticationState

**Comment by larsk2009** [comment]
Could you maybe create a bug report using the standard bug template? You will see the option to use this when creating an issue in this repo.

**Comment by MRakesh** [comment]
Closed
