### ISSUE TITLE
Preview 8 - Client Side - CSS  not loading

### ISSUE THREAD

**Issue by 2nd4ce** [Blazored/Modal#34]
Hi Chris,

Thanks for the ultra-fast update to 2.0.6. I have problems with the CSS again, but potentially, it is legitimate this time.

I put the link in the index.html, but the page reacts as there is no file behind.
<link href="_content/Blazored.Modal/blazored-modal.css" rel="stylesheet" />

I used a workaround to put the content of my Modal/src/Blazored.Modal/wwwroot/blazored-modal.css into my site.css. Works fine to me.

**Comment by chrissainty** [comment]
Can you do a full clean and restart of VS then run your app and check in the dev tools > sources tab. Is there a `_content/Blazored.Modal` folder?

**Comment by 2nd4ce** [comment]
Yep, I think it's due to something in my setup. I was using VS Code. When I started the project in VS, then the css is loading.

**Comment by 2nd4ce** [comment]
Hi Chis, 

If someone else hit the same problem, I found the issue. Apparently, launchSettings.json was missing. I use VS Code and generated the initial project of blazor with the CLI. However, launchSettings.json is not there. Only after opening it with the full VS, launchJson is generated.

Regards,
Emiliyan

**Comment by b0rke5** [comment]
> Can you do a full clean and restart of VS then run your app and check in the dev tools > sources tab. Is there a `_content/Blazored.Modal` folder?

Hi, Chris! First of all thanks for great libs for Blazor!
After last upgrade of Blazored.Modal to **2.0.6**  Blazored.Modal/blazored-modal.css gives 404 error, although _content/Blazored.Modal is present in Dev Tools \ Sources.  
Using VS2019 Prev 16.3.0 and blazor version **3.0.100-preview8-013656** 
Looks like an VS or template error..

**Comment by chrissainty** [comment]
@b0rke5 Have you added the correct tag to your index.html or _Host.cshtml as per the readme?

**Comment by b0rke5** [comment]
> @b0rke5 Have you added the correct tag to your index.html or _Host.cshtml as per the readme?

yes, I've added this css tag in index.html right after update! I have no idea what happened, but it works fine now after a few days, probably browser's cache was the problem, thanks anyway!
