### ISSUE TITLE
[Feature Request] Return object on cancel

### ISSUE THREAD

**Issue by inertia666** [Blazored/Modal#342]
**Is your feature request related to a problem? Please describe.**

I would like to return an object through the modal if cancel is pressed, the same way as when the form is submitted.

In some situations, where the edited object is not entirely bound but updated with custom events, I need to return the original object back to the service.

**Describe the solution you'd like**

Something like:

`        ModalInstance.CloseAsync(Modalresult.Canceled<T>(t));`

Where the result also flags the action as cancelled 

Or just

`        ModalInstance.CancelAsync(t);`

**Describe alternatives you've considered**

At the moment my workaround is to use the standard Close method but have to do my own comparisons instead of just restoring the original object by checking a status flag.

` ModalInstance.CloseAsync(ModalResult.Ok<T>(t));`

**Comment by chrissainty** [comment]
Thanks for raising this @inertia666. I think this is something we can add. Would you be interested in creating a PR for the feature?

**Comment by inertia666** [comment]
What do you mean by PR?

**Comment by chrissainty** [comment]
@inertia666 https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by inertia666** [comment]
OK, that's what I thought you mean but I haven't changed the code and implemented this feature myself to create a PR for you.

**Comment by chrissainty** [comment]
Thats, fine. I was asking if you'd be prepared to? I have a lot of things on my plate right now and frankly I wouldn't get to this feature for several months. If you'd be happy to create a PR then you'll be able to get the feature quicker, that's all.

**Comment by inertia666** [comment]
Yes I can probably sort that out. 

I would need some kind of guidance to how it should be implemented though. I've only just started using Blazor a week ago and even less time spent on the actual modal so not familiar with the workings of it yet.

The simplest method seems to be to pass an override method with an object
 
` ModalInstance.CancelAsync(object);`

The other alternative might be slightly more complicated.

`ModalInstance.CloseAsync(Modalresult.Canceled<T>(t));`

**Comment by chrissainty** [comment]
I think the first option would be better. I'm wondering if it should be a generic method though:

```csharp
ModalInstance.CancelAsync<T>(value);
```
