### ISSUE TITLE
[Feature Request] Add documentation for UseCustomLayout

### ISSUE THREAD

**Issue by jasekiw** [Blazored/Modal#346]
I found the parameter UseCustomLayout but found no documentation on how to use it. Can this be added to the readme?

**Comment by chrissainty** [comment]
There is an example usage in the Sample projects. I'd also be happy to take a PR to add something to the readme.

**Comment by jasekiw** [comment]
I can probably submit a pr for it in the next week.

**Comment by chrissainty** [comment]
That would be fantastic @jasekiw and much appreciated.

**Comment by aterbo** [comment]
Hey @jasekiw just wanted to check if you still had time and plans to do a PR for this. If not, I can get one together. I'm looking for something I can help out with on this repo. If you're still planning to do it, not a problem!
