### ISSUE TITLE
[Feature Request] Add UseCustomCloseButton

### ISSUE THREAD

**Issue by jasekiw** [Blazored/Modal#347]
I would like to be able to customize just the close button html without hiding the entire header. A parameter that that takes a function with CancelAsync, and closeBtnAttributes as parameters would allow for this.

**Comment by larsk2009** [comment]
So you want to change the 'value' of the `X` button if I understand correctly?

**Comment by jasekiw** [comment]
I would like to customize the html element of the x button entirely. eg. Swap it out with my own svg. I believe this is what you are saying.
