### ISSUE TITLE
Scrollable Content

### ISSUE THREAD

**Issue by cyberdarius** [Blazored/Modal#35]
There is a way to make the content of modal scrollable ?

I'm developing an input dialog (bootstrap). 
In full screen is ok, but on resized/mobile screen the content is fixed and not scrollable like in bootstrap modal. The scrollbar is visible, but it scrolls the parent page, not the modal itself.

[https://imgur.com/vf6DFB0](url)

There is any preferred way to achieve scrollable/responsive modal content ?
Thank you Chris for this component!

**Comment by chrissainty** [comment]
Try setting a height on the `blazored-modal-content` CSS class then set `overflow-y: auto`. That should get you what you want. 

Example:
```css
.blazored-modal-content {
  height: 300px;
  overflow-y: auto;
}
```

**Comment by chrissainty** [comment]
As I've not heard anything I'm going to go ahead and close this issue as hopefully, the above solution resolved your issue. Feel free to re-open if not.

**Comment by SindelarPetr** [comment]
Hi! Thanks for a great tool. This fixes the problem unless the underlying page is not scrollable. If the underlying page is scrollable, then the page will be scrolled but not the modal, any ideas?

**Comment by chrissainty** [comment]
This is just standard CSS styling, I can't really advise as I don't know what your CSS styles are or how they work within the design of your application.
