### ISSUE TITLE
Capturing EventCallback from the referenced component.

### ISSUE THREAD

**Issue by i-am-dan** [Blazored/Modal#355]
**Is your feature request related to a problem? Please describe.**
I am trying to close the modal dialog by listening to an event from the referenced component. I have a form that the modal is referencing (EditForm) and when that form is submitted I want to use EventCallback from that component and have the modal listen to that callback. When I try to add a function to a parameter (while creating the reference) I get "I cannot convert group to an object" error)

**Describe the solution you'd like**
Just like we are able to pass the parameters and options to a component. Can we also have the ability to pass other attributes that are not limited to only string parameters? 

**Describe alternatives you've considered**
I can't think of any other alternative solution :(

**Additional context**
Thank you for the great library!

**Comment by larsk2009** [comment]
Can you not make a function that listens to the callback (outside of the modal) and have that function close the modal?
