### ISSUE TITLE
Issues after upgrading to VS V 16.3 Preview 2.0 and BlazoredModal 2.06

### ISSUE THREAD

**Issue by dbowser** [Blazored/Modal#36]
This was working pretty well. 
Now, it adds a 'close icon' to MainLayout.razor (so always showing) and the 'modals' show off to  the side of my windows instead of on top of them when I open them.

I went over the setup instructions to make sure I am implementing the latest. 

What else am I missing?

**Comment by chrissainty** [comment]
It sounds like you're missing the CSS. This is usually down to browser cache most of the time, so try clearing that. 

Another issue can be the CSS isn't loading from the NuGet package, if you're sure that the CSS is present and there aren't any caching issues then, for now, manually copy the CSS from this repo to your project.

Hopefully this will all get sorted with Preview 9.
