### ISSUE TITLE
Clicking on disabled background re-runs lifecycle (OnParametersSet, SetParameters, and OnAfterRender) [Bug]

### ISSUE THREAD

**Issue by aterbo** [Blazored/Modal#363]
**Describe the bug**
If you have a modal with the background set to disabled, clicking the disabled background re-runs SetParameters, OnParametersSet, and OnAfterRender lifecycle methods (both sync and async) of the component being displayed in the modal.

This is causing a problem with some forms I have that pull data in during OnParametersSet. Any unsaved data is being reset if the user clicks on the overlay. I can fix this by moving methods to OnInitialized, but I'm not sure why this is occuring.

**To Reproduce**
Can be seen in the sample Blazor Server app
1. Add a logger to fire on the lifecycle methods in the `Confirm.razor` component, something like
```
protected override void OnParametersSet()
    {
        Logger.LogInformation("- OnParametersSet");
    }
```
2. Run the Sample app and open the Background Click tab
3. Click the background and watch your lifecycle.

**Expected behavior**
I was expecting that all background clicks would be fully disregarded, but my understanding may be wrong. Rerunning OnParametersSet may be the expected behavior

**Additional context**
If this is the expected behavior, we should add clarifications to the Wiki

**Comment by chrissainty** [comment]
@aterbo I spotted the issue. There was a check in the `HandleBackgroundClick` method that returned if `DisableBackgroundClick` was set to `true`. This is what stopped the background click closing the modal.

However, as it is triggered from an `onclick` event Blazor will automatically call `StateHasChanged` when the handler completes. This is what was causing the lifecycle methods to re-run. 

I've added a fix in #436
