### ISSUE TITLE
[Bug] UI is not properly updated when modal windows are closed not in reverse order

### ISSUE THREAD

**Issue by crui3er** [Blazored/Modal#366]
**Describe the bug**
When 2 modal windows are opened with different modal options and you close the one that was opened the first, remained second modal keep its content but gets modal options from the first window. 

**To Reproduce**
1. Prepare component that can display given text (text widget);
2. Show modal window in left-top corner with text widget with content 'Left';
2. Show second modal window in right-bottom corner with text widget with content 'Right';
3. Close first modal window that displayed in left-top corner. (I do it progromatically);
4. Modal window in right-bottom corner disappers. Modal window in left-top corner hosts text widget with content 'Right';

**Expected behavior**
Modal window in left-top corner is closed. Modal window in right-bottom corner is remained and contains text widget with content 'Right'

**Screenshots**
![BlazoredModalUpdateIssue](https://user-images.githubusercontent.com/20703715/146414454-ea47a61f-2903-4099-9631-9342c50d743f.gif)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Discovered on Blazor Server mode, but I suppose it should work the same in Blazor WebAssembly mode

**Additional context**
Sample project. Click simulate button to see behavior.
[BlazorModalUpdateIssue.zip](https://github.com/Blazored/Modal/files/7729191/BlazorModalUpdateIssue.zip)

Simulation code extract:
```csharp
private async Task Simulate()
{
    var p1 = new ModalParameters();
    p1.Add("Text", "Left");
    var refLeftModal = ModalService.Show<TextWidget>("Left", p1, new ModalOptions { Position = ModalPosition.TopLeft });
    await Task.Delay(1000);
    var p2 = new ModalParameters();
    p2.Add("Text", "Right");
    var refRightModal = ModalService.Show<TextWidget>("Right", p2, new ModalOptions { Position = ModalPosition.BottomRight });
    await Task.Delay(1000);
    refLeftModal.Close();
}
```

**Comment by larsk2009** [comment]
Ah wow, nice catch!

**Comment by chrissainty** [comment]
@larsk2009 This looks like something we should try and get fixed for the next release.

**Comment by larsk2009** [comment]
Jup I agree, I haven't tested it myself but the fix by @crui3er seems to do the trick.
