### ISSUE TITLE
Issue applying classes

### ISSUE THREAD

**Issue by jcantrel** [Blazored/Modal#368]
I am trying to implement Blazored Modal into my Blazor server side app that uses Tailwind for CSS. However I am having trouble creating a form. No matter what CSS settings I've tried inside the component the modal itself remains the same size. I then tried applying a class to the modal itself seems to break. It becomes grayed out like the background and the elements inside cannot be interacted with.

No CSS
![modal-nocss](https://user-images.githubusercontent.com/37300313/146567314-befd1993-43d5-45b9-a586-897632bf7721.PNG)

Any kind of CSS applied
![modal-css](https://user-images.githubusercontent.com/37300313/146567315-fe681bac-1f50-4d4e-b182-f64565936cda.PNG)

Here is the code I am using, the specific CSS doesn't seem to matter. In this case the width does seem to change, but the modal element remains unclickable.

`
private void showModal()
    {
        var options = new ModalOptions()
        {
            Class = "w-1/4"
        };
        Modal.Show<ViewPatient>("Add Patient", options);
    }
`

**Comment by chrissainty** [comment]
When you provide a value for the `Class` option, it replaces the default class, they are not added to it. This is why are losing all other styling. You will need to provide all styling you require, including specifying a z-index so the modal shows above the backdrop.

**Comment by aterbo** [comment]
See #364 pending PR for some proposed updates to the docs clarifying this issue.

**Comment by chrissainty** [comment]
Hopfully the updates docs provided by #364 should clarify what is required when specificying a custom class.
