### ISSUE TITLE
Animate overlay as well as modal when fading in/out [Feature Request]

### ISSUE THREAD

**Issue by aterbo** [Blazored/Modal#369]
**Is your feature request related to a problem? Please describe.**
I'm not sure if this is a feature request or a bug, but I think the animations would look much smoother if they also faded in and out the overlay as well. The current animations have the overlay pop in first, then the modal fade above it. The fade out does the opposite, where the overlay just pops off the screen after the modal disappears.

**Describe the solution you'd like**
The overlay should also animate as per the modal options settings

**Describe alternatives you've considered**
I made a quick branch showing one proposed solution to this. It modifies `BlazorModalInstance` to apply the same animation classes to the overlay `<div>` as well as the dialog `<div>`. It does this by creating another private string parameter, `OverlayAnimationClass`, which is populated similarly to the way that the main modal animation class is determined. It is applied under a different html Id from the main modal to make it unique (I just appended `-overlay` so the Id is still generated on the fly for multiple modals) 

This class is applied separately from the CustomOverlayClass so that it will also animate custom classes. It also works for multiple animated modals and global settings. It will not apply to custom layouts, same as the current animations.

**Current Behavior -- Overlay pops in and out first and last**
![CurrentAnimation](https://github.com/aterbo/BlazoredModalErrorTesting/blob/master/WithoutOverlayAnimation.gif?raw=true)

**Propose Behavior -- Overlay fades in and out**
![ProposedAnimation](https://github.com/aterbo/BlazoredModalErrorTesting/blob/master/WithOverlayAnimation.gif?raw=true)

**Comment by larsk2009** [comment]
Sounds like a good idea, i'll have a look at your PR.
