### ISSUE TITLE
[Feature Request] ModalParameters to support collection initialization

### ISSUE THREAD

**Issue by MichelJansson** [Blazored/Modal#373]
**Is your feature request related to a problem? Please describe.**
I love object and collection initializers and even though `ModalParameters` is mostly a collection it does not support a collection initializer, which makes me a little bit sad.

**Describe the solution you'd like**
Support for collection initialization.
``` cs
new ModalParameters
{
    { nameof(modal.ModalParameter), myParameter }
};
```

**Describe alternatives you've considered**
Since the underlying `Dictionary` is marked `internal` we cannot subclass `ModalParameters` to add support on the consumer side.

**Additional context**
This could easily by accomplished by implementing `IEnumerable` that exposes the underlying dictionary enumerator.
``` cs
public class ModalParameters : IEnumerable<KeyValuePair<string, object>>
{
    internal Dictionary<string, object> _parameters;

    IEnumerator IEnumerable.GetEnumerator()
        => _parameters.GetEnumerator();

    ...
}
```

**I would be happy to submit a PR for this change**
YES.

Thanks for this great package!

**Comment by larsk2009** [comment]
Hi @MichelJansson, on the surface it seems like a great suggestion. I don't know if there are any reason this isn't done already, so I'll leave that to @chrissainty. 

I did a little research and it seems this works because there is already the `Add` method, so you only have to implement the GetEnumerator function right?

**Comment by MichelJansson** [comment]
@larsk2009, indeed, but it will actually be two `GetEnumerator` methods, one for `IEnumerable` and one for `IEnumerable<T>`, but they both will just expose the enumerator of the dictionary.
