### ISSUE TITLE
When making outside calls to an api it calls twice

### ISSUE THREAD

**Issue by nyluhe** [Blazored/Modal#376]
**Describe the bug**
When I make call to my api it appears to call the method twice when done within the Modal, in OnParametersSetAsync(). However, this doesn't happen if I get the object first and pass it into the Modal.

**Expected behavior**
I would expect for the Modal to only call OnParametersSetAsync() once, but it looks to call it twice.

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly

**Additional context**

**Comment by nyluhe** [comment]
When I call the same api method within OnInitalizedAsync() it only calls once.

**Comment by chrissainty** [comment]
Hi @nyluhe we don't call lifecycle methods. The framework does. It sounds like something in your scenario is causing Blazor to update the parameters to your component, hence the two calls to OnParametersSet.

**Comment by nyluhe** [comment]
Apologies @chrissainty, the cascading parameter modal instance is not set at the same time as the parameter I passed in so it's calling that method twice. 

I've switched to OnInitialized to handle the parameter now. It was a misunderstanding of the Blazor lifecycle.

 Thanks!
