### ISSUE TITLE
[Bug] Microsoft.JSInterop.JSException: Could not find 'BlazoredModal.activateScrollLock' ('BlazoredModal' was undefined)

### ISSUE THREAD

**Issue by Trapulo** [Blazored/Modal#377]
**Describe the bug**
When I enter the page and click the button that may open the modal, I have the error "Microsoft.JSInterop.JSException: Could not find 'BlazoredModal.activateScrollLock' ('BlazoredModal' was undefined)"

if I reload the page, then click same button, it works.

Tried different browsers, cache cleanup, etc. always same result.

**Hosting Model:**
 - Blazor WebAssembly
 - .NET 6

Thanks

**Comment by larsk2009** [comment]
Does the network tab in your browser show any files failing to load? IT seems strange it doesn't work the first time, but after that it does work.

Also, have you seen #357, #261, #259, $197 and more like that? They al have similar issues, and it is caching almost every time. I know you said that isn't the issue, so maybe there is a different reason why the file is not laoding. If you can have a look at the network tab we'll know for sure why it isn't being loaded.

**Comment by FraserElectronics** [comment]
I am also seeing exactly the same thing.
Fails with the same error message but if I refresh the browser window it works.
Same hosting model and using the Edge browser.

Andy

**Comment by FraserElectronics** [comment]
Okay, subsequently it is now working fine !
Not sure what was going on there :-(

Andy

**Comment by Trapulo** [comment]
I don't know: it the same for me. It's now working. Really strange Blazor WASM... :(
