### ISSUE TITLE
Cascading parameters into the modal

### ISSUE THREAD

**Issue by samihuutoniemi** [Blazored/Modal#378]
**Describe the bug**
Not sure if it is a bug, feature request, or maybe more a question. We use a component "Error" to show errors in our app. This uses Blazored Modal. But modals are also used for other purposes. The Error component is cascaded into all components, but if the component is a modal, it will be null.

Is there any way for a component being the object of a Blazored Modal to receive a cascading parameter? I know I get the BlazoredModalInstance cascaded into it, but can I get my own?

**To Reproduce**
1. Create and open a blazored modal.
2. My cascading parameter's value is null.

**Expected behavior**
Would like it to be my component.

**Screenshots**
![image](https://user-images.githubusercontent.com/2758838/151928058-fae87f0d-c4d8-4821-8c29-795b445ab8d1.png)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Comment by chrissainty** [comment]
Hi @samihuutoniemi, I don't think this is going to be possible. Looking at your code, your Error component would need to wrap the `CascadingBlazoredModal` component. But if that's what your `Error` component uses under the hood then that won't work.

**Comment by aterbo** [comment]
Hey Chris,

I've run into similar issues. Is there any way were you could force cascaded parameters for the calling component are in turn cascaded into the modal?

I highly doubt it, since the `CascadingBlazoredModal` wraps the whole app and would need to be wrapped in whatever cascades to it, but I wanted to ask if you knew of any clever methods that might work for something like this?

**Comment by silvavelosa** [comment]
Does the Error component need to interact in any way with the `ModalService`? if not, then you can just reverse the order, like: 

```html
<Error>
    <CascadingBlazoredModal>
    ...
    </CascadingBlazoredModal>
</Error>
```

If `Error` needs the `ModalService`, you can still get it injected and it will work... but it's kind of a hack, since it's no longer the advised way to get it.

```html
<!–– Error.razor ––>
@inject IModalService ModalService

<CascadingValue Value="this">
    ...
</CascadingValue>
```

**Comment by chrissainty** [comment]
I think the option @silvavelosa has presented is probably the only way to make your scenario work, @aterbo. I'm going to close this now as there is a potential answer.
