### ISSUE TITLE
Can't Interact with controls on Modal

### ISSUE THREAD

**Issue by FraserElectronics** [Blazored/Modal#379]
**Describe the bug**
Not sure if this is a bug but I have created a modal form with a Mud table control on it.
As soon as I try and interact with the table such as selecting a different page of data, the dialog closes.

**To Reproduce**
1. Create modal with an control you can interact with.
2. Click on said control and observe that the modal closes.

**Expected behavior**
In my application I would like the user to scroll through data in the table and select a row.
On pressing Okay, the selected row would be passed back to the caller.

**Screenshots**
None.

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly
 - DotNet 6.0
 - Running on Edge.

**Additional context**
One observation is that the form appears grayed out as if disabled.
I am also trying to override the styling by setting the Class property of ModalOptions and giving it a colourful background but it is still gray in colour :-(

Andy

**Comment by larsk2009** [comment]
I would think that the overlay is on top of your modal, especially if clicking closes the modal and because it looks disabled (might be because the overlay is on top of it). Does clicking anywhere on the modal produce this behaviour? Likely you'll need to set a z-index value, see the sample (if you disable the z-index there with the browser dev-tools, you'll get the behaviour you specify).

**Comment by FraserElectronics** [comment]
Yes, clicking anywhere on the modal has the same effect.
I think the z-index is the issue but I increased it in my custom style but it still does the same thing.

Andy

**Comment by FraserElectronics** [comment]
Okay, so disabling the z-index on the underlying control causes my modal to work as I would hope.
So the underlying z-index is 101 but if I set my modal style to 100 or 102 neither makes a difference.
I am still trying to get my head around css and styles in general.

Andy

**Comment by chrissainty** [comment]
If you could provide a repro of this issue it would help dramatically, this is really hard to help with without some example code to work from.

**Comment by FraserElectronics** [comment]
Chris,
I have created a really simple example here: [Githb](https://github.com/FraserElectronics/BlazoredModalTest.git)
If you click on Counter then click the Click Me button it pops up a modal with a date picker and two buttons. It is not possible to interact with the controls on the razor component that forms the modal form. I am sure I am doing something very obviously wrong but can't seem to figure it out.

Andy

**Comment by chrissainty** [comment]
Thanks for that @FraserElectronics. I can see the issue. When you created your custom CSS class you didn't give it a high enough `z-index`, it needs to be higher than 101. Change your `aqua-modal-class` to this and everything works.

```css
.aqua-modal-class {
    display: flex;
    flex-direction: column;
    width: 60vw;
    height: 60vh;
    background-color: #e1e1e1;
    border-radius: 12px;
    border: 1px solid #1861ac;
    padding: 0.5rem;
    z-index: 102; 
    box-shadow: 0 15px 15px rgba(0,0,0,.75);
}
```

**Comment by FraserElectronics** [comment]
Chris,

Yes, that solves the issue in my simple demo app but if you note the comments previously, in my main application, setting the Z-Index greater than 101 makes no difference. It is not easy for me to share my main Blazor app as it depends on a SQL database connection and user login credentials. I can't really see much difference in my app code to this demo code though :-(

Andy

**Comment by chrissainty** [comment]
I understand the problem with replicating a real app. Thanks for trying. 

What I think this does indicate to us is that's it's probably CSS related. You might have something which is messing with the z-index in some way. 

It might be worth trying the v7 review package I published yesterday. That has a few changes which might have an effect for you. However, there are a couple of small API changes which I haven't had a chance to document yet.

**Comment by FraserElectronics** [comment]
I will give v7 a try and will let you know how I get on.
Thanks for trying to get the bottom of this for me 👍

Andy

**Comment by FraserElectronics** [comment]
Tried the pre-release but no joy :-(
Is there something I should look for in the structure of the page?
I have a screenshot of developer tools showing the elements that make up the modal but I don't see any z-index specified.
![Elements Screenshot](https://github.com/FraserElectronics/BlazoredModalTest/blob/main/Screenshot/Elements.png)

Andy
