### ISSUE TITLE
Modal breaks app if ASPNETCORE_ENVIRONMENT=Production

### ISSUE THREAD

**Issue by anixon-rdh** [Blazored/Modal#387]
**Describe the bug**
After switching to a launch profile, which sets the ASPNETCORE_ENVIRONMENT=Production, the blazor server application comes to a halt when trying to trigger a modal dialog through the Blazored.Modal component.

**To Reproduce**
1. Open project properties
2. Navigate to Debug -> General
3. Click "Open debug launch profiles UI"
4. Select the default project profile
5. Click "Duplicate selected profile"
6. Select the new profile
7. Change the Environment Variable: replace "Development" with "Production"
8. Close the Launch Profile dialog
9. In the drop down with the Play button, select the new Production launch profile
10. Please Play
11. Press a button that launches a modal dialog.
12. Application crashes, with the general error message at the bottom of the page "An error has occurred. This application may no longer respond until reloaded. Reload"

**Expected behavior**
Modal dialog should appear

**Screenshots**
Default launch profile with environment as Development
![01-WorkingDialog](https://user-images.githubusercontent.com/93688223/153721674-2d97e5a2-1a47-45b3-9807-41228c5a36ad.jpg)

New launch profile with environment as Production
![02-BrokenDialog](https://user-images.githubusercontent.com/93688223/153721676-258194f5-d60f-49a6-9245-9601e9a1abad.jpg)

Console of Broken Dialog
![03-Console](https://user-images.githubusercontent.com/93688223/153721679-31585c89-09e9-44fb-be98-567dbef9228e.jpg)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - I've only tried this with Blazor Server

**Additional context**
My guess is the component is minimifying/bundling the css/js and they can no longer be found at the default content link that we're directed to add to our host page.

To reproduce this:
I created a new Blazor Server project using the built-in template.
I followed the instructions on the home page of the Blazored Modal component. 
I created the production launch profile.

I created a github repository with the above three steps as separate commits.
https://github.com/anixon-rdh/modal-prod-build-issue-sample/tree/main/BlazorApp1/BlazorApp1

**Comment by chrissainty** [comment]
@anixon-rdh Could you turn on detailed exceptions, as advised by the error message in the console. Then report back with what the output is.

**Comment by anixon-rdh** [comment]
![04-DetailedError](https://user-images.githubusercontent.com/93688223/154267167-629db20e-8b98-4105-862f-1cfab5a64dfc.jpg)

**Comment by chrissainty** [comment]
@anixon-rdh Apologies for the delay. I'm sure you've either worked this out now or changed library. But it looks like you're not referencing the JS file in the correct way. Regardless, that file won't be needed in the next release so either way this issue will be resolved.
