### ISSUE TITLE
Cascading parameters should be fixed

### ISSUE THREAD

**Issue by silvavelosa** [Blazored/Modal#393]
**Is your feature request related to a problem? Please describe.**
The new recommended use of the `IModalService` as a cascading parameter instead of injected service could cause a performance overhead, since it's a parameter every single component in the app will receive and process repeated times, even if it's ignored in the end by most of them and doesn't ever change.

**Describe the solution you'd like**
According to [Microsoft](https://docs.microsoft.com/en-us/aspnet/core/blazor/performance?view=aspnetcore-6.0#ensure-cascading-parameters-are-fixed), cascading parameters that won't change should be marked with `IsFixed=true` to avoid the subscription and reprocessing of a value that won't change.

**Describe alternatives you've considered**
The old way, having the `IModalService` injected, instead of as a cascading parameter. But I see the advantages of making it cascading, particularly as it opens the possibility (with some small changes) to have more than one `CascadingBlazoredModal`, each with it's own service (possible solution to #378 , as well as a way to have a different default configuration for modals in different pages/contexts).

**Comment by chrissainty** [comment]
Agreed, @silvavelosa. This will be in the next release.
