### ISSUE TITLE
[Bug] I cloned it started the blazor server sample and all dialogs are rendered left top corner

### ISSUE THREAD

**Issue by PeterPann23** [Blazored/Modal#395]
**Describe the bug**

There is no modal dialog shown, the dialog is render inline using chrome

**To Reproduce**
1. Get latest
2. set Blazor server start up project
3. click any of the samples
4. 
![image](https://user-images.githubusercontent.com/44400822/165455116-4dcbd68c-0839-49cf-8127-b6fe8c85e48a.png)

**Expected behavior**
expect a moal like dialog

**Screenshots**
![image](https://user-images.githubusercontent.com/44400822/165455179-1afa6f02-1f8c-466f-ac21-b882815a29e2.png)
![image](https://user-images.githubusercontent.com/44400822/165455280-603a0c65-ed74-47a1-8c57-f5bb2858be07.png)
Edge and Chrome:
![image](https://user-images.githubusercontent.com/44400822/165455555-80ee371c-1a48-4061-b4a1-19408197d3b4.png)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server
 - Chrome, Edge
 - Windows 11, visual studio 2022

**Additional context**
not sure what I am missing as I made no changes

**Comment by chrissainty** [comment]
Thanks for spotting this @PeterPann23. I've just created a PR to fix the issues.
