### ISSUE TITLE
[Bug] Modal does not show when awaited?

### ISSUE THREAD

**Issue by yggdrasil-tynor** [Blazored/Modal#399]
**Describe the bug**
The Model.Show is async, but Modal's do not show when awaiting the modal. 
The documentation is not very clear about this?

**To Reproduce**
await Modal.Show() - not working
Modal.Show() - working

Should the Modal.Show not be awaited?

**Comment by chrissainty** [comment]
Hi @yggdrasil-tynor,

I'm not sure where you're looking but the `Show` method isn't async as you can see below, it returns a `IModalReference`.

https://github.com/Blazored/Modal/blob/e1b04dedf90e9cfe3d8fb66fa92e9c9dd6372f1a/src/Blazored.Modal/Services/IModalService.cs#L10

**Comment by yggdrasil-tynor** [comment]
@chrissainty sorry, i was mistaken by the name of this project. This was a bug in Blazorise and not tihs
