### ISSUE TITLE
Feature: disable closing modal by clicking on the backdrop

### ISSUE THREAD

**Issue by SalvadorSarpi** [Blazored/Modal#40]
I need to be able to disable the closing of the modal by clicking on the modal backdrop. can I send a PR?
grat component, thanks for your work @chrissainty, this blazor thing is awesome and the stuff you have here too.

**Comment by chrissainty** [comment]
Hi @SalvadorSarpi, sorry for the late reply, I've been on holiday. Yes, that sounds like a great feature and I'd love to receive a PR for it if you're still happy to do it?

**Comment by chrissainty** [comment]
@SalvadorSarpi I've added this feature as I was sorting the upgrade to RC1 and it was only a quick change.
