### ISSUE TITLE
[Bug] Thread Deadlock when testing with bUnit and File Upload

### ISSUE THREAD

**Issue by oatsoda** [Blazored/Modal#402]
**Describe the bug**
Getting a thread deadlock when testing a component with bUnit and the `InputFile` component.  I've logged it with bUnit with a sample to reproduce: https://github.com/bUnit-dev/bUnit/issues/760

Looks like the issue is because the `TaskCompletionSource` should be setting `TaskCreationOptions.RunContinuationsAsynchronously` as per https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#always-create-taskcompletionsourcet-with-taskcreationoptionsruncontinuationsasynchronously

**To Reproduce**
See sample at https://github.com/bUnit-dev/bUnit/issues/760

**Expected behavior**
Not cause a thread deadlock.

**Hosting Model**
Blazor WebAssembly

**Comment by chrissainty** [comment]
Thanks for raising this @oatsoda. I've added the fix per the discussions over at https://github.com/bUnit-dev/bUnit/issues/760
