### ISSUE TITLE
[Bug] Modal dialog is shown behind Leaflet map

### ISSUE THREAD

**Issue by macias** [Blazored/Modal#405]
**Describe the bug**

Well, maybe not a bug per se, but a problem/stopper. When I use modal dialog on a regular or blank page, it works fine. However when I use it on page where I have Leaflet map, the dialog technically is shown, but in such way, that everything except map is grayed out, and the modal dialog is shown behind map.

Just out of curiosity I tried to change z-index of modal dialog to 1, it didn't help. So I deleted map "layer" which resulted in modal dialog being visible, but I couldn't interact with it.

**To Reproduce**

Basically show blazored Leaflet map (https://github.com/Mehigh17/BlazorLeaflet) on the page and then call modal dialog.

**Expected behavior**

Modal dialog is shown in front.

**Screenshots**
![snapshot1](https://user-images.githubusercontent.com/1228047/177627442-cb3d6ddb-dbda-4915-951a-dfbcae21ee10.png)

Left top corner area is grayed out as expected, bottom right map is bright as before (not expected). This is just a portion of the screen, but modal dialog is behind the map so it is not point for sending bigger image.

**Hosting Model (is this issue happening with a certain hosting model?):**

Blazor WebAsm

**Comment by chrissainty** [comment]
Hi @macias, I suspect this is going to be z-index issue. The modals overlay (gray background) has a z-index of 101, Leaflet must use a higher index. 

I'd suggest finding out what Leaflet is using with the browsers dev tools and then upping the z-index of the modal to be above that.
