### ISSUE TITLE
Simplify Structure and Styling

### ISSUE THREAD

**Issue by chrissainty** [Blazored/Modal#409]
# Overview
The current structure of the HTML that makes the modal work is complex. This has lead to weird rendering issues and difficulty for users when trying to implement custom styling. This should be simplified so the problems can be avoided in the future. The downside here is the will be a breaking change for people who have done any type of customisation of the look of the modal. 

As part of this work, we should probably move to isolated CSS. While I'm not a huge fan it does make sense to insulate our styles from those that could be applied by users.

**Comment by adrianwright109** [comment]
Will the modal still support scrollable content?

**Comment by chrissainty** [comment]
@adrianwright109 Absolutely! The difference now is it's native rather than something you have to turn on.
