### ISSUE TITLE
Is there a way to have nested modals ?

### ISSUE THREAD

**Issue by mvr-devs** [Blazored/Modal#41]
Is there a way to have nested modals such that on closing the top most modal the second modal will show back up ?

**Comment by chrissainty** [comment]
Hi @mvr-devs, at this point in time that is not possible - only one modal can be active at a time. What scenario would you like to have two modals active?

**Comment by mvr-devs** [comment]
Awesome Project BTW!  When building LOB apps we will launch a modal for editing an entry that has a related property with a select list drop down, then the user may need to add add a new item to the collection so we give them a button next to the dropdown to launch an editor for the related collection. When they are finished with either adding a new item or editing an existing one, ideally the 2nd modal would be dismissed and the first modal is still there, the code runs and refreshes the dropdown list and they can finish their edit.  We also have a modal that is responsible for displaying audit changes for an entity, it would be nice to let them view the change history and then still be in the  modal...

Thanks !

**Comment by chrissainty** [comment]
Cool! Leave it with me and I'll see what I can do.

**Comment by mvr-devs** [comment]
Awesome Chris!  Thanks !!

**Comment by natsuo** [comment]
I don't know the requirements for your modal, but would it make sense to turn off background-click-cancellation and just toggle the visibility of a "details view"? The details view would be part of the "master view" component (the component that acts like the modal).

With the custom stylings I'm working on in #44, you could make a modal that covers a large part of the view. When you click on the button, toggle visibility on a details view component that renders the parts you need. The details view is centred above the master view, optionally blocking any interactions with the elements below the top-most details view.

View hierarchy would be (from top to bottom)
* Details view
* Obscuring layer (covers the master view / modal and adds a transparent dark background - much like what the modal adds to the rest of the screen)
* Master view (which is what Blazored.Modal is showing)
* Obscuring layer
* Layout/page

The details view and the obscuring layer could be packaged together as a component with it's own delegate callbacks and parameters.

If multiple modals are indeed required: Could one do that by placing a `<BlazoredModal @ref="@DetailsViewModal/>` in the layout file and flipping the switch by referencing that specific modal?

**Comment by kgday** [comment]
Excellent project and your articles on your blog have been extremely helpful. In addition to @mvr-devs the simple case of having a delete confirmation on top of a modal entry form is another scenario where this would be extremely beneficial.

**Comment by Orgbrat** [comment]
I also need this functionality in my Blazor SSA. I am using your Blazored.TextEditor in a modal dialog to create an HTML document but I have an Insert Image button on the editor toolbar that allows me to upload an image to Azure thru my WebApi and then place the returned Azure URL in the HTML img tag src. But I need the Image Upload modal to open on top of the TextEditor modal so that it can create the img tag in the editor while the editor is open.  And I just found out you can not have nested modals.  Oh what a dilemma!

By the way I am using your Blazored projects for many things and they are all excellent projects and your blogs for each one are extremely helpful.  Thanks for all your effort...

Orgbrat
