### ISSUE TITLE
[Bug] App instantly crashes when using modal on a page with an auth redirect

### ISSUE THREAD

**Issue by craigbrown** [Blazored/Modal#416]
**Describe the bug**
I have a Blazor app that uses authentication, so that the user must be logged in to see any page. If they are not, they are redirected to a login screen. When this redirect happens, I get the following exception thrown:

```
Unhandled Exception:
System.ArgumentNullException: Value cannot be null. (Parameter 'jsObjectReference')
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Blazored.Modal.BlazoredModal.ClearBodyStyles()
   at Blazored.Modal.BlazoredModal.CancelModals(Object sender, LocationChangedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.ThreadPool.Callback()
ThreadPool Callback threw an unhandled exception of type System.ArgumentNullException
```

I believe this is due to the use of the `!` (null-forgiving) operator on [line 144 of BlazoredModal.razor](https://github.com/Blazored/Modal/blob/e1ee1164767624fc0c1890a9b23679ad6f34e1fa/src/Blazored.Modal/BlazoredModal.razor#L144):

```csharp
await _styleFunctions!.InvokeVoidAsync("removeBodyStyle");
```

The `_styleFunctions` field isn't set until the `OnAfterRenderAsync()` method runs for the first time, but the auth redirect happens before this.

I'm using the latest preview.

**To Reproduce**
1. Set up a new Blazor app with authentication.
2. Set up Blazored.Modal.
3. Replace `App.razor` with the following:
    ```html
    <CascadingBlazoredModal>
        <CascadingAuthenticationState>
            <Router AppAssembly="@typeof(Program).Assembly">
                <Found Context="routeData">
                    <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)">
                        <NotAuthorized>
                            @if (context.User.Identity?.IsAuthenticated != true)
                            {
                                // If not logged in, redirect to login
                                Navigation.NavigateTo($"authentication/login?returnUrl={Uri.EscapeDataString(Navigation.Uri)}");
                            }
                            else
                            {
                                <p role="alert">You are not authorized to access this resource.</p>
                            }
                        </NotAuthorized>
                    </AuthorizeRouteView>
                </Found>
                <NotFound>
                    <LayoutView Layout="@typeof(MainLayout)">
                        <p>Sorry, there's nothing at this address.</p>
                    </LayoutView>
                </NotFound>
            </Router>
        </CascadingAuthenticationState>
    </CascadingBlazoredModal>
    ```
4. Run the app - when any redirect for login occurs, the exception will be thrown and the app will crash.

**Expected behavior**
The exception should not be thrown.

**Hosting Model (is this issue happening with a certain hosting model?):**
I'm experiencing this issue with Blazor WebAssembly. I don't know if this also affects Blazor Server.

**Comment by chrissainty** [comment]
Thanks for reporting this @craigbrown and writing up such a thorough bug report.

**Comment by craigbrown** [comment]
No problem, thanks for the speedy fix!
