### ISSUE TITLE
[Bug/FeatureRequest] Can't assert modal exceptions in BUnit tests

### ISSUE THREAD

**Issue by brettwinters** [Blazored/Modal#430]
Consider the below 'pseudocode' of a modal which throws an exception during OnInitialized(). I'm unable to catch this exception in my (BUnit) unit tests. Any idea why not?

The `reference.Result.Status` shows "WaitingForActivation" and trying to `await reference.Result` just hangs. Actually this is generally a problem for unit tests since I never know if the modal has crashed. The only evidence is that the modal content is not displayed or via the `Result.Status`

```c#
@inject IModalService ModalService

<div>
    My modal
</div>

@code {
   [CascadingParameter] BlazoredModalInstance BlazoredModal { get; set; } = default!;

   protected override void OnInitialized()
   {
        base.OnInitialized();
        throw new ArgumentException();
    }
}
```

The (failing) unit test : 

```c#
[Fact]
public void ShouldThrowArgumentException(
{
    var modalService = Services.GetService<IModalService>();
    var _ = RenderComponent<BlazoredModal>(CascadingValue(modalService));

    Assert.Throws<ArgumentException>(() =>
        modalService.Show<TestComponent>(
	    title: "",
	    parameters: new ModalParameters()
        )
    );
}
```

result : 

```log
Xunit.Sdk.ThrowsException
Assert.Throws() Failure
Expected: typeof(System.ArgumentException)
Actual:   (No exception was thrown)
```

.net6.0
Bunit
Blazor WASM

**Comment by chrissainty** [comment]
Hi @brettwinters. This is an interesting one. I'll need to have a look into what's happening here. What version of the package are you using? If you haven't already, can you try the latest preview version?

**Comment by brettwinters** [comment]
Hi @chrissainty 

I was using `6.0.1` but upgraded to `7.0.0-preiew.4` as you suggested. Unfortunately, it hasn't solved the issue. 

Interestingly enough, this 'hack' works. Could it be that we need an `ShowAsync` overload? 

```c#
[Fact]
public void Test()
{
	Assert.ThrowsAsync<ArgumentException>(async () => 
		_modalService.Show<TestModal>(
			title: "my title",
			parameters: new ModalParameters()
		)
	);
}
```

I don't think it's a BUnit issue since this also doesn't work

```c#
[Fact]
public void Test()
{
	try
	{
		_modalService.Show<TestModal>(
			title: "my title",
			parameters: new ModalParameters()
		);
		Assert.Fail("");
	}
	catch (ArgumentException)
	{
	}
}
```

Just for my own sanity, I also confirmed that normal components don't have any issues...

**Comment by brettwinters** [comment]
Solved using `ExpectedException` attribute in the `Microsoft.VisualStudio.TestTools.UnitTesting` namespace

```c#
[Fact]
[ExpectedException(typeof(ArgumentException))]
public void Test()
{
    _modalService.Show<SomeModal>(...)
}

```
