### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by CrahunGit** [Blazored/Modal#432]
**Is your feature request related to a problem? Please describe.**
It would be nice to update parameters inside modal wrapped component when parent parameters changed

**Describe the solution you'd like**
If I open a modal that loads a component to show a value I would like to see updated parameters when the parent one changes it.

**Describe alternatives you've considered**
Currently I need to close and reopen modal to see new values.

**Comment by chrissainty** [comment]
Hi @CrahunGit, thanks for suggesting this feature. I don't think this is something I would look to implement. It feels very niche and I don't understand your suggested usecase. How would the parent update the value when the modal has focus? 

Based on the above I'm going to close this as a won't implement. Sorry.
