### ISSUE TITLE
Hello Chris! What to do if I want to simply create a style to set a Height and a Width feature to the modal and simply use that?

### ISSUE THREAD

**Issue by laxedo17** [Blazored/Modal#446]
I managed to add the Size to a modal, added some CSS and it works. What a mate asked me is to have an option to simply show a Width and a Height in the modal component, like when you use the typical style "hack" and set the width and height easily.

How could it be possible?

I admire your work and even purchased your book from Manning a few weeks ago. Also I used your LocalStorage library quite a few times... Have a great day Chris.

**Comment by chrissainty** [comment]
Hi @laxedo17,

I think you're looking for the custom size setting (https://blazored.github.io/Modal/configuration/size#using-a-custom-size). Outside of this I don't want to add any additional sizing options. The current options allow pretty much any option to be implemented.
