### ISSUE TITLE
[Bug] After upgrading to 7.0, you get a Microsoft.JSInterop.JSDisconnectedException when 'unloading' the app

### ISSUE THREAD

**Issue by Schoof-T** [Blazored/Modal#447]
**Describe the bug**
After upgrading to 7.0, when the app becomes unloaded (an unhandled exception occurs, you navigate out of the application...) you now get a JSInterop exception:

> Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'xvYrH0rxATtOQ2NEdAIpOBnmmBmUMjyWx0Sv_xFkUa0'.
> 
> Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.

**To Reproduce**
1. Create a new Blazor Server project
2. Add and configure Blazored.Modal
3. Add a href to any page. E.g. `<a href="https://www.google.com">google</a>`
4. Run the App
5. Click the href
6. See the error in your output

**Expected behavior**
The error should not happen

**Screenshots**
![image](https://user-images.githubusercontent.com/2319986/191783776-08f3f24c-1a94-4059-bbb9-3d72bbbe6acf.png)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Additional Information**
Might have something to do with the following: https://github.com/dotnet/aspnetcore/issues/33336

**Comment by chrissainty** [comment]
Hi @Schoof-T, I've tried a couple of times now and I can't seem to repro the issue using the steps you provided.

**Comment by reiluke** [comment]
I have the same issue, everytime i refresh i get 2 exceptions in javascripts, this is in version 7, did not notice in version 6, see attached new blazor just added blazor modal
[BlazorApp1.zip](https://github.com/Blazored/Modal/files/9782814/BlazorApp1.zip)

**Comment by chrissainty** [comment]
Hi @reiluke, once again that isn't reproing. I'm think this could be a caching issue. Have you cleared your cache? This is almost certainly a local issue of some kind.

**Comment by reiluke** [comment]
Hi Chris, but its a new project, attached at the bottom BlazorApp1 
once the project is loaded in the browser, i press refresh there's 2 exception

![events](https://user-images.g
![exceptions in server](https://user-images.githubusercontent.com/37175362/195785080-11d9b8a5-9913-4026-ae85-684c689345d9.png)
ithubusercontent.com/37175362/195784709-b505918c-3c6c-4fbd-83af-1e8f24ef9d90.png)

**Comment by chrissainty** [comment]
I don't know what to tell you, I've ran your project and refreshed and there are no errors. I'm not dismissing this but I can't do fix something that doesn't repro. If you can find something I can Action then I'll happily take a look.

**Comment by depauwniels** [comment]
I have the same issue, made a completely new project and also encounter the 2 javascript errors.
[BlazorModalTest.zip](https://github.com/Blazored/Modal/files/9783699/BlazorModalTest.zip)

To reproduce, go to the counter page and press the "test" link. When the page opens you can see the 2 interop errors in the output.
![image](https://user-images.githubusercontent.com/9309997/195792332-bcf447dc-51bb-458d-8158-4ec4356a216b.png)

I followed the steps on this page to create my project:
https://blazored.github.io/Modal/

**Comment by reiluke** [comment]
I debug the code and the exception is here, line 157, at first run its called only once, _stylefunction is null, if i refresh it, its called twice, first one its null, 2nd one is not null so i call dispose then exception occurs

 ```
  async ValueTask IAsyncDisposable.DisposeAsync()
    {
     
            if (_styleFunctions is not null)
            {
                await _styleFunctions.DisposeAsync();
            }
        
    }
```
removing await fixed my excception
```
  async ValueTask IAsyncDisposable.DisposeAsync()
    {
        if (_styleFunctions is not null)
        {
             _styleFunctions.DisposeAsync();
        }
    } 
```

**Comment by chrissainty** [comment]
@reiluke @Niels-DP What version of .NET are you running?

**Comment by Niels-DP** [comment]
@chrissainty .NET 6.0

**Comment by reiluke** [comment]
> @reiluke @Niels-DP What version of .NET are you running?

.Net 6.0

**Comment by Schoof-T** [comment]
I am also using .NET 6.0

**Comment by chrissainty** [comment]
Ok, I can see the issue and I'll get a fix in place. What I still can't understand is why I can't get the error locally. Anyway, I appreacite the help figuring this one out
