### ISSUE TITLE
Possible to "plug in" other modal libaries?

### ISSUE THREAD

**Issue by UweKeim** [Blazored/Modal#450]
Currently I'm planning on using [DxPopup](https://demos.devexpress.com/blazor/Popup) in my Blazor WASM application.

Still, the concept of your Modal library looks awesome to me.

I'm now searching for a way to adapt your library to work with DxPopup.

The most promising approach seems to me to simply look through the source code of your library and do the same things in my Blazor WASM application.

Of course, I would lose the ability to automatically get future updates of your library.

Therefore it would be cool to have kind of a "pluggable" actual popup implementation, although I do think this would be way over the top.

### My question

Can you give me any hints on how I could implement my requirements together with your Modal library?

**Comment by chrissainty** [comment]
Hi @UweKeim, I don't see the value in what you're suggesting. If you want to use DevExpresses modal then just use that. I'm not sure what you're gaining (other than a lot of complexity) by trying to combine the two. 

I don't want to waste your time here so this isn't something I would be interested in adding to the library.
