### ISSUE TITLE
[BUG] Modal No Longer Opens After Update

### ISSUE THREAD

**Issue by jcantrel** [Blazored/Modal#454]
After updating to version 7.0 my Modals are now opening at the top of the window instead of a new layer.

Version 7.0
![image](https://user-images.githubusercontent.com/37300313/193584633-dbd9ff92-1607-4ec2-97e5-1ccbc6158829.png)

Pre-7.0
![image](https://user-images.githubusercontent.com/37300313/193584740-0d9073e9-e4fc-4305-b7d6-2a1a6ff4afe8.png)

```
private async void showModal(short locationID)
    {
        IModalReference formModal = Modal!.Show<BatchHeaderLocationDialog>("", ReturnParameters(locationID), Helpers.StandardModalOptions());
        ModalResult result = await formModal.Result;
        if (!result.Cancelled)
        {
            isLoading = true;
            await grid.Reload();
            isLoading = false;
            StateHasChanged();
        }
    }
private ModalParameters ReturnParameters(short locationID)
    {
        ModalParameters parameters = new ModalParameters();
        parameters.Add("Location", locationID);
        return parameters;
    }
internal static ModalOptions StandardModalOptions()
        {
            ModalOptions options = new()
            {
                HideHeader = true,
                HideCloseButton = true,
                DisableBackgroundCancel = true,
                Position = ModalPosition.Middle
            };
            return options;
        }
```

**Comment by jcantrel** [comment]
After further testing I see this error message in the console, but I checked and my set up still matches the Getting Started page in the documentation.

![image](https://user-images.githubusercontent.com/37300313/193589406-8c65791a-8879-457f-8fbe-8bd9ac52b029.png)

**Comment by as-srandall** [comment]
I experienced that too. I had to roll back to 7.0.0.pieview.2

**Comment by chrissainty** [comment]
Hi @jcantrel,

Can you provide a repro project? I'm guessing this could be an error in setting up Blazored Modal as `blazored.moidal.js` doesn't exist anymore so your project shouldn't be trying to load it.

**Comment by digitalsigi** [comment]
Same here. Unforutnately a big project with SQL Service behind, so providing a repro is not feasable

**Comment by digitalsigi** [comment]
> Same here. Unforutnately a big project with SQL Service behind, so providing a repro is not feasable

Installing 7.0.0.prieview.2

**Comment by chrissainty** [comment]
@digitalsigi This is most likely a local issue within your application. As you can't provide a repro I'm going to close the issue. If you do manage to create one I'll take a look.

**Comment by LoupaLoupa** [comment]
I had the same issue and I was able to fix it by using !important to the display: flex in the css class we pass to the modal when it it created using options.PositionCustomClass =  admin-modal-overlay

where

    .admin-modal-overlay {
        display: flex !important;
        z-index: 1300;
        align-items: center;
        justify-content: center;
    }
