### ISSUE TITLE
[Bug] Parameter ContentScrollable missing in V7.0.0

### ISSUE THREAD

**Issue by digitalsigi** [Blazored/Modal#458]
**Describe the bug**
Options Parameter ContentScrollable is missing in V7.0.0, but still available in 7.0.0-preview2

**To Reproduce**

var opts = new ModalOptions(){ContentScrollable =true};

**Expected behavior**
ContentScrollable schould be available or some migration description

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Comment by chrissainty** [comment]
Hi @digitalsigi, this option is not missing, it's been removed, With the new styling a scrollbar will automatically appear when content extends past the viewport making the old setting obsolete.
