### ISSUE TITLE
[Bug] Modal rerender for every keyup/keydown event

### ISSUE THREAD

**Issue by BeyondDefinition** [Blazored/Modal#459]
**Describe the bug**
When using `[CascadingParameter] ModalInstance`, apparently the [onkeyup and onkeydown](https://github.com/Blazored/Modal/blob/v7.0.0/src/Blazored.Modal/FocusTrap.razor#L1) handlers in FocusTrap sets the CascadedValue every time any keyup/keydown DOM event is generated in a child component, which rerenders the component twice for every key press.

This causes OnParametersSet to be called in Typeahead. If you remove these 2 event handlers, the Typeahead component also works as intended. See https://github.com/Blazored/Typeahead/issues/288

It does seem to generate some overhead. Perhaps it's possible to disable event propagation?

**To Reproduce**
1. Create new VS project.
2. Follow the [guide](https://blazored.github.io/Modal/) to add Modal
3. Make sure to add `[CascadingParameter] ModalInstance` and manually implement the getter + setter.
4. Trace the calls to the setter, for example with a breakpoint or `Debugger.Log`.

**Expected behavior**
Rerender only when the component state has actually changed, not twice for every key press.

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Comment by chrissainty** [comment]
Thanks for opening this issue @BeyondDefinition. I think the solution to this is pretty simple, currently the `BlazoredModalInstance` value that is cascaded down isn't fixed. I've just done a quick test and it look like setting it to fixed will resolve this.

```razor
<CascadingValue Value="this" IsFixed="true">
    @Content
</CascadingValue>
```

**Comment by BeyondDefinition** [comment]
That indeed solves it! Thanks!
I wish it was always as easy as adding `IsFixed="true"` to fix an issue!
Can you please include this improvement in the next release?
