### ISSUE TITLE
Blazored.Modal.bundle.scp.css not showing up when building with VS Code

### ISSUE THREAD

**Issue by kellyrmartin** [Blazored/Modal#462]
### Discussed in https://github.com/Blazored/Modal/discussions/452

<div type='discussions-op-text'>

<sup>Originally posted by **kellyrmartin** September 29, 2022</sup>
Hey Everyone

I just added Blazored Modal to my project. When I run it from VS Code the css doesn't seem to be showing up in the _content folder. However when I run the same project in Visual Studio it does. Here are a couple of screen shots.

I saw the post on css isolation but that line was in my project already.

VS Code
![image](https://user-images.githubusercontent.com/3556384/193158832-10d97bef-e19a-4d56-9767-74ad07db6ec9.png)

Visual Studio
![image](https://user-images.githubusercontent.com/3556384/193158886-7050ab02-d172-480d-8ca9-78d5a1b3f224.png)

</div>

**Comment by chrissainty** [comment]
Hi @kellyrmartin, I'm going to clsoe this as it appears to be something external to this library (VS Code by the looks of it). There isn't anything I can do here.
