### ISSUE TITLE
[Bug] Events can instantiate multiple modals. Intended?

### ISSUE THREAD

**Issue by haakonfp** [Blazored/Modal#467]
I have a modal that is shown when an Action is invoked in a recurring async function. It will show multiple modals layered on top of each other, if the original is not removed before the function reoccurs.

For example, I have a function that uses an API call every 60 seconds to check for an application update. If there is a new update available, I want a modal to show. I have simplified the code a bit for illustratory purposes, by removing the actual API call and just adding the invoke (simulating a response if an update is available).

```cs
public event Action? OnNewUpdateAvailable;

public async void CheckForUpdateAsync()
{
    var timer = new PeriodicTimer(TimeSpan.FromSeconds(60));
    while ( await timer.WaitForNextTickAsync() ) { OnNewUpdateAvailable?.Invoke(); }
}
```

This will show a new modal every 60 seconds, and if you do not close the previous, the new will show up either in front or behind the other. I assume, although I have not tried, that the same would happen if you have a loop or similar logic that instantiates multiple modals.

I have solved this myself with a simple bool state, but I was wondering if this was actually intended behavior? To be fair, it could be useful if you have different types of modals that pop up on certain events, and want the user to see all of them sequentially.

I have reported it here, since the specific documentation on using multiple modals does not discuss this as an option (of queued modals). So not sure if this is a bug, or if this should be handled by the library user. Thoughts?

**Comment by haakonfp** [comment]
While having multiple modals is not necessarily an issue in all cases, the background overlay gets applied each time. This creates a less and less transparent overlay, which may not be ideal.

**Comment by chrissainty** [comment]
Hi @haakonfp, this is the expected behaviour in this situation and by design. My immediate thought here is why you would want a modal in this situation? Is the modal allowing the user to perform an action of some kind? Or it is just informational?
