### ISSUE TITLE
Full Content Page???

### ISSUE THREAD

**Issue by normanlc** [Blazored/Modal#476]
Is there going to be a sample for "FullContentPage.razor" being utilized?

**Comment by chrissainty** [comment]
What do you want to see from that sample?

**Comment by normanlc** [comment]
I'm looking for a sample of utilizing the Blazored/Modal to display/show a dialog with a form on it so that data entry can be used. I saw the file "FullContentPage" but did not see it used in the downloaded example. Did I miss something?

**Comment by normanlc** [comment]
I'm looking for a sample of utilizing the Blazored/Modal to display/show a dialog with a form on it so that data entry can be used. I saw the file "FullContentPage" but did not see it used in the downloaded example. Did I miss something?

**Comment by LePtitJoNadeau** [comment]
I think it could be good to have a sample of a spinner with overlay that doesn't display the size of modal.

What do you think about that?
