### ISSUE TITLE
Option to have Modals not close when a page navigation occurs

### ISSUE THREAD

**Issue by TravisNorwood** [Blazored/Modal#477]
We use Blazored Modal to show a busy spinner modal (to prevent user for doing anything while processing server side). We'd like this to keep going until the new page shows. So we need it to not go away on NavigationManager.LocationChanged

**Comment by chrissainty** [comment]
Hi @TravisNorwood. Can you please use the correct issue template when opening an issue as this really helps with the administration of the project.
