### ISSUE TITLE
Closing a modal causes page to scroll down to previous position from top

### ISSUE THREAD

**Issue by nicolaidanekov** [Blazored/Modal#479]
Hey there!

I am having some issues where closing a modal causes the page to visually go to top and then scroll down to the previous scrolled location.

Is this an issue you have experienced before or have an idea how to fix? :)

Best regards, 
Nicolai

**Comment by emilg** [comment]
Do we have any updates on this?

I saw that this was also discussed in another issue: https://github.com/Blazored/Modal/issues/354#issuecomment-1159249498

What is the status on this? The behavior of the modals is very frustrating for users as it keeps restarting at the top. When you work with for example lists, it's almost impossible to know which line you where working on when the scroll keeps working this way.

Any workarounds?

**Comment by chrissainty** [comment]
I believe this is fixed in new versions so I'm going to close
