### ISSUE TITLE
Modal display issue after upgrade to 7.0

### ISSUE THREAD

**Issue by weiihnachtsmann91** [Blazored/Modal#490]
**Describe the bug**
Modal not displaying right after upgrade to version 7.0.0 ( works fine with version 6.0).

**Expected behavior**
Should look a like when upgraded

**Screenshots**
Blazored.Modal Version 6.0.0 (what it should look like)
![blazoredModal60](https://user-images.githubusercontent.com/82328873/212475025-e3e5bd94-a411-4dfa-b15d-ea5a3a1ec377.jpg)

Blazored.Modal Version 7.0.0
![blazoredmodal70](https://user-images.githubusercontent.com/82328873/212475022-c941197e-ab76-48b8-8d0f-e13b12c6f7dd.jpg)
**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly

**Additional context**
Is there anything I'm missing?

Thank you and have a nice day,

Herbert

**Comment by chrissainty** [comment]
Gonna need something more to go on here. Two screenshots really doesn't help much without some code to put it into context.

**Comment by weiihnachtsmann91** [comment]
I got it, 
my main problem was to include 
`<link href="{YOUR APP ASSEMBLY NAME}.styles.css" rel="stylesheet">`
to my index.html, since css isolation wasn't mandatory for the previous version.
Thank you anyway for your time!
