### ISSUE TITLE
ModalPosition.Middle problem when modal height exceeds window height

### ISSUE THREAD

**Issue by Jimmys20** [Blazored/Modal#491]
Hello, when a modal has `Position = ModalPosition.Middle`, if the height of the modal exceeds the height of the browser window, then it's impossible to scroll to the top of the modal. I scroll to the top of the page but there is still more content that stays hidden at the top of the window.

**Comment by chrissainty** [comment]
Can you provide a repro of the issue otherwise there is nothing I can do.

**Comment by Jimmys20** [comment]
Yes. https://github.com/Jimmys20/BlazoredModalIssues491

**Comment by SSchulze1989** [comment]
Can confirm I have the same problem. Any modal with Position=Middle will not scroll to the top.

**Comment by giarico** [comment]
I also confirm I have the same issue

**Comment by emilg** [comment]
+1.

We updated to the latest version to overcome the previous scroll issue. Now we have this problem instead..
