### ISSUE TITLE
[Bug] Uncaught SyntaxError: Unexpected token '<' (at blazored.modal.js:1:1)

### ISSUE THREAD

**Issue by nssidhu** [Blazored/Modal#494]
Uncaught SyntaxError: Unexpected token '<' (at blazored.modal.js:1:1)

![image](https://user-images.githubusercontent.com/3267605/215341144-075cfc73-f1b5-4f9b-b371-abb79a4639c6.png)

`<PackageReference Include="Blazored.Modal" Version="7.1.0" />`

======================================================================================

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server
 - Blazor WebAssembly
 - etc...

**Additional context**

**Comment by chrissainty** [comment]
I'm being much stricter from now on with bug reports that don't have repro steps. Hence closing due to lack of info.
