### ISSUE TITLE
IModalService Modal - why Modal is null?

### ISSUE THREAD

**Issue by ZedZipDev** [Blazored/Modal#497]
VS2022 WebAssembly NET 6
I try to add modal dialog to my app. Do as it is in your sample.
1. Added Nuget
2. Added using to _Imports.razor
@using Blazored.Toast
@using Blazored.Toast.Services
@using Blazored.Modal
@using Blazored.Modal.Services

3. Program:
builder.Services.AddBlazoredToast();

That is my razor component

`@page "/login"
<h1>Passing Data to a Modal</h1>
<hr class="mb-5" />
<p>
    Data can be passed to a modal by using the <code>ModalParameters</code> object. The items you add to this collection must match the parameters
    defined on the component being displayed in the modal. In the example below, you can type a message and see it displayed in the modal.
</p>
<div class="form-group">
    <label>Enter a message</label>
    <input class="form-control" type="text" @bind="_message" />
</div>
<button @onclick="ShowModal" class="btn btn-primary">Show Modal</button>
@code {
    [CascadingParameter] public IModalService Modal { get; set; } = default!; //<--Modal is null!
    string _message = "";
    void ShowModal()
    {
        var parameters = new ModalParameters
        {
            { nameof(DisplayMessage.Message), _message }
        };

        Modal.Show<DisplayMessage>("Passing Data", parameters);
        _message = "";
    }
}`

 There is     [CascadingParameter] public IModalService Modal { get; set; } = default!; //<--Modal is null!

How to fix it?

**Comment by chrissainty** [comment]
When raising a bug please use the bug template provided and provide a repro showing the issue. I'm closing any issues which don't follow this as it's taking up a huge amount of my time.

**Comment by ZedZipDev** [comment]
Thank you very much. But note: you closed it but it is not resolved....

**Comment by chrissainty** [comment]
It's a label I use when closing an issue which I won't work on. Which this is. If you open an issue in the correct way then I will look at that one.

**Comment by ZedZipDev** [comment]
ok, thank you, sorry. Do the 2nd attempt
