### ISSUE TITLE
[Bug] Closing a modal dialog with a button refreshes the page

### ISSUE THREAD

**Issue by paleocomburo** [Blazored/Modal#500]
**Describe the bug**
When I open a modal dialog in my Blazor WebAssembly app, and I click a button that is supposed to close the dailog (for example: Ok, or Cancel), the page refreshes.
If I use the "X" in the top-right to close the dialog no page efresh happens.

**To Reproduce**
1. Create a new Blaxor WebAssembly (ASP.NET Core hosted) application.
2. Add Blazored.Modal as described in the documentation here: https://blazored.github.io/Modal/
3. Add a simple new component to use as the dialog. I based mine off the example giving in the documentation here: https://blazored.github.io/Modal/usage/passing-data
4. Update the Index page to have a way to open the modal dialog.
5. Open the modal dialog.
6. Click the "Close" button.
7. See the page refresh.

**Expected behavior**
I expect the page not to refresh after I close the modal dialog.

**Screenshots**

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly with ASP,NET Core hosting.

**Additional context**
Uisng .NET 7
Blazored.Modal 7.1.0

The component I added to test:
``` C#
<div class="m-2">
    <form>
        <p><b>Test</b></p>

        <button @onclick="Close">Close</button>

</form>
</div>

@code {
    [CascadingParameter]
    BlazoredModalInstance BlazoredModal { get; set; }

    private async Task Close() => await BlazoredModal.CloseAsync();
}
```

The Index.razor page:
``` C#
@page "/"

<PageTitle>Index</PageTitle>

Blazored modal test.

<button @onclick="@(() => Modal.Show<TestComponent>("Test"))">Test</button>


@code {
    [CascadingParameter] public IModalService Modal { get; set; }
}
```

A full solution with the repro can be found in this repo: https://github.com/paleocomburo/blazor-modal-refresh-repro

**Comment by paleocomburo** [comment]
I have also added the complete solution I created for the repro.

[BlazorModelRefresh.zip](https://github.com/Blazored/Modal/files/10698968/BlazorModelRefresh.zip)

**Comment by chrissainty** [comment]
@paleocomburo Thanks for the info. Would you mind removing the zip file and linking to a repo instead. I had an incident with a file attachment so I have a zero trust policy with them now.

**Comment by paleocomburo** [comment]
Yeah, no problem.
I have updated the issue and replaced the zip file with a link to the repo.
This also gave me the oppertunity to check the repro on my personal PC. I posted the issue from my work laptop, where I have Visual Studio Enterprise, and use Google Chrome for testing. On my personal PC I have Visual Studio Community and use Microsft Edge. Same result.

**Comment by paleocomburo** [comment]
I did some digging on my own. I'm not that knowledgable about Blazor, but I did find a line of code that causes the refresh for me.

In `Blazored.Modal.BlazoredModalInstance`, the function
``` C#
public async Task CloseAsync(ModalResult modalResult)
```
contains an `await Task.Delay(400);`. This causes the reload.
If I comment out that line, I have no refresh. If I move the line to the top of the function, so it's the first line that gets executed, my break-point at the "if" statement below it is not triggered (while it is with the delay on the original position).

I don't (yet) understand why this causes the refresh, but I will dig further.

**Comment by paleocomburo** [comment]
Ok, figured it out. I need to add an `preventDefault` attribute the event handler. For instance: `@onclick:preventDefault`.

This may be new to .NET 7 Blazor? I had a working app on .NET 6, but now I migrated to .NET 7 this has become an issue all of a sudden.
This should probably be reflected in the documentation for this project.

**Comment by chrissainty** [comment]
You shouldn't need to do that. Sorry I haven't had time to look at this yet.

**Comment by paleocomburo** [comment]
No worries. I have a workaround that works.

**Comment by Jimmys20** [comment]
@paleocomburo, the reason the page refreshes is because the button is inside a form element and when you click it submits the form. The default type for buttons inside forms is type="submit". You  need to specify type="button" to your button so that is doesn't submit the form. @onclick:preventDefault also worked because it prevented the default button behavior which is to submit the form.

**Comment by chrissainty** [comment]
Thanks @Jimmys20!

**Comment by paleocomburo** [comment]
I am curious if this behaviour did change between .NET 6 and .NET 7. Because I have an existing application, that I upgraded from .NET 6 to .NET 7 (and then also upgraded the Blazored Modal library), which started having the refresh behaviour after the upgrade. Before it worked fine.

**Comment by chrissainty** [comment]
The behaviour @Jimmys20 mentioned is the default behaviour of HTML, I don't see changes in .NET 6 to .NET 7 effecting this. All I'd say, is if this didn't cause a full page refresh in a previous version, that was the bug. What is happening now is what should happen.

**Comment by Jimmys20** [comment]
The page refresh did not happen with `Blazored.Modal` version 6.0.x. My wild guess is that the js focus-trap that was being used in 6.0.x stopped the propagation of click events inside the modal. `Blazored.Modal`  version 7.0.x now uses a native focus trap implementation. I agree that the current behavior is the correct one.
