### ISSUE TITLE
Strange bar appears screen wide in Firefox

### ISSUE THREAD

**Issue by pablopioli** [Blazored/Modal#501]
**Describe the bug**
When you open a modal in Firefox an addicional full width bar is shown

**To Reproduce**
1. Ejecute the included samples (Server or WASM, it's the same)
2. Click on 'Show Modal'

**Screenshots**
![modal screenshot](https://user-images.githubusercontent.com/15127047/221381259-537d4434-157b-48bf-93cc-d68cb0d31662.jpg)

**Additional context**
This doesn't happen on Chromium browsers, it appears to be a problem in Firefox render engine. I tried to inspect the additional artifact but it disappears when you open the browser tools (F12)

**Comment by LePtitJoNadeau** [comment]
I have the same behavior

**Comment by pablopioli** [comment]
Closed as new versions of Firefox does not have this problem

**Comment by LePtitJoNadeau** [comment]
Good job, thank you!
