### ISSUE TITLE
CustomSize option does not work with Position option properly.

### ISSUE THREAD

**Issue by a13864** [Blazored/Modal#505]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server
 - Blazor WebAssembly
 - etc...

**Additional context**

**Comment by chrissainty** [comment]
Please fill out the template for new issues. Closing as this is incomplete.

**Comment by a13864** [comment]
var options = new ModalOptions { Size = size };

        if (size == ModalSize.Custom)
        {
            options.SizeCustomClass = "my-custom-size";
            options.Position = ModalPosition.Middle;
        }

        Modal.Show<Confirm>($"Size: {size}", options);

options.Position is not working with custom size option together.
