### ISSUE TITLE
Wrong path while loading BlazoredModal.razor.js

### ISSUE THREAD

**Issue by GoceBogdanovski** [Blazored/Modal#507]
The './' is trying to load this resource from the current working directory and it results in 
**Unhandled exception rendering component: Failed to fetch dynamically imported module: 
http://localhost:{port}/dir1/dir2?{query_string} and appended '_content/Blazored.Modal/BlazoredModal.razor.js'**

https://github.com/Blazored/Modal/blob/efd11bbe6f994aff1c7072853d98a35cfe5c3bc6/src/Blazored.Modal/BlazoredModal.razor#L70

**Comment by shekhov** [comment]
Also got this error, but got to it differently. I have a project that starts IIS Express and the appsettings are loaded depending on ASPNETCORE_ENVIRONMENT variable. When it is set to Development, everything works. But as soon as I load the project with Test or Production, I get this message.

**Comment by chrissainty** [comment]
I'm not sure what to suggest here, as stated by the official docs:

> The path segment for the current directory (./) is required in order to create the correct static asset path to the JS file.

**Comment by GoceBogdanovski** [comment]
> I'm not sure what to suggest here, as stated by the official docs:
> 
> > The path segment for the current directory (./) is required in order to create the correct static asset path to the JS file.

It is an embedded Blazor application that is loaded in another application, for example on URL http://domain.com/page1/page2?param_one=2&param_two=3, and the library is setting the path to the BlazoredModal.razor.js like this:
http://domain.com/page1/page2?param_one=2&param_two=3./_content/Blazored.Modal/BlazoredModal.razor.js

**Comment by chrissainty** [comment]
I use this package in embedded Blazor apps and I don't see this issue. I'm not saying there isn't one but I can't fix what I can't replicate. Can you make a repro for this?

**Comment by chrissainty** [comment]
Ok. I'm sorry but I'll have to close this as I can't fix a problem I can't replicate. If you find a way to replicate it then please feel free to reopen the issue.
