### ISSUE TITLE
[Feature Request] Change parameters after modal is shown

### ISSUE THREAD

**Issue by Jimmys20** [Blazored/Modal#513]
Hello, we can pass data to the modal using `ModalParameters` that the Show method accepts. Is it possible to change the parameters while the modal is visible?

**Comment by LoupaLoupa** [comment]
You can pass your value type inside a class, the object will be immutable, but the values inside can change.

**Comment by chrissainty** [comment]
This isn't possible and I don't think it's something we'd change. There are a few options you could use to achieve this like state management or some form of event.
