### ISSUE TITLE
This dialog is not working  in WebAssembly

### ISSUE THREAD

**Issue by bsdnetpl** [Blazored/Modal#519]
WebAssembly there is no _Host.cshtml file.
Where should I add:
 **blazored-model.css**
and
**blazored.model.js**
So that the dialogue works properly.

**Comment by chrissainty** [comment]
The setup instructions for the package are covered on the docs site (https://blazored.github.io/Modal/).

**Comment by bsdnetpl** [comment]
It doesn't add anything. My question is where should I add these two entries:
   <link href="_content/Blazor.Model/blazored-model.css" rel="stylesheet">
     <script src="_content/Blazor.Model/blazored.model.js"></script>
Because there is no file in my project : _Host.cshtml

**Comment by chrissainty** [comment]
You don't need to add those things, that's why they're not specified in the docs. They are added automatically. If you follow the setup steps, everything is setup for you.
