### ISSUE TITLE
Pressing Cancel Button for the second time returns ModalResult.Confirmed = true

### ISSUE THREAD

**Issue by ankerfisch** [Blazored/Modal#520]
**Describe the bug**
I'm invoking a modal using this code.

var parameters = new ModalParameters();
parameters.Add(nameof(EditTrackAndTrace.TrackItem), trackItem);
var editForm = Modal.Show<EditTrackAndTrace>("Bearbeiten", parameters);
var modalResult = ModalResult.Cancel();
modalResult = await editForm.Result;
if (modalResult.Confirmed)
{
   Do something
}

The modal looks like this:
![image](https://github.com/Blazored/Modal/assets/82159081/f17ffbd8-3f22-49e2-9201-c58d861f7eb9)

When first invoking the modal an pressing the Cancel button, the ModalResult.Confirmed is false, which is correct.
Invoking the modal again and pressing the Cancel button again, the ModalResult.Confirmed is true, which is incorrect.

**To Reproduce**
1. invoke modal
2. click on cancel button
3. invoke modal again
4. click on cancel button

**Expected behavior**
The ModalResult.Confirmed should always be false

**Screenshots**

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Additional context**

**Comment by chrissainty** [comment]
Can you add `type="button"` to your cancel button. By default, buttons have a type of submit and I think when you're pressing cancel it's submitting the form and you're seeing a weird race condition. 

If that's not the issue please feel free to reopen the issue.

**Comment by ankerfisch** [comment]
Chris,

thank you. Problem resolved.

Kind Regards,

Michael

Mit freundlichen Grüßen,

Michael Steffen
ANKER GmbH Fisch- u. Feinkostfabrik
Gewerbestraße 6 * DE – 23942 Dassow
T. 49(0)38826/821-0 * F. 49(0)38826/821-99
E. ***@***.******@***.***> * I. www.anker-fisch.de<http://www.anker-fisch.de>
Geschäftsführer: Michael Steffen
HRB 4547 Amtsgericht Schwerin

Diese elektronische Nachricht enthält vertrauliche und/oder rechtlich geschützte Informationen, die nur für den Empfänger bestimmt sind. Wenn Sie nicht der richtige Adressat sind oder diese Nachricht irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Nachricht. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Nachricht ist nicht gestattet.
This e-mail may contain confidential and/or privileged information, which is intended for the recipient only. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: Chris Sainty ***@***.***>
Gesendet: Dienstag, 20. Februar 2024 01:09
An: Blazored/Modal ***@***.***>
Cc: Michael Steffen ***@***.***>; Author ***@***.***>
Betreff: Re: [Blazored/Modal] Pressing Cancel Button for the second time returns ModalResult.Confirmed = true (Issue #520)


Can you add type="button" to your cancel button. By default, buttons have a type of submit and I think when you're pressing cancel it's submitting the form and you're seeing a weird race condition.

If that's not the issue please feel free to reopen the issue.
