### ISSUE TITLE
[Suggestion] Rename FocusTrap component

### ISSUE THREAD

**Issue by k-schneider** [Blazored/Modal#521]
My solution already had a custom FocusTrap component defined and when adding Blazored.Modal it created a naming collision.  I think the FocusTrap component in this library should be named to be a little more specific to avoid this problem for consumers.  Something along the lines of BlazoredModalFocusTrap would solve this.

**Comment by chrissainty** [comment]
I'm not sure I see this as an issue, this is what namespaces are for after all. Blazorise has a FocusTrap component and they don't give it a special name. I'm going to close this as it's not something I think will change.
