### ISSUE TITLE
[Question] How to customize selected styling elements?

### ISSUE THREAD

**Issue by macias** [Blazored/Modal#529]
I've read documentation about custom layout: https://blazored.github.io/Modal/styling/custom-layout but it is (as I understand) when you want completely, 100%, custom styling.

In my case I would like to change just a few bits, like:

```
.bm-header
{
    padding:0;
}
```

but since Modal uses isolated styling I don't know how to do it. I tried also adding `::deep` but it didn't change anything.

**Comment by chrissainty** [comment]
Have you tried adding the `!important` modifier to your CSS rules?

**Comment by macias** [comment]
Thank you very much, it did the trick :-).
