### ISSUE TITLE
Async call on Close

### ISSUE THREAD

**Issue by NPadrutt** [Blazored/Modal#53]
Is there an OnClose Version where I can use async? As far as I can see currently there has to be a void return type.
I try to reload my list when the dialog was closed but not canceled, but that does not seem to work that way.

**Comment by natsuo** [comment]
Clicking the close button (cross) or clicking the background is considered a cancellation. If your modal has a Yes/No button for instance, they should return a ModalResult stating which button you clicked.

For instance, in a modal allowing you to select a customer, you could return a null value.
`Modal.Close(ModalResult.Ok<Customer>(null));`

**Comment by NPadrutt** [comment]
That is what I am doing.

The dialog is opened with this:

    public void OpenCreateUserDialog()
    {
        Modal.OnClose += ModalClosed;
        Modal.Show(LocalizedStrings.CreateUserTitle, typeof(CreateUser));
    }

 I close the dialog with this:

            ModalService.Close(ModalResult.Ok(true));

and my close method looks like:

    private async void ModalClosed(ModalResult modalResult)
    {
        if (!modalResult.Cancelled)
        {
            UsersList = await UsersApi.GetUsersAsync();
        }
        Modal.OnClose -= ModalClosed;
    }

So far I used the dialogs of MatBlazor and after the UserList is reloaded the UI refreshed properly. Since the dialogs there where very limited I switched. Unfortunately, After the closed method is handled the UI does not refresh. 
Unless I overlook something, my suspicion is that this is due to the fact that the `ModalClosed `method does not return a task.
I also tried it without async await and with result:

      UsersApi.GetUsersAsync().Result;

But that freezes the whole UI.

**Comment by NPadrutt** [comment]
I was able to solve this.

```
private async void ModalClosed(ModalResult modalResult)
    {
        if (!modalResult.Cancelled)
        {
            UsersList = await UsersApi.GetUsersAsync();
            StateHasChanged();
        }
        Modal.OnClose -= ModalClosed;
    }
```

Not the additional call of `StateHasChanged`. It seems that Blazor wouldn't recognize automatically that it has to update the list.

**Comment by chrissainty** [comment]
Hi @NPadrutt,

I'm glad you figured it out. Blazor needs to be told to trigger a re-render when operating in event handlers as they are outside of Blazor "view".

**Comment by NPadrutt** [comment]
mh, makes sense. Though it confuses me a bit that it worked in the Event Handler of the MatBlazor Dialog. But maybe there is something different in the background :)

Thanks
Nino

**Comment by Kurti123** [comment]
> That is what I am doing.
> 
> The dialog is opened with this:
> 
> ```
> public void OpenCreateUserDialog()
> {
>     Modal.OnClose += ModalClosed;
>     Modal.Show(LocalizedStrings.CreateUserTitle, typeof(CreateUser));
> }
> ```
> 
> I close the dialog with this:
> 
> ```
>         ModalService.Close(ModalResult.Ok(true));
> ```
> 
> and my close method looks like:
> 
> ```
> private async void ModalClosed(ModalResult modalResult)
> {
>     if (!modalResult.Cancelled)
>     {
>         UsersList = await UsersApi.GetUsersAsync();
>     }
>     Modal.OnClose -= ModalClosed;
> }
> ```
> 
> So far I used the dialogs of MatBlazor and after the UserList is reloaded the UI refreshed properly. Since the dialogs there where very limited I switched. Unfortunately, After the closed method is handled the UI does not refresh.
> Unless I overlook something, my suspicion is that this is due to the fact that the `ModalClosed `method does not return a task.
> I also tried it without async await and with result:
> 
> ```
>   UsersApi.GetUsersAsync().Result;
> ```
> 
> But that freezes the whole UI.

Is there any documentation  Modal.OnClose field went to? I just upgraded from 3.x to 5.1 and have some errors here.

**Comment by chrissainty** [comment]
If you go through the readme or checkout the sample projects you can see how the new APIs work. Essentially though, there isn't an OnClose event anymore, you now await the modal.

**Comment by gocarnetdev** [comment]
What is the advice for a method to hold the modal open and allow user re-submission in the event of an error? Following code illustrates the problem. I've tried lots of different things, feel like I must be missing something obvious?

    private async void SubmitForm()
    {
        ErrorCSS = ErrorCSS.Replace("visible", "hidden");
        APIResult r = await dataService.UpdateTourPlaceSequence(AppState.SelectedTour, PlaceID, currentSeq, NewSeq);

        if (r.Error == APIErrors.NoError)
        {
            await modal.CloseAsync(ModalResult.Ok<int>(NewSeq));
        }
        else
        {
            // Failure due to duplicate sequence # or database error during save
            Error = r.ErrorMessage;
            ErrorCSS = ErrorCSS.Replace("hidden", "visible");
            // Prevent modal from closing and allow the user to see the error message and re-submit.
            // Works if submit button type is "button" but then you don't get the refresh of the map component
            // So, how do you do this...????
        }
    }


`

**Comment by chrissainty** [comment]
Just don't call the modals close method when there is an error. That seems the obvious thing to do, unless I'm missing something?
