### ISSUE TITLE
Responsible modal support for mobile

### ISSUE THREAD

**Issue by rnielikki** [Blazored/Modal#54]
in blazor-modal class in html, width is always 50rem, which cuts contents on mobile (or forced to scroll).

**Comment by chrissainty** [comment]
We can look at adding responsiveness into the component. But for now you can either provide your own CSS class or override the `.blazor-modal` class in your own CSS.

**Comment by Daniel-NP** [comment]
This works for me:

    .blazored-modal {
    width: auto !important;
    }

**Comment by softwareguy74** [comment]
+1

**Comment by kamranghamsari** [comment]
I have this problem
what should I do?

**Comment by larsk2009** [comment]
This issue is a bit old, and it seems the particular issue had been fixed in V3.0.0. I think it is better if you open a new issue if you are having a similar issue.
