### ISSUE TITLE
Keyboard Handling not straight-forward

### ISSUE THREAD

**Issue by HMyersPharmaLink** [Blazored/Modal#544]
**Is your feature request related to a problem? Please describe.**
I have a need to recognize certain keystrokes in a dialog box, such as Enter (YES) , ESC(NO), plus controls numeri "+" and "-"

**Describe the solution you'd like**
I would like to see the ability to filter keyboard input and perhaps define a Yes and no and a string of control characters, 
then provide an event for access to the control character picked if any. Ignore anything else

**Describe alternatives you've considered**
I have already written this for another vendors software, it is giving me a different problem, essentially, it is hiking up my power consumption and processor %. That soluction seems to not play well in my application. I have keyboard working there, but it doesn't seem to transfer over. 

**Additional context**

**Comment by chrissainty** [comment]
@HMyersPharmaLink I'm trying to understand what you're asking for. Why can't you handle the keystrokes in the component being displayed in the modal? Why does this need to be part of the library?

**Comment by HMyersPharmaLink** [comment]
We are using scanners to scan Drug Codes (we dispose of old expired, recalled drugs) so we have people scanning drugs QR codes all day.
These codes some times have non printable characters, in particular asc(29) which is the <GS> group separator character. We replace it with a Pipe | for further processing.

That said, I ended up crafting a JavaScript solution to intercept keyboard input after first attempt using blazor (net) keyboard events was unreliable or unable to detect the keys I needed. JS does it just fine.

Anyway, problem is solved.

I really appreciate you responding very much.

Harvey Myers

**Comment by chrissainty** [comment]
Thanks for getting back @HMyersPharmaLink. I'll close the issue as you have a solution.
