### ISSUE TITLE
Vulnerability in Microsoft.AspNetCore.Components@6.0.3

### ISSUE THREAD

**Issue by germgh0st** [Blazored/Modal#549]
We use Synk to check for vulnerabilities in our repositories.

Currently an issue is reported as below:

![image](https://github.com/Blazored/Modal/assets/6408110/9fe6cbcb-5af6-4e38-90a1-c5850b9819ba)

Are there any plans to update Blazored.Modal to use a later version of Microsoft.AspNetCoe.Components to remove this vulnerability?

**Comment by MrGeneric** [comment]
![image](https://github.com/Blazored/Modal/assets/3923223/3b6c390d-667a-418e-9d58-5aa221a41050)

I think if you install the 6.0.25 version directly then BlazoredModal will use that.

**Comment by germgh0st** [comment]
Yes, this is correct. However we'd much rather that third party libraries that we use to use up to date dependencies so that we don't have to spend the time checking/updating them, hence my question.
