### ISSUE TITLE
Cancelling a Modal w/ Parameters still returns the changes on the passed parameter

### ISSUE THREAD

**Issue by dmarsh12** [Blazored/Modal#55]
Any action taken/modification on a passed parameter returns to the parent component even while using Modal.Cancel().

For example, if I have a List<string> object that I pass to a modal as a cascading parameter, modify the list in the dialog, and hit cancel/call the Modal.Cancel() function, the action taken on the parameter still is applied and passed to the parent component. 

Is this intended?

**Comment by chrissainty** [comment]
Are you passing your list to the modal using the `ModalParameters` object?

**Comment by chrissainty** [comment]
As I've not heard back I'm going to close this issue and assume it's resolved. If you have any further issues feel free to re-open.

**Comment by larsk2009** [comment]
I was having this same problem, but it had to do with Entity Core 'caching' things or something along those lines, and nothing with what the Modal did.
