### ISSUE TITLE
[Feature Request] .net 8

### ISSUE THREAD

**Issue by armandelta2002** [Blazored/Modal#550]
hi, we need  work  on .net 8

**Comment by chrissainty** [comment]
@armandelta2002 What isn't working on .NET 8?

**Comment by garrettlondon1** [comment]
@chrissainty

Currently, there is no good solution for using SSR + InteractiveServer and the BlazoredModal package. Originally, CascadingBlazoredModal was cascaded down the entire tree.

Now in .NET8, if you don't define global interactivity, and use SSR plus InteractiveServer islands.. What do you recommend for this application?
- Do you have to now use cascading modal in every single @page or InteractiveServer component?
