### ISSUE TITLE
[Bug] Version 7.3.0: Modal/src/Blazored.Modal /FocusTrap.razor produces a nice blue line

### ISSUE THREAD

**Issue by JASiebel** [Blazored/Modal#557]
**Describe the bug**
I'm not sure if there is change with Version 7.3.0 and I miss some configurations.

The  FocusTrap.razor produces an unexpected nice blue line.

See Line 1 in FocusTrap.razor.

I think this is not indented.

Thanks for Your great work.
Best regard 
Jörg Siebel

**Comment by chrissainty** [comment]
🤦‍♂️ I was using that for some debugging and forgot to remove it. I'll get a minor fix out later today.
