### ISSUE TITLE
Requires using Blazored.Modal in Startup.cs

### ISSUE THREAD

**Issue by ChrisClarke1218** [Blazored/Modal#56]
Hi All,

A quick setup step point:  your  step #1.  Register Services - missed adding the instruction - Add 'using Blazored.Modal;' to the startup.cs file.

**Comment by chrissainty** [comment]
Hi Chris,

This wasn't missed, more omitted. But I appreciate we shouldn't assume everyone knows how to `ctrl`+`.` to add a using statement. I'll update the readme.
