### ISSUE TITLE
[Bug] Instruction on the getting started page does not result in a working setup

### ISSUE THREAD

**Issue by zwrawr** [Blazored/Modal#561]
I'm probably just missing something but, 

**Describe the bug**. 
[Instruction on the getting started page does not result in a working setup.]( https://blazored.github.io/Modal/) 

**To Reproduce**
1. Create a new "Blazor Web App" with .Net 8.0
2. Follow the getting started on [blazored.github.io](https://blazored.github.io/Modal/)
3. I also took the confirm modal from this repo for testing
4. Run the program and click the buttons
5. Nothing happens

**Expected behavior**
The getting started should produce a working system on the recommend project type for .Net 8.0

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Web App 

**Additional context**
See repo [zwrawr/blazorBlazoredModaltest](https://github.com/zwrawr/blazorBlazoredModalTest) 

The webapp template has pages across both SSR and WASM rendering, which makes this a little complicated.

**Comment by chrissainty** [comment]
This is a common issue with the new .NET 8 templates. In this file https://github.com/zwrawr/blazorBlazoredModalTest/blob/main/blazorBlazoredModal/Components/App.razor you need to add `@rendermode="InteractiveServer/InteractiveWebAssembly"` to the `HeadOutlet` and `Routes` components other wise the app is only server-side rendered.

See the app in the samples folder for an example (https://github.com/Blazored/Modal/blob/main/samples/InteractiveServer/Components/App.razor)

**Comment by zwrawr** [comment]
Thanks.

The comment still stands
>  The getting started should produce a working system on the recommend project type for .Net 8.0
