### ISSUE TITLE
Styling changes when moving from Development to Production environment

### ISSUE THREAD

**Issue by DrGriff** [Blazored/Modal#61]
Using Blazor (Server) addressing .Net Core 3.1 preview 2 (3.1.100-preview2-014569)

Under the launchSettings.json, I have the following:
```
"profiles": {
  "IIS Express": {
    "commandName": "IISExpress",
    "launchBrowser": true,
    "environmentVariables": {
      "ASPNETCORE_ENVIRONMENT": "Development"
    }
  },
```

When I run the application, the modal window has the following classes:

```
<div class="blazored-modal-container blazored-modal-center blazored-modal-active">
<div class="blazored-modal-overlay"></div>
<div class="blazored-modal-wrapper">
<div class="blazored-modal">
<div class="blazored-modal-header">
```
However, when I comment out the line (to mimic a PROD environment)
` //  "ASPNETCORE_ENVIRONMENT": "Development"`

I end up with:

```
<div class="blazored-modal-container  ">
<div class="blazored-modal-overlay"></div>
<div class="blazored-modal-wrapper">
<div class="blazored-modal-header">
```

The differences are causing the modal window to display to the left of the page.

**Comment by chrissainty** [comment]
That's a very odd issue. I can't see how the environment variable could change what CSS classes are output, there is not logic which is based on the environment. Would you be able to post a minimum repro somewhere so I can take a look?

**Comment by DrGriff** [comment]
I systematically dismantled the app until the problem disappeared, then re-assembled the application and the problem has not re-appeared.  According to my Source Control I'm back where I started but with different behaviour.  Seems that this is a non-issue.
