### ISSUE TITLE
Allow pass onClose to Show method

### ISSUE THREAD

**Issue by troepolik** [Blazored/Modal#63]
I'd like to pass onClose to Show method like win forms show dialog
It will free programmers from handle subscribe/unsubscribe.
Also it useful if any error was thown before unsubscribe
Look like that:
`
Modal.Show<MessageDialog>("Dance", parameters, onClose: ShowResult);
`
I have prepared branch with this feature , but I can not push it, seems I have not rights.
If you give me right, I will prepare pull request with feature and samples

Also I fixed bug (m.b blazor bug)
If I show first modal then in onClose I show second modal with the same component type (but with another text), blazor do not refresh content inside modal window

Like this:
`
Modal.Show<MessageDialog>("Dance", parameters, onClose: ShowResult);
`
then

```
void ShowResult(ModalResult result)
    {
        var parameters = new ModalParameters();
        parameters.Add("DialogParameters", new MessageDialog.DialogParameters()
        {
            Message = result.Cancelled ? "User calcel process" : result.Data.ToString(),
            Buttons = new MessageDialog.ButtonType[] { MessageDialog.ButtonType.Ok }
        });

        Modal.Show<MessageDialog>("Result", parameters);
    }
```

to fix that in ModelService I made :
`
var content = new RenderFragment(x => { x.OpenComponent(1, componentType); x.SetKey(Guid.NewGuid()); x.CloseComponent(); });
`
I added x.SetKey when build render fragment

**Comment by chrissainty** [comment]
Hi @troepolik,
Interesting suggestion, I look forward to your PR to see what it looks like. 

You don't need any permissions to raise a PR. I suggest checking out GitHub's help pages on creating a pull request (https://help.github.com/en/desktop/contributing-to-projects/creating-a-pull-request).

**Comment by troepolik** [comment]
Hi @chrissainty ,
unfortunetly I could not push my branch allow_pass_onClose_to_show_method to your repository...
logs here:
git.exe push --progress "origin" allow_pass_onClose_to_show_method:allow_pass_onClose_to_show_method

fatal: HttpRequestException encountered.
An error occurred while sending the request.
fatal: HttpRequestException encountered.
An error occurred while sending the request.
remote: Permission to Blazored/Modal.git denied to troepolik.
fatal: unable to access 'https://github.com/Blazored/Modal.git/': The requested URL returned error: 403

My colleague tried to do the same and got this error too.
We experimented with his repo and got success only when he added me as collabolator to his repo.

**Comment by chrissainty** [comment]
That's because you are trying to push directly to the repo. You have to fork the repo first and then raise a PR from your fork into this repo. Again, please have a read of the GitHub docs, here is a [link to the article on forking](https://help.github.com/en/github/getting-started-with-github/fork-a-repo).

**Comment by troepolik** [comment]
Thanks for explanation, I lose knowledge about fork. I'v created PR now.

**Comment by Liero** [comment]
I strongly recommend against this API design.

First of all, it can be easily implemented as extension method in your own project.
Second, it violates design principles of modern C# frameworks. We shouldn't really follow old WinForms 👴
Thirds, it pollutes the `Show` method with already bunch of overloads with yet another parameter. We can add parameters endlessly, but there are better approaches, see #103 for example

**Comment by troepolik** [comment]
Yes, If you can implement this API with awaitable result, it will resolve the problem too
