### ISSUE TITLE
Modal close event not working - core 3/3.1

### ISSUE THREAD

**Issue by chewabledrapery** [Blazored/Modal#65]
Hi,

I'm having an issue getting the modal close event to fire, i've even downloaded and modified Index.razor pages in the samples and it does not work in either BlazorSample or ServerSideblazor projects..

modified index.razor code below, once the strresult variable is displayed as "modal shown" it is not changed when closing or cancelling the modal.

Help very much appreciated this is a bit of a show stopper for me at the moment as i need to detect when the user has closed the modal.

Kind regards,

Dean.

![image](https://user-images.githubusercontent.com/33089517/69486012-d30fa300-0e3e-11ea-9538-f131517338c3.png)

**Comment by chrisd2k** [comment]
Are you sure it's the event not firing and not just the UI not detecting the state change?  I had to add a manual call to this.StateHasChanged(); to trigger a UI refresh in the ModalClosed event.

**Comment by chrissainty** [comment]
@chewabledrapery as @chrisd2k has stated the code is working fine you just need to manually call `StateHasChanged` to your `ModalClosed` method. Events like this happen outside of Blazor view and therefor it doesn't know it needs to re-render the UI, hence the need to call it manually.

**Comment by chewabledrapery** [comment]
Hi @chrisd2k, @chrissainty 

Thanks for the reply guys, you are indeed correct I've changed my code and its working now.

I'm new to blazor and not a particulalry accomplished web dev, i'm a winforms dev trying to drag myself into the 21st century so my understanding of the architecture is constantly improving.

Even though i'd employed StateHasChanged for some cascading dropdowns in the same component I hadn't put 2+2 together in this instance when following your examples.

Hope i've not wasted your time and I really appreciate the feedback, especially on a weekend.

The project is awesome thank you so so much.

Cheers,

Dean.

**Comment by chrissainty** [comment]
No problem and welcome to web dev! 😃 Happy to help.
