### ISSUE TITLE
Close dialog on Esc?

### ISSUE THREAD

**Issue by softwareguy74** [Blazored/Modal#67]
Is it possible to somehow wire up the Esc key to close the dialog?

**Comment by chrissainty** [comment]
Yes, I'll add this as an enhancement.

**Comment by goodisontoffee** [comment]
PR raised https://github.com/Blazored/Modal/pull/99

**Comment by pcecamacho** [comment]
Hello
Any news related to this feature?
Thank you

**Comment by chrissainty** [comment]
@pcecamacho We haven't added the feature so far. It would require a bump in the major version number as it introduces a breaking change and I would want to do that for such a small feature. We'll look at it when we add some other functionality.

**Comment by jenmagjen** [comment]
@chrissainty  Hi! :) I recently spoke to a guy in the norwegian Blind organization, which is working with user testing of different websites and online services. He said unclosable modals (no support for Esc) were like traps for them. They have to close the tab, hit the back button or refresh the whole page in order to close them. So in support for all our visually impaired friends out there who love to use the Internet, this would really be an important update - and for them, not at all a small feature :) Looking forward to that update. :)

**Comment by chrissainty** [comment]
@jenmagjen Agreed, please understand when I said small I meant in terms of changes. Generally speaking, this control hasn't been built with blind/sight-impaired users in mind and therefore there are probably a lot of things we need to do to make this fully accessible to sight-impaired users. Adding this would help but I'm sure we have a very long way to go still.

I'm literally at breaking point right now in terms of commitments and I'm going to be booking some holiday from work so I can work on the backlog of Blazored issues (currently over 40). When I do I'll make sure this is included.

**Comment by jenmagjen** [comment]
@chrissainty  Yes, another known issue is that modals let the "background" be open. So the screen readers does not "see" that the rest of the content is hidden by opacity/overlay, and may get confused when browsing down a page which for other users is "hidden". :) I fully understand that not all can be in place now. Development takes time. :) All improvements are great. Blazor pages with the different Blazored-stuff is really working well. :) So your job so far has been excellent. :) I'll follow the gits with eager :)

**Comment by chrissainty** [comment]
Thanks for the information @jenmagjen and it's always great to hear the components are helping people 🙂

**Comment by NeskireDK** [comment]
Closing modal with ESC is not functioning. 
Steps to reproduce: 
1. git clone https://github.com/Blazored/Modal.git
2. build run 
3. Test any of the modals on the demo, non can close with ESC, most can with click in dark areas.
4. rebuild with setting makes no difference, in demo nor in my own project: 
<CascadingBlazoredModal ActivateFocusTrap="true">
previously known as: 
<CascadingBlazoredModal FocusFirstElement="true">

Using chrome: Version 86.0.4240.75 (Official Build) (64-bit)
OS regional settings and keyboard: Denmark
