### ISSUE TITLE
HTTP GET /_content/Blazored.Modal/blazored-modal.css responded 404 in Production Mode (ASPNETCORE_ENVIRONMENT = "Production")

### ISSUE THREAD

**Issue by dlasalde** [Blazored/Modal#68]
I'm using v2.3.0 of the Blazored.Modal and everything works fine if I set the environment variable:  ASPNETCORE_ENVIRONMENT = "Development".  
But once I set it to "Production", I get a "HTTP GET /_content/Blazored.Modal/blazored-modal.css responded 404".

Here's what I have in my ConfigureServices method in the Startup:
` services.AddBlazoredModal();`

Here's what I have in my _imports.razor
`@using Blazored
@using Blazored.Modal
@using Blazored.Modal.Services`

Here's what I have in the MainLayout.razor file:
`<BlazoredModal />`

Here's what I have in the _Host.cshtml file:
` <link href="_content/Blazored.Modal/blazored-modal.css" rel="stylesheet" />`

Here's my dotnet version:  3.0.100
I using Visual Studio Professional 2019 V16.3.10

Is there something additional that I have to do to make this work in production mode?

**Comment by chrissainty** [comment]
Hi @dlasalde, your issue sounds very similar to #61. That seemed to end up being some weird caching issue or build problem. Might be worth trying a full clear down as per that issue.

**Comment by dlasalde** [comment]
@chrissainty I was able to reproduce this issue in a test project:
`@page "/fetchdata"

@using ContactManagementSystem2.Data
@using Microsoft.JSInterop
@using Newtonsoft.Json;
@inject WeatherForecastService ForecastService
@inject IModalService Modal
@inject IJSRuntime JSRuntime
     <body onbeforeunload="RemoveDataTableFromDOM('#example')">
        <h1>Weather forecast</h1>

        <p>This component demonstrates fetching data from a service.</p>
        <p>
            When I would click on the "Home" or "Counter" pages, the filter and the footer would remain on the page because the DataTables plugin
            adds control elements to the DOM around the table.  So, to fix this issue I added a body tag to this razor control page
            and then to this tag I added the window event handler attribute: "onbeforeunload" and then pass in the RemoveDataTableFromDOM method (defined in the "_Host.cshtml" file) along with the table's id as a parameter
            which in turn will call the DataTables' "destroy" method.
        </p>

        <div id="loadingPanel" class="loading-panel hidden"></div>
        @if (errorOccurred)
        {
            <div class="text-danger">
                An error has occurred.  Please try refreshing the page and/or closing the browser and reopening it.  If the problem persists, please contact the administrator of this site.

            </div>

        }


        @if (!errorOccurred && forecasts == null)
        {
            @*<p><em>Loading...</em></p>*@
            <div class="loader" style="align-content: center;"></div>
        }
        else if (!errorOccurred && forecast != null)
        {
            <table id="example" class="display" style="width:100%;">
                <thead class="bg-primary text-white">
                    <tr>
                        <th>Date</th>
                        <th>Temp. (C)</th>
                        <th>Temp. (F)</th>
                        <th>Summary</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var forecast in forecasts)
                    {
                        id++;
                        <tr @onclick="@(() => ShowModal(id))">
                            <td>@forecast.Date.ToShortDateString()</td>
                            <td>@forecast.TemperatureC</td>
                            <td>@forecast.TemperatureF</td>
                            <td>@forecast.Summary</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </body>


@code {
    WeatherForecast[] forecasts;
    string forecastsJSON;
    bool errorOccurred;

    int id = 0;

    WeatherForecast forecast = new WeatherForecast();

    protected override async Task OnInitializedAsync()
    {
        try
        {
            //forecasts = await ForecastService.GetForecastAsync(DateTime.Now);
            await GetList();
            ForecastService.RefreshListRequest += RefreshMe;
        }
        catch
        {
            errorOccurred = true;
        }
        
    }

    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            JSRuntime.InvokeAsync<object>("LoadJQueryDataTable", new[] { "#example" });
        }
    }

    private void ShowModal(int uniqueId)
    {
        if (uniqueId > 0)
        {
            forecast = forecasts.FirstOrDefault();
            var parameters = new ModalParameters();
            parameters.Add("forecast", forecast);
            var cssOptions = new ModalOptions() { Style = "blazored-prompt-modal" };
            Modal.Show($"Edit info for date: {forecast.Date}", typeof(FetchDataModal), parameters, cssOptions);

        }
    }

    protected bool IsLoading { get; set; }

    private async void RefreshMe()
    {
        await GetList();
        forecastsJSON = forecasts != null ? JsonConvert.SerializeObject(forecasts): string.Empty;
        await JSRuntime.InvokeAsync<object>("RefreshJQueryDataTable", new[] { "#example", forecastsJSON });
    }

    protected async Task GetList()
    {
        IsLoading = true;
        forecasts = await ForecastService.GetForecastAsync(DateTime.Now);
        IsLoading = false;
    }

}`
MainLayout.razor:
`@inherits LayoutComponentBase
<BlazoredModal></BlazoredModal>
<div class="sidebar">
    <NavMenu />
</div>

<div class="main">
    <div class="top-row px-4">
        <a href="https://docs.microsoft.com/en-us/aspnet/" target="_blank">About</a>
    </div>

    <div class="content px-4">
        @Body
    </div>
</div>

Here's what I have in the _Host.cshtml:
@page "/"
@namespace ContactManagementSystem2.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ContactManagementSystem2</title>
    <base href="~/" />
    <script type="text/javascript" src="~/lib/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/bootstrap.min.js"></script>

    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
    <link href="css/site.css" rel="stylesheet" />

    <link href="~/css/datatables/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/css/datatables/dataTables.bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/datatables/jquery.dataTables.min.js"></script>
    <link href="_content/Blazored.Modal/blazored-modal.css" rel="stylesheet" />
</head>
<body>
    <app>
        @(await Html.RenderComponentAsync<App>(RenderMode.ServerPrerendered))
    </app>

    <script src="_framework/blazor.server.js"></script>
    <script type="text/javascript" src="~/lib/blazorpolyfill/blazor.polyfill.min.js"></script>

   
    <script>
        var _MyDataTable = null;
        function LoadJQueryDataTable() {
            var tableId = arguments[0];
            console.log("Calling the 'LoadJQueryDataTable' method for tableid:  " + tableId);
            $(document).ready(function () {
                try {
                    //the datatable renders faster than the data coming in so I'm delaying it here (3 seconds)
                    setTimeout(function () {
                        _MyDataTable = $(tableId).DataTable({                           
                            autoWidth: true,
                            scrollX: true,
                            scrollY: '50vh'
                        })//datatable
                    }, 3000);//end of setTimeout
                }//end of try
                catch (exception) {
                    console.log("exception thrown (document.ready):  " + exception);
                }//end of catch
            });//end of document ready
        }//end of function

        function RefreshJQueryDataTable() {
            try {
                $("#errormessage").text("");
                var tableId = arguments[0];
                var newDataArray = arguments[1];
                console.log("calling the 'RefreshJQueryDataTable' method for tableid: " + tableId);
                console.log("here is the data:  "+newDataArray)

                _MyDataTable.draw();
             
            }
            catch (exception) {
                console.log("exception thrown (RefreshJQueryDataTable):  " + exception);
            }
        }

        function HandleException() {
            try {
                var tableId = arguments[0];
                var exceptionMessage = arguments[1];
                console.log("calling the 'HandleException' method for tableid:  " + tableId);
                console.log("here is the exception:  " + exceptionMessage);
                
                $("#errormessage").text("Ooops!  An error has occurred! Please refresh the page and try again.  If this problem persists please open up a ticket with the help desk.");
            }
            catch (exception) {
                console.log("exception thrown (HandleException):  " + exception);
            }
        }
    </script>
    <script>
        /*
         * In order for this function to work, you'll need
         * to add the following body tag to your page component 
         * where "#example" is the id you have for your table:
         * <body onbeforeunload="RemoveDataTableFromDOM('#example')">
         * 
         * */

        function RemoveDataTableFromDOM(table) {
            document.ready(function () {
                console.log("DataTable().destroy() is being called");
               
                //table.DataTable().destroy();
                 //var elem = document.querySelector(table + '_wrapper');
                //elem.parentNode.removeChild(elem);
            });
        }
    </script>
</body>
</html>`

Startup.cs:
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using ContactManagementSystem2.Data;
using Blazored.Modal;
using Blazorise;
using Blazorise.Bootstrap;
using Blazorise.Icons.FontAwesome;


namespace ContactManagementSystem2
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();
            services.AddServerSideBlazor().AddCircuitOptions(options => { options.DetailedErrors = true; });
            services.AddBlazoredModal();
            services.AddSingleton<WeatherForecastService>();

            services.AddBlazorise(options =>
            {
                options.ChangeTextOnKeyPress = true;
            }).AddBootstrapProviders().AddFontAwesomeIcons();
            
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.ApplicationServices.UseBootstrapProviders().UseFontAwesomeIcons();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapBlazorHub();
                endpoints.MapFallbackToPage("/_Host");
            });
        }
    }
}`
Program.cs:
`using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Serilog;

namespace ContactManagementSystem2
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .WriteTo.Console().CreateLogger();
            try
            {
                Log.Information("Woohoo!  Starting up!  Giddy up!!");
                CreateHostBuilder(args).Build().Run();
                
            }
            catch(Exception ex)
            {
                Log.Fatal(ex, "Application start-up failed.");

            }
            finally
            {
                Log.CloseAndFlush();

            }
            
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
            .UseSerilog()
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}`

Project Dependencies:
`<ItemGroup>
    <PackageReference Include="Blazored.Modal" Version="2.2.0" />
    <PackageReference Include="Blazorise.Bootstrap" Version="0.8.6.1" />
    <PackageReference Include="Blazorise.Icons.FontAwesome" Version="0.8.6.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.1.0" />
  </ItemGroup>`

**Comment by dlasalde** [comment]
I found the solution [here](https://stackoverflow.com/questions/58862932/blazor-server-static-files-dont-link-in-non-dev-environments):  
I was missing "webBuilder.UseStaticWebAssets()" in the CreateHostBuilder method that's in the Program.cs: 
` public class Program
    {
        public static void Main(string[] args)
        {
            
           
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args)
        {
            var config = new ConfigurationBuilder()
                .AddCommandLine(args)
                .Build();

            return Host.CreateDefaultBuilder(args)
                 .UseSerilog((ctx, config) => { config.ReadFrom.Configuration(ctx.Configuration); })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseConfiguration(config);
                    webBuilder.UseStaticWebAssets();
                    webBuilder.UseStartup<Startup>();
                })
                .ConfigureAppConfiguration(appConfig =>appConfig.SetBasePath(Directory.GetCurrentDirectory())
                .AddEnvironmentVariables()               
                .AddCommandLine(args));
        }
       

       
        

       
        
    }`

**Comment by darraghjones** [comment]
Perhaps this should be added to the Getting Setup section of the readme as it caught me out
