### ISSUE TITLE
Disable modal header

### ISSUE THREAD

**Issue by mcrisafu** [Blazored/Modal#71]
Thank you for your awesome work!

Is it possible to not only disable the close button but also the whole header? I style my modals with bulma so I only need the modal-content. I can pass an empty title and disable the close button but there are still some padding pixel. I think an option to disable the whole header would be the easiest and least "hacky" solution.

regards
Marco

**Comment by chrissainty** [comment]
Hi Marco,

Glad you like the control. Yes, that's a good idea, I'll add it to the pipeline.
