### ISSUE TITLE
Scrollable Modal [Question]

### ISSUE THREAD

**Issue by mykelboachie** [Blazored/Modal#72]
Do you have to add some code to make modals scrollable?

I have fields that are longer than screen length and it looks like my modal is just fits some on the screen preventing me from getting to the submit or close button to get the modal off the screen.

Please let me know if I am doing something wrong
![Capture](https://user-images.githubusercontent.com/16784541/69999632-f2c55c00-150d-11ea-81eb-74e188a6676a.PNG)

**Comment by chrissainty** [comment]
Hi @mykelboachie, check out my comment on #35, that should sort your issue.

**Comment by mykelboachie** [comment]
@chrissainty Hey man thanks...That did sort my issue. Thanks for this fantastic tool

**Comment by chrissainty** [comment]
No worries :)
