### ISSUE TITLE
RenderFragment for the Title

### ISSUE THREAD

**Issue by jimmygilles** [Blazored/Modal#73]
Hello,

Currently, the Title is a string that cannot be updated once the modal is open.
It would be great to change from a string to a RenderFragment.

That would allow us to update the title based on data loaded asynchronously from a restapi for example.

Thank you very much !

**Comment by jimmygilles** [comment]
Just to be clear.

In the dialog Razor file, there is something like that:

```
<h3>@Title</h3>

<div>
    @Content
    @ChildContent
</div>

@code
{
    public RenderFragment Content { get; set; }

    [Parameter]
    public RenderFragment Title { get; set; }
    [Parameter]
    public RenderFragment ChildContent { get; set; }
}
```

then, we can use it either:

**Comment by jimmygilles** [comment]
What I wanted to say, I don't know if it's possible to use something like that:

```
<h3>@Title</h3>

<div>
    @Content
    @ChildContent
</div>

@code
{
    public RenderFragment Content { get; set; }

    [Parameter]
    public RenderFragment Title { get; set; }
    [Parameter]
    public RenderFragment ChildContent { get; set; }
}
```
and then:

```
    <Test2>
        <Title>I am the title</Title>
        <ChildContent>
            I am the content of the dialog.
        </ChildContent>
    </Test2>

    <Test2>
        I am a dialog with a default title
    </Test2>
```

Thank you.

**Comment by chrissainty** [comment]
@jimmygilles I've come up with the following, I hope it solves your need. You will be able to get access to the modal via a cascading parameter, you can then use the new `SetTitle` method to update the title of the modal dynamically.

```csharp
[CascadingParameter] BlazoredModal BlazoredModal { get; set; }

protected override void OnInitialized()
{
    BlazoredModal.SetTitle("My Modal Title");
}
```

**Comment by satishbhagal** [comment]
hi can you share its full code here.

Thanks in Advance!
