### ISSUE TITLE
Modal visible during onClose

### ISSUE THREAD

**Issue by fudgeboy2000** [Blazored/Modal#74]
Hi there - many thanks for your efforts with this component so far.  It's been really useful while I've been getting my project off the ground.

One thing I've used it for is for a confirm dialog - pops up, user clicks Yes or No, modal closes down and their choice is passed back to the onClose method via ModalResult.  Works well, but if the result of the choice is a noticeably slow operation (100 DB writes, say) then the modal remains visible **while** the onClose method is running.  I'd like to throw up a progress bar or something, but need to hide the modal first.

I've tried wrapping the modal in a @showForm bool and setting it to false, and calling StateHasChanged() in various places, but no joy so far.

Am I missing something obvious, or is this not possible?

**Comment by chrissainty** [comment]
This is an interesting one. Both the modal and your code are subscribed to the `OnClose` event and I think your code is getting there first, as it were.

I could add an `OnAfterClose` event which fires after the OnClose but I'm not sure if that's just hiding bad design. Let me have a think.

**Comment by fudgeboy2000** [comment]
I think you're right about the bad design.  I did some digging today and I had some async code in a twist somewhere which blocked the UI thread, stopping the modal from hiding.  I reworked it to use a Task.Run and it works well now.  Coming from a mostly web background has done me in with this - my async experience needs some work!

**Comment by chrissainty** [comment]
lol yeah, it does get fun at times. Are you running Blazor WebAssembly?

**Comment by fudgeboy2000** [comment]
No, it's server at the moment.  This project is a small-ish corporate intranet app so running in the browser isn't key, and I'm not allowed to build on preview tech.  I still wanted to get the general Blazor stack into the product estate as soon as possible though - it's a really exciting way of rapidly building good-looking .net core web apps without needing loads of experience in javascript frameworks, or even much HTML.  It means the app can be supported by a wider range of developers in the team - the back end guys can get much more involved than usual.

Once I've got Blazor's foot in the door I'm hoping for more WA projects in the future when it reaches GA.  Some of the upcoming support for PWAs, different renderers, and native support make it potentially the most flexible approach I've seen for a c# development team.

**Comment by chrissainty** [comment]
That sounds like a good plan. 

I couldn't agree with your thoughts more. Blazor is an extremely exciting tech for all the reasons you've mentioned. I'm very excited to see where we are in a few years time once WebAssembly gets more features.

I've actually decided to go with the other event approach for now. I think it's better the modal is dealt with separately to user code.
