### ISSUE TITLE
ModalResult contain Modal Type

### ISSUE THREAD

**Issue by larsk2009** [Blazored/Modal#76]
I have a page where I want to show multiple different modals and do something different with the return value depending on which type is used when calling Show<T>.

I don't think this is possible right now. Am I correct in this assumptions.
If so, do you agree this is something nice to add? If you do I could see if I can make a PR for it.

**Comment by chrissainty** [comment]
You are correct, multiple modals aren't supported right now. I'm working on adding this support in but I'm still deciding on how I want it to work. Once I've done that it might be good to have some help with it.

**Comment by larsk2009** [comment]
Good to hear. Please keep me in the loop and I will see how I can help
