### ISSUE TITLE
IE11 Support?

### ISSUE THREAD

**Issue by fudgeboy2000** [Blazored/Modal#77]
I know, I know.  IE11 is horrible, but sometimes we have to put up with it.  I can totally understand if you don't want to sink any time into this, but if you have any advice on a starting point then I'm up for checking it out.

If I download the project, fire up the samples, server-side blazor, nothing works in IE11.  Not a fault of the modal package, just blazor itself.  If I then add daddoon's blazor.polyfill to the project then things start to work, but the modal styling is off:

![BlazorModalIE11](https://user-images.githubusercontent.com/38722956/70398423-24a95780-1a13-11ea-951d-f23f302ff9b7.png)

The title bar is missing, and the overlay's starting position is...different.

**Comment by chrissainty** [comment]
@fudgeboy2000 It will just be down to CSS styles and making them work with IE11. 

I can't really remember now what is and isn't supported in IE11 style-wise. But I would expect I've used some more modern CSS rules which don't work. You'll need to find these and rework them to make them IE11 compatible.

**Comment by chrissainty** [comment]
I'm going to close this issue as I'm not planning on adding IE11 support. Sorry I couldn't be more help.
