### ISSUE TITLE
Using as confirm delete

### ISSUE THREAD

**Issue by dennismagno** [Blazored/Modal#79]
I have a Task DeleteCustomer if I call it directly on button click, the record was successfully deleted and list my html is updated.  But when I call it on ModalClosed, refreshing list doesn't seem to work.  The record is successfully deleted but not reflect on my Ui.

```
async Task DeleteCustomer(long Id)
{
    await http.DeleteAsync($"api/customer/{Id}");
    await LoadCustomer();
}

private async void ModalClosed(ModalResult modalResult)
{
    if (!modalResult.Cancelled)
    {
        await DeleteCustomer(this.customerId);
    }

    Modal.OnClose -= ModalClosed;
}
```

**Comment by chrissainty** [comment]
You need to call `StateHasChanged` to let Blazor know it needs to update the UI. You need to do this because Blazor doesn't monitor custom event handlers.

```
private async void ModalClosed(ModalResult modalResult)
{
    if (!modalResult.Cancelled)
    {
        await DeleteCustomer(this.customerId);
    }
    
    StateHasChanged();
    Modal.OnClose -= ModalClosed;
}
```

**Comment by dennismagno** [comment]
Hi Chris, thanks a lot for your reply and explanation about the problem that I have.
