### ISSUE TITLE
Add way to configure default ModalOptions

### ISSUE THREAD

**Issue by juho-hanhimaki** [Blazored/Modal#81]
Now its kinda tedious to pass options for each show of the modal.

In general I want the modals to always behave the same way so ideally there should be a way to configure once and forget.

**Comment by chrissainty** [comment]
Agreed, you can specify all of the options directly on the modal component to avoid having to do this. You can see an example [here](https://github.com/Blazored/Modal/blob/dfb53d81dc4764000e4d619fab288b6ff0b35c09/samples/BlazorSample/Shared/CustomModalLayout.razor#L3) where the `style` option is being set. Any options you set here are global.
