### ISSUE TITLE
Controlling Width and Height of Modal

### ISSUE THREAD

**Issue by DigitalPZ** [Blazored/Modal#83]
I have successfully incorporated BlazoredModal into my project but every modal I show seems to be constrained in width and height. As a result, the content doesn't use all the screen real estate. I have looked at where the constraint might be but cannot find it. Any ideas?

**Comment by chrissainty** [comment]
The modal doesn't have any constraints on it. The size of the modal is completely under your control. So you can either provide your own class for the modal with the style settings you want. Or the modal can just expand to the size of whatever it is displaying. So you can set the style on the component which is showing in the modal and modal should flex to that size.

**Comment by DigitalPZ** [comment]
Can the modal have scrollbars?

**Comment by chrissainty** [comment]
It can have what you want :) You're in complete control.

Give it whatever CSS styling you wish, scrollbars, hover effects, purple background, it's all under your control 😄

**Comment by DigitalPZ** [comment]
I really need to up my CSS game. Thanks for the quick responses.

**Comment by chrissainty** [comment]
It's definitely worth doing, you can achieve some amazing stuff now using CSS. I personally use SASS a lot to help manage it but it's a personal preference. Have fun!
