### ISSUE TITLE
StateHasChanged() not updating parent component OnClose()

### ISSUE THREAD

**Issue by rleath82** [Blazored/Modal#86]
Closing the modal using StateHasChanged() is not refreshing the parent component. Was wondering if anyone else was experiencing this issue?

**Comment by chrissainty** [comment]
@rleath82 Could you provide some example code showing your issue, please?

**Comment by rleath82** [comment]
https://github.com/rleath82/BlazoredTest

I've reduced most of the code to make it easier to look at. If you need anything else, please let me know. Thanks!

**Comment by rleath82** [comment]
Basically, I have an Index component that is calling an API to load data. I have a button that loads a modal form to edit that data. When closing the modal, the Index component is not refreshing to show the new data until I manually refresh.

**Comment by chrissainty** [comment]
Thanks for providing some sample code. So the long and short of it is that you shouldn't need to call `StateHasChanged` at all. The modal does this internally as part of calling either `Modal.Close` or `Modal.Cancel`. Have you tried removing it completely?

I would also suggest checking out the sample applications in this repo for reference implementations.

**Comment by chrissainty** [comment]
@rleath82 Are you still having an issue? As I haven't heard anything for a while I'm going to close this issue for now. But please reopen it if you are still having a problem.
