### ISSUE TITLE
Modal doesn't close when previous/next browser buttons clicked

### ISSUE THREAD

**Issue by mshortt96** [Blazored/Modal#87]
Not sure if this issue has been raised before but I've noticed that the modal will stay open when the user navigates to the previous or next page in the browser's session history. Are there any plans for a fix?

Thanks in advance!

**Comment by chrissainty** [comment]
Thanks for raising this @mshortt96, it's not something which has been brought up before. 

I think we should be able to fix this by using the `NavigationManager.LocationChanged` event to detect route changes and close the modal.

**Comment by chrissainty** [comment]
@mshortt96 I've just looked at this but I can't seem to replicate the behaviour. I'm using the sample app from the repo, if I open a modal then use the browsers back button the modal disappears as expected. 

Could you provide a repro of the issue?
