### ISSUE TITLE
Subheader parameter

### ISSUE THREAD

**Issue by ambiguousrocket** [Blazored/Modal#89]
![Teams_2020-01-15_14-09-04](https://user-images.githubusercontent.com/42182755/72440392-a58d0900-37a0-11ea-84ad-707d0256ff47.png)

I'd like to be able to add a subheader as a parameter below the Modal title.

Thoughts? I can make a start on implementing this.

**Comment by chrissainty** [comment]
Hey, would you mind giving me a day or two to think on this?

I'm wondering if it would be better to implement a header template to allow developers full control over things rather than only be able to set some title text.

**Comment by ambiguousrocket** [comment]
Cool! I think a customisable header template would be excellent.

I can work around it in the meantime with the HideHeader option.

**Comment by chrissainty** [comment]
I've been looking into this feature this morning and it's not going to be quite as straightforward as I hoped. The idea of a template is fine but it's a bit clunky for a developer I think. I've got some other stuff I need to get done right now, and as you have a workaround, I'm going to park this for a week or two and have a longer think.

**Comment by chrissainty** [comment]
Hi @ambiguousrocket, I've been looking at this over the past couple of days and I don't think a customisable header option is going to work.

I think the route you have taken with hiding the header and creating your own in the component being displayed is probably the best option at this point in time. I'm going to close this as a won't fix for now but I'm happy to look at it again if there is enough interest.
