### ISSUE TITLE
Show and get result in single method 

### ISSUE THREAD

**Issue by anotherdeveloper** [Blazored/Modal#94]
Is it possible to get the results back in a single method call?
Something like var result=Modal.Show(...);

Or is it possible to wrap the method call in another method that gives the same result, i.e. something that doesn't disrupt program flow with a callback?

**Comment by chrissainty** [comment]
The quick answer is no. When you invoke the modal by calling the `Show` method, you are, in fact, invoking an event which triggers the modal to show. Due to this, there is no way to return back to the calling code with a result.

**Comment by anotherdeveloper** [comment]
That's unfortunate. Thanks for your reply.

**Comment by chrissainty** [comment]
Could I ask what you dislike about the callback approach? This is very much the programming model for Blazor so I think you will encounter this a lot.

**Comment by anotherdeveloper** [comment]
It disrupts program flow. var line =Console.ReadLine() is better than Console.ReadLine(OtherMethodWhereResultWillBeDelivered);

I haven't come across other examples of this in Blazor, but I'm only on my first Blazor project. 

If anyone can think of a way to get what I want please let me know (other than timed polling).

**Comment by chrissainty** [comment]
Blazor uses an event-based programming model, you're going to see callbacks used all over the place. Have a look at the [Blazing Pizza workshop app](https://github.com/dotnet-presentations/blazor-workshop/blob/master/src/BlazingPizza.Client/Shared/ConfigurePizzaDialog.razor) which has a dialog component. It doesn't do things the way you're looking for either but maybe it's closer to what you want.

Good luck with your search.

**Comment by Liero** [comment]
@chrissainty:

what about `var result=await Modal.ShowAsync(...);` :)


implementation:

```csparp
public static Task ShowAsync(this IModalService modalService, ...) 
{
   var tsc = new TaskCompletionSource<ModalResult>();
   void onClose(ModalResult result)  {
      modalResult.OnClose -= onClose;
      tsc.SetResult(modalService);
   }
   modalResult.OnClose += onClose;
   modalService.Show(...)
   return tsc.Task;
}
