### ISSUE TITLE
blazor 3.2.0-preview.1 upgrade

### ISSUE THREAD

**Issue by dazinator** [Blazored/Modal#95]
Blazor 3.2.0-preview.1 has been released, is it worth upgrading?

https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/

**Comment by chrissainty** [comment]
I'm not sure what you mean, is your issue related to this project? Or just a general question?

**Comment by dazinator** [comment]
Sorry I should have been more clear.
With the release of blazor 3.2.0 preview 1, do you think it's worth updating the sample etc to reference the latest blazor packages and verify the modal still works with the latest blazor release? 

https://github.com/Blazored/Modal/blob/master/samples/BlazorSample/BlazorSample.csproj#L14

Nope - wasnt meant to come accross as a general question about the worthwhileness of updating blazor in out apps in general ;-)

**Comment by dazinator** [comment]
- I'm using this modal in a blazor 3.2.0 preview 1 app just fine, so it's really just an issue about whether you consider keeping the sample up to date worthwhile for cosmetic purposes!

**Comment by chrissainty** [comment]
Thanks for clarifying @dazinator 😄 

Yes, it would be good to upgrade the Wasm project and keep it current. Happy to take a PR for this if you fancy doing it?

**Comment by chrissainty** [comment]
The project is now upgraded.
