### ISSUE TITLE
Modal Container is appearing on the NavMenu

### ISSUE THREAD

**Issue by marciusnery** [Blazored/Modal#96]
Hi!

I'm using version 3.1.1 and on the main screen (MainLayout) the modal-container div is showing, and when I give a show on the modal, it's only open in that small space.

I'm placing the controller as below:
`<div class="sidebar">`
`<NavMenu />`
`</div>`

`<BlazoredModal DisableBackgroundCancel="true" HideHeader="true" HideCloseButton="true" />`

This problem started to happen suddenly. Before it worked perfectly. Could anyone help?

**Comment by chrissainty** [comment]
Can you provide all of the code for your main layout component please.

**Comment by marciusnery** [comment]
```
@inherits LayoutComponentBase
@inject SessionPage SessionPage

<div class="sidebar">
    <NavMenu />
</div>

<BlazoredModal DisableBackgroundCancel="true" HideHeader="true" HideCloseButton="true" />

<div class="main">
    <div class="top-row px-4">
        <div class="row col-12">
            <div class="text-left col-7">
                <b>@SessionPage.Description</b>
            </div>
            <div class="text-right col-5">
                <AuthorizeView>
                    Olá &nbsp<b> @context.User.Identity.Name</b>                    
                </AuthorizeView>
            </div>
        </div>
    </div>
    <div class="content px-4">
        @Body
    </div>
</div>
```

**Comment by chrissainty** [comment]
Thanks, everything looks good to me. Are you sure the CSS is loading correctly and that you've not got any caching issues with it? Have you tried a hard reload of the browser for example? Might be handy to see a screenshot of what's happening as well, if possible?

**Comment by marciusnery** [comment]
My index page:

```
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>DVCE</title>
    <base href="/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/site.css" rel="stylesheet" />
    <link href="_content/Blazored.Modal/blazored-modal.css" rel="stylesheet" />
</head>

<body>
    <app>Loading...</app>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <script src="_framework/blazor.webassembly.js"></script>
</body>

</html>
```

**Comment by marciusnery** [comment]
The image:
[https://postimg.cc/mc4shj54](url)

**Comment by marciusnery** [comment]
Another image

![blazor2](https://user-images.githubusercontent.com/4802400/74345549-02beaf00-4d8d-11ea-871c-374664374c0c.jpg)

**Comment by chrissainty** [comment]
The CSS isn't being loaded for some reason. Have you tried clearing your cache as I mentioned earlier? This has happened before to other after an update. Also, check the sources tab in the dev tools and make sure the CSS file for the modal is showing.

**Comment by marciusnery** [comment]
The content is empty. What to do?
![blazor3](https://user-images.githubusercontent.com/4802400/74356871-d1021400-4d9d-11ea-8177-176ffe207641.jpg)

**Comment by chrissainty** [comment]
Could you please answer this question - **Have you tried clearing your cache as I mentioned earlier?**

If you have and that hasn't worked. I would suggest uninstalling the package and reinstalling it.

**Comment by marciusnery** [comment]
Yes, I cleared the browser cache.

I will try to reinstall.

**Comment by marciusnery** [comment]
Nothing works. I installed version 3.0.0, 3.1.1, cleaned the cache and the contents of the css file remain empty.

**Comment by chrissainty** [comment]
Have you tried opening the site in a private/incogneto window?

I've just created a brand new Blazor project and added the package and everything works as expected so this is definitely a local issue.

**Comment by marciusnery** [comment]
I cleaned up the solution, changed the ASPNETCORE_ENVIRONMENT environment variable on the client and server as they were different, and it worked.

Thank you for your support.
