### ISSUE TITLE
Adding Blazored.Modal package to project causes Microsoft.AspNetCore.Components.Analyzer to be loaded twice

### ISSUE THREAD

**Issue by goodisontoffee** [Blazored/Modal#97]
This appears to be down to the Sdk.props file at C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.Web\Sdk pulling the code analyzer into the project but it also coming in via the dependencies within Blazored.Modal.

If `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` is set then this causes a build issue. We can `<NoWarn>8034</NoWarn>` to prevent the build issues, but I figured I'd bring it to your attention just in case you need to patch something your end.

Steps to reproduce:

1. `dotnet new blazorserver -n Example`
1. `cd Example`
1. `dotnet add package Blazored.Modal`
1. `dotnet build`

```
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 173.45 ms for C:\Users\*********\RiderProjects\Example\Example.csproj.
CSC : warning CS8034: Unable to load Analyzer assembly C:\Users\*********\.nuget\packages\microsoft.aspnetcore.components.analyzers\3.1.0\analyzers\dotnet\cs\Microsoft.AspNetCore.Components.Analyzers.dll : Assembly with same name is already loaded [C:\Users\*********\RiderProjects\Example\Example.csproj]
CSC : warning CS8034: Unable to load Analyzer assembly C:\Users\*********\.nuget\packages\microsoft.aspnetcore.components.analyzers\3.1.0\analyzers\dotnet\cs\Microsoft.AspNetCore.Components.Analyzers.dll : Assembly with same name is already loaded [C:\Users\*********\RiderProjects\Example\Example.csproj]
  Example -> C:\Users\*********\RiderProjects\Example\bin\Debug\netcoreapp3.1\Example.dll
  Example -> C:\Users\*********\RiderProjects\Example\bin\Debug\netcoreapp3.1\Example.Views.dll

Build succeeded.

CSC : warning CS8034: Unable to load Analyzer assembly C:\Users\*********\.nuget\packages\microsoft.aspnetcore.components.analyzers\3.1.0\analyzers\dotnet\cs\Microsoft.AspNetCore.Components.Analyzers.dll : Assembly with same name is already loaded [C:\Users\*********\RiderProjects\Example\Example.csproj]
CSC : warning CS8034: Unable to load Analyzer assembly C:\Users\*********\.nuget\packages\microsoft.aspnetcore.components.analyzers\3.1.0\analyzers\dotnet\cs\Microsoft.AspNetCore.Components.Analyzers.dll : Assembly with same name is already loaded [C:\Users\*********\RiderProjects\Example\Example.csproj]
    2 Warning(s)
    0 Error(s)
```

**Comment by chrissainty** [comment]
Hi @goodisontoffee, I've just tried to recreate your issue but I'm not seeing the error my end. What version of dotnet have you got installed?

**Comment by goodisontoffee** [comment]
3.1.101

**Comment by chrissainty** [comment]
Thanks, I have 3.1.100, I'm just updating now.

**Comment by goodisontoffee** [comment]
And I’ll try it on another machine my end.

**Comment by chrissainty** [comment]
I'm now getting the error on my machine as well, it's something to do with the latest .NET Core release.

**Comment by chrissainty** [comment]
I've just updated the package, it seems I'd updated to 3.1.100 but not 3.1.101. It's just been pushed to NuGet and should be available in the next half hour. Let me know if you're still seeing an issue after the update.

**Comment by goodisontoffee** [comment]
Already propagated and looks good to me. Thanks for the amazingly rapid response.
